### ISSUE TITLE
error asyncio

### ISSUE THREAD

**Issue by Chun78HunZi** [tensorflow/federated#1035]
RuntimeWarning: coroutine 'wrap_coroutine_in_current_trace_context.<locals>._' was never awaited
  handle = ready.popleft()
ERROR:asyncio:Exception in callback _patch_task.<locals>.step()
handle: <Handle _patch_task.<locals>.step()>

tff version = 0.15.0
python version = 3.6

**Comment by hbmcmahan** [comment]
Can you provide steps to reproduce this error? Thanks.

**Comment by michaelreneer** [comment]
Closing this issue, please feel free to reopen with step to reproduce this issue.
