### ISSUE TITLE
My custom loss function cannot be used

### ISSUE THREAD

**Issue by shine-1055** [tensorflow/federated#1042]
class focal_loss(tf.keras.losses.Loss):
    def __init__(self,alpha=0.25, gamma=2,reduction = tf.keras.losses.Reduction.AUTO,name='focal_loss'):
         super().__init__(reduction=reduction,name=name)
         self.alpha = alpha
         self.gamma = gamma
    def call(self, y_true, y_pred):
         alpha = self.alpha
         gamma = self.gamma
         alpha = tf.constant(alpha, dtype=tf.float32)
         gamma = tf.constant(gamma, dtype=tf.float32)
         y_true = tf.cast(y_true, tf.float32)
         y_pred = tf.cast(y_pred, tf.float32)
         ones = K.ones_like(y_true)
         alpha_t = y_true * alpha + (ones - y_true) * (1 - alpha)
         p_t = y_true * y_pred + (ones - y_true) * (ones - y_pred) + K.epsilon()
         focal_loss = -alpha_t * K.pow((ones - p_t), gamma) * K.log(p_t)
        return focal_loss

TypeError: Expected tensorflow.python.keras.losses.Loss or collections.abc.Sequence, found type.

**Comment by shine-1055** [comment]
I have solved this problem, thanks

**Comment by darpitdavetamu** [comment]
@shine-1055 can you please mention how did you solve the problem.
