### ISSUE TITLE
Is TFF already used in production environment?

### ISSUE THREAD

**Issue by zpcalan** [tensorflow/federated#1044]
Hi, developers form TFF.
I'm new to this project and I have this question after reading some of your tutorials: Is TFF already used in production environment?
According to the tutorial, TFF is for researchers. But maybe there're some core APIs could be used in in production environment.
For example: Federated learning with great amount of mobile devices and several central servers.

**Comment by ZacharyGarrett** [comment]
TFF's execution stack can be used in production environments for cross-silo settings, setting up services on cloud stacks its viable. Searching can come up with companies going in this direction. However TFF does not provide a runtime for executing on mobile devices (cross-device settings) at this time.
