### ISSUE TITLE
TypeError: tf___forward_pass() missing 1 required positional argument: 'batch_input'

### ISSUE THREAD

**Issue by snehasrav25** [tensorflow/federated#1059]
**Describe the bug**
Throwing me an error tf___forward_pass() missing 1 required positional argument: 'batch_input' when trying to train the model on federated data
**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):  TensorFlow Federated 0.17.0,tensorflow==2.3.0
* Python version:python 3.6 (pip 21.0)
* Bazel version (if building from source):
* CUDA/cuDNN version:10.2
* What TensorFlow Federated execution stack are you using?

**Expected behavior**
The model should be successfully trained on federated data

**Additional context**
I amtrying to run the same example given in the image classification and following the same steps,however  i faced the below error log. Not sure if it is because of the versions compatability.
i got error when executing below statements.

iterative_process = tff.learning.build_federated_averaging_process(
    model_fn,
    client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),
    server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0))

Error Log:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-ac50a57ff3b7> in <module>
      1 iterative_process = tff.learning.build_federated_averaging_process(
      2     model_fn,
----> 3     client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02)
      4     )

/data/snehasan/federated/lib/python3.6/site-packages/tensorflow_federated/python/learning/federated_averaging.py in build_federated_averaging_process(model_fn, client_optimizer_fn, server_optimizer_fn, client_weight_fn, broadcast_process, aggregation_process, model_update_aggregation_factory, use_experimental_simulation_loop)
    227       signature `({input_values}@CLIENTS-> output_values@SERVER)`. Must be
    228       `None` if `model_update_aggregation_factory` is not `None.`
--> 229     model_update_aggregation_factory: An optional
    230       `tff.aggregators.WeightedAggregationFactory` that constructs
    231       `tff.templates.AggregationProcess` for aggregating the client model

/data/snehasan/federated/lib/python3.6/site-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py in build_model_delta_optimizer_process(model_fn, model_to_client_delta_fn, server_optimizer_fn, broadcast_process, aggregation_process, model_update_aggregation_factory)
    608   Raises:
    609     ProcessTypeError: if `broadcast_process` or `aggregation_process` do not
--> 610       conform to the signature of broadcast (SERVER->CLIENTS) or aggregation
    611       (CLIENTS->SERVER).
    612     DisjointArgumentError: if both `aggregation_process` and

/data/snehasan/federated/lib/python3.6/site-packages/tensorflow_federated/python/learning/model_utils.py in weights_type_from_model(model)
     98     # with variables created for this model.
     99     with tf.Graph().as_default():
--> 100       model = model()
    101   py_typecheck.check_type(model, model_lib.Model)
    102   return type_conversions.type_from_tensors(ModelWeights.from_model(model))

<ipython-input-22-4c89b9220bfc> in model_fn()
      7       input_spec=preprocessed_example_dataset.element_spec,
      8       loss=tf.keras.losses.SparseCategoricalCrossentropy(),
----> 9       metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

/data/snehasan/federated/lib/python3.6/site-packages/tensorflow_federated/python/learning/keras_utils.py in from_keras_model(keras_model, loss, input_spec, loss_weights, metrics)
    153 
    154   return model_utils.enhance(
--> 155       _KerasModel(
    156           keras_model,
    157           input_spec=input_spec,

/data/snehasan/federated/lib/python3.6/site-packages/tensorflow_federated/python/learning/keras_utils.py in __init__(self, keras_model, input_spec, loss_fns, loss_weights, metrics)
    275 
    276         if len(self._loss_fns) == 1:
--> 277           batch_loss = self._loss_fns[0](y_true, y_pred)
    278         else:
    279           batch_loss = tf.zeros(())

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    695     self._concrete_stateful_fn = (
    696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 697             *args, **kwds))
    698 
    699     def invalid_creator_scope(*unused_args, **unused_kwds):

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3073             arg_names=arg_names,
   3074             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3075             capture_by_value=self._capture_by_value),
   3076         self._function_attributes,
   3077         function_spec=self.function_spec,

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/eager/function.py in bound_method_wrapper(*args, **kwargs)
   3733     # However, the replacer is still responsible for attaching self properly.
   3734     # TODO(mdan): Is it possible to do it here instead?
-> 3735     return wrapped_fn(*args, **kwargs)
   3736   weak_bound_method_wrapper = weakref.ref(bound_method_wrapper)
   3737 

/data/snehasan/federated/lib64/python3.6/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

TypeError: in user code:

    TypeError: tf___forward_pass() missing 1 required positional argument: 'batch_input'

**Comment by ZacharyGarrett** [comment]
To confirm, the tutorial at:
https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification
https://github.com/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb

Is having this problem?

Running it as-is from Colab (https://colab.sandbox.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb) all 44 code cells run completely without error.

Could the issues be extended to include more details about the environment? Were there any changes at all to the code in the tutorial linked above?

**Comment by michaelreneer** [comment]
Thanks for the well documented issue; however, we can not reproduce your results. I'm going to close this, please feel free to reopen if you are still seeing this.
