### ISSUE TITLE
Problem of "no attribute 'from_compiled_keras_model'", any alternative?

### ISSUE THREAD

**Issue by sumeyyegsu** [tensorflow/federated#1212]
I have tensorflow version 2.2.0 and tensorflow_federated version 0.14.0. In the code, I have the following line:

`return tff.learning.from_compiled_keras_model(keras_model, sample_batch)`

and it generates the following error:

`AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'from_compiled_keras_model'`

I don't know what can I use as an alternative/equivalent to it (because `from_compiled_keras_model` is removed from the current tensorflow_federated). 

Thank you.

**Comment by jkr26** [comment]
Hi @sumeyyegsu 

This should be addressable simply by using `tff.learning.from_keras_model` instead, and just not compiling the Keras model before passing to TFF.
