### ISSUE TITLE
TFF GCP Setup Tutorial/Guide syntax error

### ISSUE THREAD

**Issue by legenderyLuke** [tensorflow/federated#1232]
**Issue**
Hi while I was going through the GCP Setup tutorial for TFF, I found that after running step
>6. Run the client container interactively.
> The string "Hello World" should print to the terminal.
`$ docker run \
    --interactive \
    --tty \
    --name=tff-client \
    --volume ~:/simulation \
    --workdir /simulation \
    <registry>/tff-client \
    bash`

of [4. Run a simulation on a client container.](https://www.tensorflow.org/federated/gcp_setup#4_run_a_simulation_on_a_client_container)
I got the following error regarding the `--volume` flag: 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33724568/111151235-17b8d380-8587-11eb-94b0-98aac1995b40.png)
**Potential Solution**
It looks like `--volume ~/:/simulation` solves the problem, but I'm still not getting "Hello World", could you pls fix that?

**Comment by ZacharyGarrett** [comment]
Thank you for the report!

Would you be up for submitting a PR to update the guide to the correct docker `--volume` flag? The source can be found in this markdown file https://github.com/tensorflow/federated/blob/master/docs/gcp_setup.md

Its hard to tell without more information why `"Hello World!"` still isn't being printed. Any chance of attaching the logs of what happens after the `--volume` flag is changed?

**Comment by legenderyLuke** [comment]
> **Issue**
> Hi while I was going through the GCP Setup tutorial for TFF, I found that after running step
> 
> > 1. Run the client container interactively.
> >    The string "Hello World" should print to the terminal.
> >    `$ docker run \     --interactive \     --tty \     --name=tff-client \     --volume ~:/simulation \     --workdir /simulation \     <registry>/tff-client \     bash`
> 
> of [4. Run a simulation on a client container.](https://www.tensorflow.org/federated/gcp_setup#4_run_a_simulation_on_a_client_container)
> I got the following error regarding the `--volume` flag:
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/33724568/111151235-17b8d380-8587-11eb-94b0-98aac1995b40.png)
> **Potential Solution**
> It looks like `--volume ~/:/simulation` solves the problem, but I'm still not getting "Hello World", could you pls fix that?
