### ISSUE TITLE
Memory explodes

### ISSUE THREAD

**Issue by raghavchugh21** [tensorflow/federated#1245]
While running the following command:
bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1500 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd --server_learning_rate=1 --clients_per_round=10 --client_epochs_per_round=1 --experiment_name=cifar100_fedavg
the VRAM usage explodes.
It quickly reaches 8.9 GB in the first round. It remains stable, until around the 125. round, when it doubles to 16.9 GB. This phenomenon repeats itself until the training crashes.

**Comment by ferasbg** [comment]
Given that this library functionally wraps each function for the conjugate training components, note that there may be a problem with tensorflow federated and the GPU memory allocation during training, which is especially something to keep in mind of if you are training on a single GPU with multiple instances of the networks e.g. the client models training in federated environment. This could be incorrect, but I would recommend looking into your system metadata to narrow down your problem.

**Comment by zcharles8** [comment]
Hi @raghavchugh21. It seems like this might be related to https://github.com/google-research/federated/issues/29. Additionally, this issue seems to be specifically related to the `federated_research` repository, so it might be better to post your issue there.

**Comment by zcharles8** [comment]
@raghavchugh21 I believe this issue is fixed by de97c52ca835b5557c0c1c9dbd768f742a2739f5. If possible, can you confirm this is the case by running the same command using the latest nightly version of TFF?

**Comment by zcharles8** [comment]
Based on feedback from google-research/federated#29, I believe that this has been resolved. Feel free to re-open it if the issue persists.
