### ISSUE TITLE
DataLossError upon loading dataset using tf.data.experimental.load

### ISSUE THREAD

**Issue by AHabes** [tensorflow/federated#1265]
I would like to train two independent ```TFF``` models using ```emnist dataset```. Each model should train on a ```1000``` distinct participants randomly drawn from the dataset.

Code below
```python
emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data()

participants_ids = np.random.choice(a=emnist_train.client_ids, 
                                    size=1000,
                                    replace=False)

federated_dataset = 
        [data_train.create_tf_dataset_for_client(i) for i in participants_ids]

nested_dataset = tf.data.Dataset.from_tensor_slices(federated_dataset)
```
Trying to save the dataset using the function ```tf.data.experimental.save```

```python
tf.data.experimental.save(nested_dataset, 'model_dataset')
```
the warning below is generated. However, the save is completed.

```python
E tensorflow/core/framework/dataset.cc:89] The Encode() method is not implemented for DatasetVariantWrapper objects.
```

**The problem occurs upon loading the dataset and trying to inspect its contents**
```python
dataset = tf.data.experimental.load('model_dataset', 
                      element_spec= 
                      DatasetSpec(collections.OrderedDict([
                         ('label', TensorSpec(shape=(), dtype=tf.int32)),
                         ('pixels', TensorSpec(shape=(28, 28), dtype=tf.float32))]), 
                      TensorShape([])

# verifying elements
for example in dataset:
        print(example)
```
Error below
```python
tensorflow.python.framework.errors_impl.DataLossError: Unable to parse tensor from stored proto.
```
Trying other methods such as ```pickle.dump``` and ``` np.save```, all resulted in error below even after converting the dataset into ```numpy.ndarray``` using ```np.asarray()```
```python
pickle.dump(np.asarray(nested_dataset), open('model_dataset', 'wb'))

tensorflow.python.framework.errors_impl.InternalError: Tensorflow type 21 not convertible to numpy dtype.
```

Env details
```python
python -V 3.8.5
tensorflow==2.4.1
tensorflow-datasets==4.2.0
tensorflow-federated==0.18.0
Keras==2.4.3
numpy==1.19.2
```
Is this a ```bug```, or is there any good way to slice the dataset into clients and save the newly created datasets ?

**Comment by zcharles8** [comment]
Hi @AHabes. Generally, `tf.data.experimental.save` is not suitable for saving federated datasets, since there is no way to disambiguate which examples are associated to each client. The warning 

If you're interested in saving federated datasets, you can use `tff.simulation.FilePerUserClientData`, see https://www.tensorflow.org/federated/api_docs/python/tff/simulation/FilePerUserClientData. Unless I'm mistaken, this seems to meet your exact use case.

Note: If you're using the tensorflow-federated-nightly, then you would instead use `tff.simulation.datasets.FilePerUserClientDatea`.

**Comment by zcharles8** [comment]
Also note that `FilePerUserClientData` would be used to load the federated datasets, once you've saved the datasets to disk. How you want to do this is up to you, though typically a `tf.io.TFRecordWriter` is a good way to proceed in such cases (see https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/simulation/datasets/file_per_user_client_data_test.py for an example of how to use this).

**Comment by AHabes** [comment]
@zcharles8,Thanks for the follow up, and for the useful info indeed.

Actually, the main idea is to use this ```federated dataset``` to train a ```federated model```,  then transform this same dataset into a ```flatten``` one and save it in order to process it later and use it to train a traditional ```centralized model```. 

This final intension is to establish a comparison between the ```federated model``` and the ```centralized model``` when trained on the same dataset. 

That is reason behind the attempt to convert the federated dataset into a flatten format usable by a traditional centralized model and save it.

**Comment by zcharles8** [comment]
@AHabes is there a good reason to save the centralized dataset? It sounds like `ClientData.create_tf_dataset_from_all_clients` is exactly the functionality you want (amalgamating a dataset across clients).

From the code snippet above, it looks like you're trying to use the EMNIST dataset, but with only 1000 of the clients. Can you elaborate on this? For training purposes, you only need to sample a small number per round to get decent convergence on most models, and for testing, I don't see the benefit of throwing away client data.

**Comment by AHabes** [comment]
@zcharles8, Thanks for the follow up, much appreciated

Actually, I would run several experiments, each with different expected number of participants (ranging from ~10 to ~1000). 

In general, the process goes like this:

1. Experiment with various sampling techniques (Poisson, uniform, Binomial etc ..) to sample an expected number of participants per round (say 1000).
2. Train a federated model for x rounds based on the clients sampled at each round.
3. Collect the ids of clients participated in the federated model
4. Prepare a centralized dataset from the participants' datasets (and ideally save it for future usage and referencing).
4. Use the centralized dataset to train a traditional centralized model for x epochs.
5. Compare the performance of federated vs traditional models trained on the same dataset (to investigate the effects of sampling techniques and number of participants).

Using ```ClientData.create_tf_dataset_from_all_clients``` I would assume I need to first slice the ```ClientData``` to contain only the data of the sampled participants (step 1 above) before calling ```create_tf_dataset_from_all_clients```. Otherwise, it will create the centralized dataset out of all 3400 participants ?

**Comment by zcharles8** [comment]
@AHabes I believe that https://www.tensorflow.org/federated/api_docs/python/tff/simulation/ClientData#from_clients_and_fn will do exactly what you want. Basically, you can use this to create a new `ClientData` that only uses the smaller number of clients, in which case `create_tf_dataset_from_all_clients` would give exactly the desired outcome.

Note that to make this more performant, you may want to pass in `emnist_train.dataset_computation` instead, so you would end up doing something like

```
emnist_train, _ = tff.simulation.datasets.emnist.load_data()
subsampled_clients = emnist_train.client_ids[:10]
subsampled_train = tff.simulation.datasets.ClientData.from_clients_and_fn(
  subsampled_clients, emnist_train.dataset_computation)
```

**Comment by zcharles8** [comment]
Hi @AHabes. I'm closing this issue due to a lack of activity. If the suggestion above does not work, feel free to re-open this.
