### ISSUE TITLE
How to run tensorflow performance simulator and set fusion method?

### ISSUE THREAD

**Issue by ArtyZe** [tensorflow/federated#1351]
Thanks for your great work. 
When read a paper of google engineer, which refers to **TensorFlow Performance Simulator** to estimate the runtime for : with no fusion, with default fusion, with customer fusion. But I don't find doc about this, are there some examples to show how to use TensorFlow Performance Simulator ?

**Comment by jkr26** [comment]
Hi @ArtyZe 

To me this sounds like something that would be relevant to Grappler, and static TensorFlow Graph optimization, as in [this talk](https://web.stanford.edu/class/cs245/slides/TFGraphOptimizationsStanford.pdf) by a core TF team member. But this is a little outside of what we do in TFF.

You may want to repost this question on the [TensorFlow main GitHub page](https://github.com/tensorflow/tensorflow), as Grappler is a subcomponent there, or on StackOverflow with the TensorFlow tag.

Thanks!
