### ISSUE TITLE
How do I modify this code?

### ISSUE THREAD

**Issue by amir11877** [tensorflow/federated#1458]
tf.keras.layers(body = concatenate([upbody1, downbody1],axis=-1)),
tf.keras.layers(body1 = LSTM(8, activation='tanh'))(body),

tf.keras.laayers(out = Dense(60, activation='softmax'))(body1),

tf.keras.layers(model = Model([bdbd, rhrh, lhlh, rfrf, lflf]), out),
])

File "<ipython-input-367-2708f0ec1ea2>", line 105
      ])
      ^
  SyntaxError: invalid syntax

**Comment by zcharles8** [comment]
Closed, as it is a duplicate of #1471.
