### ISSUE TITLE
anyway to install tff with tensorflow-metal

### ISSUE THREAD

**Issue by yshen22** [tensorflow/federated#1516]
I'm using my gpu version on macos(tensorflow-metal).
https://github.com/apple/tensorflow_macos
Tensorflow version:tensorflow2.4.0-rc0
However I can not installing a tff version on tensorflow2.4.0-rc0
When I am trying to install tensorflow_federated using pip install tensorflow_federated==0.18.0, it would automatically install another cpu version of tensorflow macos and replace tensorflow2.4.0-rc0 with tensorflow2.4.0cpu. Anyway to have a gpu version of tff in macos?

**Comment by yingding** [comment]
In a pyhton3.8 virtual env, for the tf base version 2.5 and tensorflow_macos==2.5.0 and tensorflow-metal seem to work:
```
SYSTEM_VERSION_COMPAT=0 pip install tensorflow-macos==2.5.0 tensorflow-federated==0.19.0 tensorflow-metal 
```

**Comment by yingding** [comment]
I tested the tff example from https://www.tensorflow.org/federated, it is kind of wired to see the cpu is quick.
```
| type      | time in secs | 
|-----------|--------------|
| cpu       | 3.46         |
| gpu/metal | 8.57         |

```

**Comment by yingding** [comment]
An [update](https://github.com/tensorflow/federated/issues/2307#issuecomment-1073244816) on this with an intel based works with python@3.8
```
SYSTEM_VERSION_COMPAT=0 pip install tensorflow-macos==2.8.0 tensorflow-metal==0.4.0;
SYSTEM_VERSION_COMPAT=0 pip install tensorflow-federated==0.20.0
```

**Comment by michaelreneer** [comment]
Closing as this does not appear to be an issue anymore.
