### ISSUE TITLE
Multiple processes cannot simultaneously read StackOverflow word counts

### ISSUE THREAD

**Issue by krishnap25** [tensorflow/federated#1593]
Hi, 

Whenever I have multiple jobs trying to read the word counts from the StackOverflow dataset on TFF on a compute cluster, some of them end up crashing with this error:

```
File "path_to_conda_env/lib/python3.8/site-packages/tensorflow_federated/python/simulation/datasets/stackoverflow.py", line 167, in load_word_counts
    word, count = line.split()
ValueError: not enough values to unpack (expected 2, got 1)
```
The error does not occur every single time but it occurs quite frequently.

Here is a minimal working example which can reproduce the same error pretty reliably (you might have to run this a few times):
```
import tensorflow_federated as tff
import time
from multiprocessing import Pool

data_dir = "/path/to/downloaded/data"

def my_func(t):
     time.sleep(t)  # optional
     vocab = tff.simulation.datasets.stackoverflow.load_word_counts(cache_dir=data_dir)
     return len(vocab) + t

with Pool(3) as p:
    print(p.map(my_func, [1, 5, 10]))

```

**Environment**
* OS Platform and Distribution: Ubuntu 20.04
* Python package versions: tff: 0.19.0 and tf: 2.5.0
* Python version: 3.8
* Bazel version (if building from source): N/A (downloaded via pip)
* CUDA/cuDNN version: CUDA:11.1 and cuDNN: 8. The error also occurs with CUDA_VISIBLE_DEVICES=""
* What TensorFlow Federated execution stack are you using? Simulation

**Expected behavior**
I expect multiple jobs to be able to read this file simultaneously (given that it is not being edited by any of them). Fixing this issue will make large-scale experimentation much easier for me. Thank you!

**Comment by zcharles8** [comment]
@krishnap25 Just to get some more context, can you explain why you're trying to read the word counts in each process? On first examination, I would imagine that reading in one process, and then doing the post-reading work in parallel would be the easiest (and fastest) way forward.

**Comment by krishnap25** [comment]
Hey @zcharles8, thanks for the prompt response! 

I'm trying to run a number of jobs in parallel on a slurm cluster. Each job loads the word counts and does some further processing. I have found that the jobs crash when they are start running at around the same time. The example I gave above with multiprocessing tried to simulate that in a self-contained manner. 

Since each job runs on a different machine and can potentially be scheduled to run at a different time, I cannot read the word counts once per batch of jobs. However, I realize that the simplest workaround for me is to read the word counts and store the relevant parts in a separate file, and have my jobs load this file directly. 

I'm leaving the issue open because there is still a bug which prevents different processes/jobs from loading the word counts in parallel.

**Comment by zcharles8** [comment]
As far as I know, it's difficult to do multiple reads on the same file in parallel (eg. see https://stackoverflow.com/questions/18104481/read-large-file-in-parallel). Under the hood, `stackoverflow.load_word_counts()` simply downloads a file and then reads it in python. I suspect this will not behave well with parallel jobs.

One thing you may try is to have each process download the file to a separate location, to avoid parallel reads (which can be done by specifying the `cache_dir`). A more sophisticated solution may use queues to supply the dictionary of word counts to the multiple processes (eg. see https://stackoverflow.com/questions/11196367/processing-single-file-from-multiple-processes).

Disclaimer: I am not an expert in python multiprocessing.

**Comment by zcharles8** [comment]
@krishnap25 Any updates on your end? As far as I understand, this is not really a bug on TFF, this is a manifestation of the fact that doing parallel reads in python on a single file can be slow. Is there some aspect to this that makes this addressable from TFF?

**Comment by krishnap25** [comment]
@zcharles8 Sorry for the late response! 

I can have up to 32 jobs running in parallel, so keeping 32 copies of the stackoverflow dataset is infeasible, given its large size. My workaround is to process the word counts into a separate small file so that I do not encounter this error. 

I do not actually use Python multiprocessing in my use-case; I have multiple jobs running in parallel on a *slurm cluster* (the multiprocessing example is a minimal working example to reproduce that error without slurm). Therefore, I do not know how to implement a queue which can feed each job.

I'm closing this issue because I have a workaround. Thanks for your help!
