### ISSUE TITLE
Anyway to install tff with TensorFlow-rocm

### ISSUE THREAD

**Issue by yshen22** [tensorflow/federated#2239]
I have a AMD GPU, so I can't use TensorFlow-gpu for GPU training. The only way for using gpu computing on TensorFlow is by tensorflow-rocm library. 
However I can not installing a tff version on tensorflow-rocm
When I am trying to install tensorflow_federated using pip install tensorflow_federated==0.18.0, it would automatically install another cpu version of tensorflow and replace tensorflow-rocm with tensorflow2.4.0cpu. Anyway to have a gpu version of tff with AMD gpu?

**Comment by zcharles8** [comment]
Hi @yshen22. I'm not an expert in this kind of thing, but could you try something like the following:

1. `pip install tensorflow_federated`
2. `pip uninstall tensorflow`
3. `pip install tensorflow-rocm`

There may be mismatched dependencies that make this not work, but it could lead to what you want.

**Comment by yshen22** [comment]
@zcharles8  Thank you for your help. I have tried your steps. It is working now the on the surface as follows.
>>> import tensorflow_federated as tff
>>> print(tff.federated_computation(lambda: 'Hello World')())
WARNING:tensorflow:From /home/xx/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/compiler/tensorflow_computation_transformations.py:59: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From /home/xx/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/compiler/tensorflow_computation_transformations.py:59: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
b'Hello World'
However I am not sure whether it would be robust when I try more advanced functions. But I will come to your help when mismatched dependencies come. Thank you.

**Comment by zcharles8** [comment]
It sounds like this is tentatively working for now. If something strange happens, feel free to reopen.
