### ISSUE TITLE
Installing with pip breaks because TF2.0 doesn't have contrib

### ISSUE THREAD

**Issue by jeandut** [tensorflow/federated#224]
Currently you cannot install by:
`pip install --upgrade tensorflow-federated`
because it will download tf 2.0 which doesn't have a contrib module. You have to pip install a fixed version<2.0 (it works with 1.13.1 for instance).

**Comment by michaelreneer** [comment]
@jeandut Thanks for bringing this to our attention. This will be fixed in the next release. I have assigned this issue to myself and I will close it with that release. 

As you mentioned you can pip install a fixed version < 2.0 to work around this issue until then.

**Comment by xjohnxjohn** [comment]
@jeandut I found "ModuleNotFoundError: No module named 'tensorflow.python.saved_model.model_utils'" with 1.13.1.

**Comment by michaelreneer** [comment]
This is fixed in [v0.2.0](https://github.com/tensorflow/federated/tree/v0.2.0).
