### ISSUE TITLE
No 'loss' attribute

### ISSUE THREAD

**Issue by tushar-semwal** [tensorflow/federated#225]
I was able to run the Federated Image classification tutorial last week. But now this error is popping:
![tff_eror](https://user-images.githubusercontent.com/8556809/53893611-6e00ec80-4026-11e9-9a05-e03eed235a5d.PNG)

**Comment by jkr26** [comment]
Testing #226, will merge once all tests pass

**Comment by jkr26** [comment]
#226 is merged, this error should be fixed.

**Comment by tushar-semwal** [comment]
Thanks!
