### ISSUE TITLE
Federated in Tensorflow.js

### ISSUE THREAD

**Issue by bhack** [tensorflow/federated#229]
Will this api be exposed in Tensorflow.js?
So that you can join in the federation from a browser tab.

**Comment by bhack** [comment]
>Another technology, called Federated Learning(McMahan et al., 2016), enables devices to collaborativelytrain a centralized model while keeping sensitive data ondevice.  Browsers are a natural a platform for this type of application.
From https://arxiv.org/pdf/1901.05350.pdf

/cc @dsmilkov @nsthorat

**Comment by innerop** [comment]
There is already an example of Federated Learning in TensorflowJS by Google’s PAIR group. Just Google it. This I believe has the simulation environment and high level API that are missing from TFJS and TF.

**Comment by bhack** [comment]
Ok. https://github.com/PAIR-code/federated-learning

**Comment by bhack** [comment]
I hope it will be included upstream cause I don't see any commit from October.

**Comment by nsthorat** [comment]
The PAIR-code/federated-learning library is not part of tensorflow/federated officially. It was just an experiment and does not interact with this library (which is the official TensorFlow federated learning library).

**Comment by bhack** [comment]
Mhh.. it could be useful if the official Tensorflow.js repo will interact with the official federated learning library.

**Comment by nsthorat** [comment]
Yes -- that would be great, but we (TensorFlow.js team) don't currently have the cycles to do that.

**Comment by bhack** [comment]
Probably the federated target currently it is not on for a scale "a training node in every user browser tab"

**Comment by batrlatom** [comment]
@nsthorat I also thinks that federated learning would be a great thing in the Tensorflowjs and this project is best suited for it since it would turn any browser into learning node. Maybe you can talk about it with your team if you could put it on the roadmap in some meaningful future.

**Comment by krzys-ostrowski** [comment]
Hi, there are at least 2 ways of interpreting this question, (a) exposing JS equivalents of the TFF APIs that we currently offer in Python, (b) providing an in-browser JS runtime for executing TFF computations. Which one did you have in mind? I can see the advantages of (b), and it's consistent with the current system design. The advantages of (a) are less clear to me. Someone would have to make a case for it.

**Comment by bhack** [comment]
For me b has the priority over a so that you can join in a federation just with you browser tab.

**Comment by batrlatom** [comment]
b is the way

**Comment by shashwatsahay** [comment]
I kind of implemented a browser-based implementation of this with a flask server as backend, I don't know if it exactly meets the requirement of federated learning paradigm. Here is a process

1. Send base-untrained global neural network to the browser
2. Train the model on the server.
3. Send the model back to the server using the model.save() function 
4. Aggregate the model by taking the mean of the weights and biases 
5. User managed fetch call of the global model.

**Comment by batrlatom** [comment]
@shashwatsahay would you post it on github somewhere? I would like to take a look since I would use it in my project as well. By the way, take a look on openmined, they also have a federated learning implemented with tfjs

**Comment by shashwatsahay** [comment]
@batrlatom hey I will post the code in my public repository, I have looked at the openmined project, I didn't know they have already implemented the federated learning in the syftjs.

**Comment by raghu20ram** [comment]
hi @shashwatsahay that's great !! , did you post the code on github? If so can you shall the repo name? I just want to have a look at the code. I tried running the PAIR code federated TFJS but that does not work. TIA

**Comment by krzys-ostrowski** [comment]
Hi. Unfortunately, there doesn't appear to be anything actionable here at the moment, and we can't make specific promises regarding .js, so I'm going to close this issue. If you have an idea for a specific contribution to TFF, please open a separate thread. Thank you!

**Comment by shashwatsahay** [comment]
> hi @shashwatsahay that's great !! , did you post the code on github? If so can you shall the repo name? I just want to have a look at the code. I tried running the PAIR code federated TFJS but that does not work. TIA

Just a last comment I have posted the stripped of version of my code in my public repository https://github.com/shashwatsahay/pyjs_federated_learning , I couldn't post the code from the actual project due to various reasons. Hopefully this helps you in expanding your own project
