### ISSUE TITLE
CIFAR100, Train Images Not Distorted?

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/federated#2309]
**Describe the bug**
I noticed that the training images for the CIFAR100 dataset are cropped centrally (instead of distorted). Is this intentional? Thanks in advance for the help!

https://github.com/tensorflow/federated/blob/f3df9197881a93e93db6b2e7790738e829b62232/tensorflow_federated/python/simulation/baselines/cifar100/image_classification_tasks.py#L117-L120

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**

**Additional context**

**Comment by zcharles8** [comment]
Hi @HanGuo97. While my vague recollection is that it may have been intentional due to the behavior of the random distortion within a TFF computation, I'm not 100% certain. Thanks for pointing this out. I'll investigate when I get a chance.

One thing I will note: The baselines are intended only as a kind of guideline on how to evaluate federated learning methods. We strongly encourage users to use whatever works best for them, including their own custom tasks.

**Comment by HanGuo97** [comment]
Got it, thanks for the quick response!

**Comment by HanGuo97** [comment]
Hi, I just want to follow up on this question. Notably, I noticed that in the `google-research/federated` library, the preprocessing is done differently "in the past" (notably `google-research/federated/optimization/`).

More precisely, before `google-research/federated` was standardized to use `tensorflow/federated` for preprocessing, the CIFAR100 dataset is preprocessed differently that did have random cropping. It uses TFF to load the data but uses its own preprocessing, which has a flag for random cropping that is set to True by default. Later it starts to rely on this repo. Since this repo does not use random cropping, both libraries stop adding randomization (presumably).

I understand this is likely a minor detail, but I'm curious if this is expected or desired behavior (i.e., removing randomization is better)?

**Comment by zcharles8** [comment]
Hi @HanGuo97. This should be resolved by https://github.com/tensorflow/federated/commit/52eb9bdeadf1e82729e5fd572108bcd666aee8b4, which adds a toggle for whether to distort train images or not in the task. Thanks for pushing on this.

**Comment by HanGuo97** [comment]
Great to hear and thanks a ton!
