### ISSUE TITLE
ImportError: cannot import name 'computation_pb2'

### ISSUE THREAD

**Issue by wuzhiyu666** [tensorflow/federated#231]
When running the code ''tensorflow_federated/python/examples/mnist/**models_test.py**'', I got an error

File "/home/wzy/Desktop/github_project/federated-master/tensorflow_federated/python/core/impl/computation_impl.py", line 20, in <module>
    from tensorflow_federated.proto.v0 import computation_pb2 as pb
**ImportError: cannot import name 'computation_pb2'**

Then I viewed the folder  **tensorflow_federated/proto/v0**, I find there are no file named **computation_pb2**, could you please tell me what should I do? @michaelreneer @jkr26 
Thank you!

**Comment by michaelreneer** [comment]
@wuzhiyu666 Can you go into more detail by what you mean when you say "when running"? Is it possible that you are possibly not using Bazel to run the `models_test` target?

```
bazel test tensorflow_federated/python/examples/mnist:models_test
```

You can see that there is a protobuf [computation.proto](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/proto/v0/computation.proto) located at the path that you referenced. Bazel will resolve these dependencies and eventually generate the python that you are looking for `computation_pb2` from the `computation.proto`.

Take a look at our [installation instructions](https://github.com/tensorflow/federated/blob/master/docs/install.md) for how to install Bazel and test TFF.

**Comment by wuzhiyu666** [comment]
thank you so much! I will try it.

**Comment by wuzhiyu666** [comment]
Sorry, when I used bazel to compile the code, it took 2 hours and failed in the end. when I say "when running", I am running the code "`models_test`" in pycharm. I have question that can I run the code in pycharm locally without bazel and docker?
Thank you so much! @michaelreneer

**Comment by michaelreneer** [comment]
So there are a few things here:

* It's possible that it would take 2 hours to build. TFF has a source-level dependency on TensorFlow so you end up building TFF from source. This entirely depends on your machine.

* We have a hard dependency on protobuf and converting the `computation.proto` in to the missing `computation_pb2`. Which practically means that we also have a dependency on Bazel. We don't have a dependency on Docker, you could use `virtualenv` to create a local environment. Docker or `virtaulenv` are used here to keep the pip package dependencies separated from the system Python.

* You can use pycharm as an IDE if you want, but you still need to compile the protobuf. You would also need to install the packages that we do not build from source, you can find those in the `requirements.txt`.

* I am curious about the error that you got after it took 2 hours to build. Did you happen to save the log? What command ended up failing?

Keep in mind you don't need to build everything from source to **use** TFF, you can instead pip install the pip package. You would not be able to run the unit tests by only installing the pip package, but you could use and play with the API.

**Comment by wuzhiyu666** [comment]
Thank you so much! @michaelreneer 
Sorry for the late reply, I have reinstalled my operating system and run bazel again. But I got a new problem. The bazel have used up all my RAM and crash my computer. 
Could you please tell me how to sovle the problem?
Thank you!

**Comment by wuzhiyu666** [comment]
I have a new question that if using bazel is not mandatory, is there another demo can I run without bazel?
I am new to federated-leaning and just want to run a demo to see how it works.
Thank you! @michaelreneer

**Comment by jkr26** [comment]
Hi @wuzhiyu666,

If you are looking for a demo, the place I would start is the Colab notebooks linked from tensorflow.org/federated, under tutorials, e.g.:

https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification

If you open these notebooks, you will see a button for "open in Google Colab"; this will connect you to a runtime which allows you to step through the code and text, executing code block-by-block.

Hopefully this is what you are looking for! We are happy to hear of your interest in federated learning!

**Comment by michaelreneer** [comment]
@wuzhiyu666 

As I mentioned before you can simply install the pip package to use TFF or you could do as @jkr26 suggested and run one of the TFF tutorials directly in your browser in Colab. **I would strongly recommend one of these approachs, the easiest is simply running the notebook in your browser.***

Bazel is required to build TFF source. If you are having issues with Bazel RAM usage, you can check out this [bazel build options](https://www.tensorflow.org/install/source#bazel_build_options) documentation from TensorFlow or the Bazel documentation on the [local_resources](https://docs.bazel.build/versions/master/user-manual.html#flag--local_resources) flag.

**Comment by michaelreneer** [comment]
@wuzhiyu666 As a data point for us, would you mind sharing the specs of your machine?

**Comment by RansSelected** [comment]
Hi!

The error **"ImportError: cannot import name 'computation_pb2'"** still appears when running 
`python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"`

even after installation of TF Fedefrated via Bazel. At the same time running
` bazel test tensorflow_federated/python/examples/mnist:models_test`
performs well, with no error.

Specs:
MacOS Sierra 10.12
Python 3.6
PyCharm CE 2019 IDE
Conda env
