### ISSUE TITLE
Tensor is not an element of this graph

### ISSUE THREAD

**Issue by osanwe** [tensorflow/federated#236]
I've tried to reproduce a tutorial "Federated Learning for Image Classification" in Colab [1] and encountered a `ValueError` during execution

    iterative_process = tff.learning.build_federated_averaging_process(model_fn)

The error is following:

     ---------------------------------------------------------------------------
     ValueError                                Traceback (most recent call last)
     /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
        1091             subfeed_t = self.graph.as_graph_element(
     -> 1092                 subfeed, allow_tensor=True, allow_operation=False)
        1093           except Exception as e:

     /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in as_graph_element(self, obj, allow_tensor, allow_operation)
        3477     with self._lock:
     -> 3478       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
        3479 

     /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
        3556       if obj.graph is not self:
     -> 3557         raise ValueError("Tensor %s is not an element of this graph." % obj)
        3558       return obj

     ValueError: Tensor Tensor("Placeholder:0", shape=(), dtype=float32) is not an element of this graph.

How it can be solved?

[1] https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb

**Comment by ZacharyGarrett** [comment]
Thanks for the report @osanwe. We're are actively working on the next release, which will fix this.

The following link should work for the next few days, until the new release:
https://colab.sandbox.google.com/github/tensorflow/federated/blob/test_237819542/docs/tutorials/federated_learning_for_image_classification.ipynb

**Comment by jkr26** [comment]
Hi @osanwe, we updated to v0.2.0 earlier today; this notebook now works. Thanks for the vigilance!

**Comment by deepquantum88** [comment]
Hi, the above link is not working. I also faced the same issue.
