### ISSUE TITLE
Custom loss function not working

### ISSUE THREAD

**Issue by darpitdavetamu** [tensorflow/federated#2455]
### My custom-loss function
 def custom_loss(keras.losses.loss):
      return K.mean(K.square((self.y_pred - self.y_true)/self.y_true))

### Model parameters

def model_fn():    
    keras_model = create_keras_model()
    return tff.learning.from_keras_model(
      keras_model,
      input_spec=preprocessed_sample_dataset.element_spec,
      loss = custom_loss(),
      metrics=[tf.keras.metrics.MeanSquaredError()])

TypeError: Expected keras.losses.Loss, found type.

I tried looking at Custom Federated Algorithims Part 2: URL: https://www.tensorflow.org/federated/tutorials/custom_federated_algorithms_2#defining_a_loss_function

But I am unable to replicate the same in my code?

**Comment by wennanzhu** [comment]
If you want to use the `loss` argument in `tff.learning.from_keras_model`, you should assign `loss` to a `tf.keras.losses.Loss` object. See https://www.tensorflow.org/api_docs/python/tf/keras/losses/Loss. 

The https://www.tensorflow.org/federated/tutorials/custom_federated_algorithms_2 tutorial shows how to build a customized federated computation without using the `tff.learning.from_keras_model` API.

**Comment by darpitdavetamu** [comment]
@wennanzhu you mean something like this:

class custom_loss(Loss):

  def call(self, y_true, y_pred):
    y_pred = tf.convert_to_tensor_v2(y_pred)
    y_true = tf.cast(y_true, y_pred.dtype)
    return tf.reduce_mean(math_ops.square((y_pred - y_true)/y_true), axis=-1)

**Comment by darpitdavetamu** [comment]
@wennanzhu unfortunately I have tried that. But it is not working. Keep getting the same error.

**Comment by darpitdavetamu** [comment]
Created custom loss exactly as above and used as here:

def model_fn():
    keras_model = create_keras_model()
    return tff.learning.from_keras_model(
      keras_model,
      input_spec=preprocessed_sample_dataset.element_spec,
      loss = custom_loss,
      metrics=[tf.keras.metrics.MeanSquaredError()])

**Comment by wennanzhu** [comment]
@darpitdavetamu I think you need an object of `tf.keras.losses.Loss`, could you try`loss = custom_loss()`?

**Comment by darpitdavetamu** [comment]
i am getting the following error:



TypeError: in user code:

    File "/Users/darpitdave/opt/anaconda3/envs/Fl_Env/lib/python3.9/site-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py", line 353, in _compute_local_training_and_client_delta  *
        client_output = client_delta_fn(dataset, initial_model_weights)
    File "/Users/darpitdave/opt/anaconda3/envs/Fl_Env/lib/python3.9/site-packages/tensorflow_federated/python/learning/federated_averaging.py", line 100, in reduce_fn  *
        output = model.forward_pass(batch, training=True)
    File "/Users/darpitdave/opt/anaconda3/envs/Fl_Env/lib/python3.9/site-packages/tensorflow_federated/python/learning/framework/dataset_reduce.py", line 28, in _dataset_reduce_fn  *
        return dataset.reduce(initial_state=initial_state_fn(), reduce_func=reduce_fn)
    File "/Users/darpitdave/opt/anaconda3/envs/Fl_Env/lib/python3.9/site-packages/tensorflow_federated/python/learning/keras_utils.py", line 412, in forward_pass  *
        return self._forward_pass(batch_input, training=training)
    File "/Users/darpitdave/opt/anaconda3/envs/Fl_Env/lib/python3.9/site-packages/tensorflow_federated/python/learning/keras_utils.py", line 379, in _forward_pass  *
        batch_loss = tf.add_n([loss_fn(y_true=y_true, y_pred=predictions)] +
    File "/var/folders/dl/qpbnclts6xz8qb73n20zb8q80000gn/T/ipykernel_65622/3531200346.py", line 3, in call  *
        return K.mean(K.square((y_pred - y_true)/y_true))

    TypeError: Input 'y' of 'Sub' Op has type float64 that does not match type float32 of argument 'x'.

**Comment by wennanzhu** [comment]
It seems the custom loss function is working, but you are getting a type mismatch error in `tf.reduce_mean(math_ops.square((y_pred - y_true)/y_true), axis=-1)`. Have you tried to cast values to `tf.float32`?

**Comment by darpitdavetamu** [comment]
@wennanzhu Thank you for the help. Yes, i tweaked things using the cast function to match them. it's working all fine.
