### ISSUE TITLE
examples/mnist problem

### ISSUE THREAD

**Issue by drkingman** [tensorflow/federated#247]
I'm trying mnist example and something happens 

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "demo.py", line 26, in <module>
trainer = tff.learning.build_federated_averaging_process(model_fn)`

![图片](https://user-images.githubusercontent.com/22471616/54344362-a2eeee00-467b-11e9-84cc-119ecefe5a84.png)

**Comment by drkingman** [comment]
I have sorted out

**Comment by michaelreneer** [comment]
@drkingman Your issue mentions that you are trying to mnist example and your error and picture reference a `demo.py`.

Have you checked out the [install](https://www.tensorflow.org/federated/install) documentation? I would recommend first running the colabs if you are interesting in learning about federated learning. If you are interested in contributing please take a look at those install instructions and they try running the following command to run the mnist example.

```bash
bazel test //tensorflow_federated/python/examples/mnist:models_test
```

**Comment by drkingman** [comment]
@michaelreneer Thank a lot, the problem is solved.
