### ISSUE TITLE
No output from tff.federated_computation(), image classification example

### ISSUE THREAD

**Issue by ANSHUMAN87** [tensorflow/federated#250]
When i execute image classification example in the link below:
https://github.com/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb
Following the installation steps provided.
I am not getting ourput of 'Hello, World!'

System: Ubuntu 18.04
Output:
![image](https://user-images.githubusercontent.com/32511895/54412596-56f28680-4719-11e9-88c7-52a88567cbf2.png)

Please help to know the reason.

**Comment by drkingman** [comment]
I have met the same problem, as I tried using `jupyter notebook` and follow the linked example, it will be totally fine to run it.

**Comment by michaelreneer** [comment]
@ANSHUMAN87 It looks like you are using jupyter to convert the notebook to python, is that correct? Or are you possibly copying the code from the notebook into your own custom script? Have you tried to run the notebook in colab? One difference between running the code in a notebook and running the code in a script is that in a notebook the output is produced by the notebook not the python code. So when you bring the notebook into a python script you need to additionally `print` the output..

```
print(tff.federated_computation(lambda: 'Hello, World!')())
```

**Comment by ANSHUMAN87** [comment]
@michaelreneer : Thank you very much for pointing out that. It is really the root-cause. Now it is solved, thanks for your help!
