### ISSUE TITLE
 Can TFF be used for training on mobile phone?

### ISSUE THREAD

**Issue by bigpear123** [tensorflow/federated#251]
the model we can get now can be used on mobile phone for federated_learning?

**Comment by krzys-ostrowski** [comment]
We designed the system with this possibility in mind. However, at the moment there is no support in TFF for deployment to mobile devices. Only a simple local simulation runtime.

**Comment by Joostrothweiler** [comment]
@krzys-ostrowski could you please elaborate on the timeline for implementing this or work that is to be done in order to make this happen?

**Comment by jionglearningzhang** [comment]
Any suggestion if we want to have the federated learning simulated with not mobile phones but separate computers? @krzys-ostrowski

**Comment by krzys-ostrowski** [comment]
Hi. Unfortunately, we can't make any specific promises at the moment regarding support for deployment to physical devices.
