### ISSUE TITLE
Can labels be vectors when constructing datasets

### ISSUE THREAD

**Issue by skiifall** [tensorflow/federated#2560]
The output of the data set I am using is a one-dimensional vector, but there is no relevant description in the document and presentation. May I ask whether it can be achieved？

**Comment by zcharles8** [comment]
@skiifall As long as your `tff.learning.Model` can compute its forward pass, any tensor structure of a label should work. For context, many of the baselines in `tff.simulation.baselines` actually have vector-valued "labels" (eg. https://www.tensorflow.org/federated/api_docs/python/tff/simulation/baselines/stackoverflow/create_tag_prediction_task).

**Comment by skiifall** [comment]
> @skiifall As long as your `tff.learning.Model` can compute its forward pass, any tensor structure of a label should work. For context, many of the baselines in `tff.simulation.baselines` actually have vector-valued "labels" (eg. https://www.tensorflow.org/federated/api_docs/python/tff/simulation/baselines/stackoverflow/create_tag_prediction_task).

Thank you for your answer. I'll give it a try
