### ISSUE TITLE
Docs site: Tutorials link straight to ipynb files instead of colab

### ISSUE THREAD

**Issue by jvmncs** [tensorflow/federated#2561]
**Describe the bug**
Links from [this tutorials page](https://www.tensorflow.org/federated/tutorials/tutorials_overview) are just pointing to downloadable iPython notebooks. I would've expected them to open in colab, since the tutorial page specifically calls the tutorials "colab-based".

**Environment (please complete the following information):**
Brave Browser (don't think this matters though)

**Expected behavior**
Tutorials should either open up in colab or link to the GitHub-hosted version of the rendered ipynb. Alternatively, the tutorials page should just say that the tutorials are ipynb instead of "colab-based"

**Comment by zcharles8** [comment]
@jvmncs Thanks for reporting this. I saw that this was indeed happening yesterday, but can't seem to reproduce it today. Can you confirm whether or not this is still an issue for you? A nightly TF doc change might have fixed it.

**Comment by jvmncs** [comment]
Yes, looks like the tutorials are redirecting to the tensorflow.org docs site on my end again. Thanks for prompt response 👍
