### ISSUE TITLE
Remote Executor service docker image not available

### ISSUE THREAD

**Issue by Crazynovatech** [tensorflow/federated#2578]
Hi, The image gcr.io/tensorflow-federated/remote-executor-service:latest does not exist for setting remote executor service. Please let me know if there is any other option/tutorial exists for distributed federated learning.

**Environment :**
* OS Platform and Distribution: Ubuntu 20.04
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version: 3.8

**Comment by hardik-vala** [comment]
Hi, you should be able to pull `gcr.io/tensorflow-federated/remote-executor-service:0.20.0`.
