### ISSUE TITLE
FL installation doesn't end

### ISSUE THREAD

**Issue by HTGorji** [tensorflow/federated#2635]
Hi,
When I want to install the FL, it starts with installing some packages, and it's fine, but then the tf_nightly starts to be installed, but it doesn't seem right because several tf_nightly want to be installed. 
How can I solve the problem? I am installing it on Windows 10 using the following command in Anaconda Prompt:
pip install --upgrade pip
pip install --upgrade tensorflow-federated --user

.
.
.
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
Collecting tf-nightly
  Downloading tf_nightly-2.9.0.dev20220308-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220307-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 2.9 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220306-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220305-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220304-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.0 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220303-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220302-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220301-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220228-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220227-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220226-cp39-cp39-win_amd64.whl (352.9 MB)
     ---------------------------------------- 352.9/352.9 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220225-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.4 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220224-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220223-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.4 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220222-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220221-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220220-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220219-cp39-cp39-win_amd64.whl (352.8 MB)
     ---------------------------------------- 352.8/352.8 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220218-cp39-cp39-win_amd64.whl (352.7 MB)
     ---------------------------------------- 352.7/352.7 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220214-cp39-cp39-win_amd64.whl (349.8 MB)
     ---------------------------------------- 349.8/349.8 MB 2.9 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220213-cp39-cp39-win_amd64.whl (349.8 MB)
     ---------------------------------------- 349.8/349.8 MB 2.5 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220212-cp39-cp39-win_amd64.whl (349.8 MB)
     ---------------------------------------- 349.8/349.8 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220211-cp39-cp39-win_amd64.whl (349.8 MB)
     ---------------------------------------- 349.8/349.8 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220203-cp39-cp39-win_amd64.whl (349.0 MB)
     ---------------------------------------- 349.0/349.0 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220202-cp39-cp39-win_amd64.whl (348.6 MB)
     ---------------------------------------- 348.6/348.6 MB 3.0 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220201-cp39-cp39-win_amd64.whl (348.5 MB)
     ---------------------------------------- 348.5/348.5 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220130-cp39-cp39-win_amd64.whl (349.6 MB)
     ---------------------------------------- 349.6/349.6 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220129-cp39-cp39-win_amd64.whl (349.6 MB)
     ---------------------------------------- 349.6/349.6 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220127-cp39-cp39-win_amd64.whl (344.1 MB)
     ---------------------------------------- 344.1/344.1 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220126-cp39-cp39-win_amd64.whl (344.1 MB)
     ---------------------------------------- 344.1/344.1 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220125-cp39-cp39-win_amd64.whl (344.1 MB)
     ---------------------------------------- 344.1/344.1 MB 2.9 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220124-cp39-cp39-win_amd64.whl (343.9 MB)
     ---------------------------------------- 343.9/343.9 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.9.0.dev20220123-cp39-cp39-win_amd64.whl (343.9 MB)
     ---------------------------------------- 343.9/343.9 MB 3.4 MB/s eta 0:00:00
ERROR: Operation cancelled by user

**Comment by hardik-vala** [comment]
Hi, it seems that pip is backtracking through `tf_nightly` versions to try to resolve a conflicting dependency that's already installed. Have you tried installing the latest official release of [`tensorflow-federated`](https://github.com/tensorflow/federated/releases/tag/v0.20.0) in a [virtual env](https://docs.python.org/3/library/venv.html)?

**Comment by michaelreneer** [comment]
+1 to what @hardik-vala suggested, going to close this. Please reopen if you still have an issue.

**Comment by sonic-onkaringale** [comment]
I am also facing same issue with windows 11

**Comment by timmy1691** [comment]
I am installing this in a virtual environment, and it is going on in a loop as well. Does it have to be a fresh virtual environment? because i also installed packages like numpy and some other packages before installing tensorflow-federated.
