### ISSUE TITLE
Multiple output and multiple losses with tensorflow_federated

### ISSUE THREAD

**Issue by darpitdavetamu** [tensorflow/federated#2685]
I have the following model architecture:

    def create_keras_model():
        input = keras.Input(shape=(24, ), name="original_inpt")
        x = tf.keras.layers.Dense(512,activation='relu')(input)
        x = tf.keras.layers.Dense(256,activation='relu')(x)
        x = tf.keras.layers.Dense(64,activation='relu')(x)

        out1 = keras.layers.Dense(1,name = 'loss1')(x)
        out2 = keras.layers.Dense(1,name = 'loss2')(x)

        encoder = keras.Model(inputs = input, outputs = [out1, out2], name="encoder")
        return encoder

How do I pass the model_fn function:

    def model_fn():
        keras_model = create_keras_model()
        return tff.learning.from_keras_model(
          keras_model,
          input_spec=preprocessed_sample_dataset.element_spec,
           loss = [tf.keras.losses.MeanSquaredError(),tf.keras.losses.AbsoluteError()],,
          metrics = {
               "loss1": [tf.keras.metrics.MeanSquaredError()],
               "loss2": [tf.keras.metrics.MeanSquaredError()]
           })

It gives the following error:
InvalidArgumentError: Graph execution error:

Incompatible shapes: [500,1] vs. [2,500]
	 [[{{node SquaredDifference}}]]
	 [[StatefulPartitionedCall_1/StatefulPartitionedCall/ReduceDataset]] [Op:__inference_pruned_97396]

**Comment by wennanzhu** [comment]
Does `keras.Input(shape=(24, ), name="original_inpt")` match the shape of your input dataset? Also, metrics should be a list, not a dictionary.

**Comment by darpitdavetamu** [comment]
@wennanzhu Thank you for your response. Yes. Also, I was able to fix the error by changing code to this:

  def create_keras_model():

      input = keras.Input(shape=(24, 1), name="original_inpt")
      x = tf.keras.layers.Conv1D(filters=4,kernel_size=4,padding = 'same',input_shape=(24,1))(input)
      x = tf.keras.layers.MaxPool1D(pool_size=2)(x)
      x = tf.keras.layers.Conv1D(filters=8,kernel_size=4,padding = 'same')(x)
      x = tf.keras.layers.MaxPool1D(pool_size=2)(x)
      x = tf.keras.layers.LSTM(16, return_sequences=False)(x)
      
      
      x1_2 = tf.keras.layers.Dense(4,activation='relu')(x)
      x2_2 = tf.keras.layers.Dense(4,activation='relu')(x)

      out1 = keras.layers.Dense(1,name = 'hypo_loss')(x1_2)
      out2 = keras.layers.Dense(1,name = 'hyper_loss')(x2_2)

       encoder = keras.Model(inputs = input, outputs = [out1, out2], name="encoder")
       return encoder

  def model_fn():

      keras_model = create_keras_model()
      return tff.learning.from_keras_model(
        keras_model,
        input_spec=preprocessed_sample_dataset.element_spec,
        loss = [custom_loss_hyper(),custom_loss_hypo()],
        metrics = [tf.keras.metrics.MeanSquaredError(),tf.keras.metrics.MeanSquaredError()])


But my model is performing terribly compared to a central model. The training-loss in a central model reduces to about 600-700. In the FL setup, it reduces until 6000 but starts to increase after that.
I checked all my local models individually to see if there are outlier issues but they all seem to work fine. In addition, I got access to a manual code that averages weights across local models and seems to work as expected giving loss in the range near to the central model. Not sure, why it is not performing the same with 'tensorflow_federated'. Can you please help

**Comment by zcharles8** [comment]
@darpitdavetamu It's unfortunately difficult to debug this without the full code. That being said, loss diverging is often symptomatic of a learning rate (either client or server) being too large. I'd recommend trying a couple. Note that the learning rate needed may be slightly different than the "manual code" you refer to depending on how certain normalizations occur when taking averages.

**Comment by darpitdavetamu** [comment]
@zcharles8 Thank you for your reply. That's an interesting point. I did try to play with a few but not that rigorously. Give me a day or two to rigorously go through multiple combinations and check if there is change in model behavior. I will get back here for the same. 

In the manual code and tensorflow_federated:
Client optimizer: Adam and lr = 0.001
Server optimizer: SGD and lr = 1.0

However, I suspect that in the manual codes weights (\theta) are directly being averaged as opposed to differences between \theta_t and \theta_(t-1) as in 'tensorflow_federated'. Any suggestions on the changes I should focus on to match the performance?

Also, here is the link to the code I am using to implement federated learning: https://github.com/darpitdavetamu/Federated-Learning/blob/main/FL_MultiOutput(Manual_Code).ipynb
