### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by chandasri7** [tensorflow/federated#2696]
I want to implement the Federated Learning model using images. So, here clients clicks 100 images for training purpose. But data at client is unlabeled. So how the model can be trained and parameters for process of aggregation can take place?

**Comment by zcharles8** [comment]
It sounds like this is more of a researdch-oriented question around how to do unsupervised learning in federated settings. While it's a substantive research question, it's  a bit beyond TFF issues, so I'm closing this issue.
