### ISSUE TITLE
How to fix this issue? AttributeError：'EnhancedModel'object has no attribute 'report_local_unfinalized_metrics'

### ISSUE THREAD

**Issue by GShaol** [tensorflow/federated#2706]
# Hello, I am learning your code, but there will be such a bug when running your code([federated]federated/tensorflow_federated/examples/simple_fedavg), may I ask what is going on?

- <img width="815" alt="162010135-21680480-d38e-40b9-b9fc-0ac6c1860de3" src="https://user-images.githubusercontent.com/52623788/162102045-97571d42-d168-40f9-a58c-00fa9d1f3b1b.png">

- <img width="818" alt="162009169-5b14e97c-b95d-4184-86cf-ae965be74753" src="https://user-images.githubusercontent.com/52623788/162102053-81851819-9444-4238-9e3f-b9cd2c198443.png">

**Comment by GShaol** [comment]
I already know why. 
![捕获](https://user-images.githubusercontent.com/52623788/162115439-be156c75-269c-4458-be50-0073eeae1170.PNG)
Reference:https://www.tensorflow.org/federated/api_docs/python/tff/learning/Model#report_local_outputs

**Comment by aixiangwang** [comment]
Could you tell clearly? I see no problem with the picture

**Comment by aixiangwang** [comment]
Could you tell clearly? I see no problem with the picture.Thanks!

**Comment by GShaol** [comment]
Version problem, never mind.

**Comment by aixiangwang** [comment]
do you mean tensorflow_federated version?

**Comment by GShaol** [comment]
yes! In the new version, some functions have replaced.

> I already know why. ![捕获](https://user-images.githubusercontent.com/52623788/162115439-be156c75-269c-4458-be50-0073eeae1170.PNG) Reference:https://www.tensorflow.org/federated/api_docs/python/tff/learning/Model#report_local_outputs

**Comment by aixiangwang** [comment]
The picture tells us to use report_local_unfinalized_metrics and the code sample does exactly that.My tensorflow_federated version is 0.19.0 .Could you remember how you modify the code?

**Comment by GShaol** [comment]
pip install tensorflow_federated

**Comment by aixiangwang** [comment]
I have already install tensorflow_federated=0.19.0 ,you mean I should lower the version?

**Comment by aixiangwang** [comment]
I have solved the problem. Thank you for your answer
