### ISSUE TITLE
Tutorial "Federated Learning for Image Classification" does not work.

### ISSUE THREAD

**Issue by moodybomber** [tensorflow/federated#281]
The code here 

[federated/docs/tutorials/federated_learning_for_image_classification.ipynb](https://github.com/tensorflow/federated/blob/v0.2.0/docs/tutorials/federated_learning_for_image_classification.ipynb)

does not work, since this import does not work:
`from tensorflow.python.keras.optimizer_v2 import gradient_descent`

My conda env has the following packages:

![image](https://user-images.githubusercontent.com/49069128/55237792-3eaf5b00-5233-11e9-8019-cdecf62e6796.png)

**Comment by jkr26** [comment]
Hi,

Could you please advise how you are trying to execute this notebook? If it is through a local Jupyter backend, note that this is only a supported path when TFF is built from source with Bazel; the pip package may become out of sync with the master version of the notebooks.

**Comment by moodybomber** [comment]
I am trying to interpret the code by a python installation in a conda environment on windows.
I could get the tutorial working now by:
- creating a NEW conda environment &
- explicitly using pip in that environment for the installation of tensorflow_federated

**Comment by jkr26** [comment]
It is possible then that there was a version conflict. If possible, could you attach the output of `conda list` in your new env?

**Comment by moodybomber** [comment]
The output of "conda list" in the conda env where tff is working looks like:
![image](https://user-images.githubusercontent.com/49069128/55545023-a569c400-56cc-11e9-8d35-77808d82a972.png)

**Comment by jkr26** [comment]
I just tried to repro this issue locally, was unsuccessful. Closing, since this seems to be resolved.
