### ISSUE TITLE
Command issue

### ISSUE THREAD

**Issue by Ishita200008** [tensorflow/federated#2878]
tff.backends.native.set_local_python_execution_context(clients_per_thread=5)   [THIS IS THE COMMAND]
AttributeError: module 'tensorflow_federated.python.core.backends.native' has no attribute 'set_local_python_execution_context' [ERROR]

this above command isn't working for me, could you tell me how to rectify it

**Comment by michaelreneer** [comment]
+1 to @hardik-vala question, I think this must be due to an older version of `tensorflow-federated` package.

https://www.tensorflow.org/federated/api_docs/python/tff/backends/native/set_local_python_execution_context
