### ISSUE TITLE
Secure Aggregation implementation (?) not working.

### ISSUE THREAD

**Issue by pedropgusmao** [tensorflow/federated#2980]
**Describe the bug**
Hi there,

I'm trying to use the `tff.learning.secure_aggregator` described in [Tuning recommended aggregations for learning](https://colab.research.google.com/github/tensorflow/federated/blob/v0.27.0/docs/tutorials/tuning_recommended_aggregators.ipynb) together with [Federated Learning for Image Classification](https://colab.research.google.com/github/tensorflow/federated/blob/v0.27.0/docs/tutorials/federated_learning_for_image_classification.ipynb) using this

```
secagg_bound = tff.aggregators.PrivateQuantileEstimationProcess.no_noise(
            initial_estimate=50.0,
            target_quantile=0.95,
            learning_rate=1.0,
            multiplier=2.0,)

model_aggregator = tff.aggregators.MeanFactory(tff.aggregators.SecureSumFactory(secagg_bound))

iterative_process = tff.learning.algorithms.build_weighted_fed_avg(
        model_fn,
        client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.02),
        server_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=1.0),
        model_aggregator=model_aggregator,
    )
```

But I get the following error message: 

```
File "/home/pedro/.pyenv/versions/3.9.13/envs/tff_salvia/lib/python3.9/site-packages/tensorflow_federated/python/core/impl/executors/federated_resolving_strategy.py", line 527, in compute_federated_secure_sum_bitwidth
    raise NotImplementedError(
NotImplementedError: `tff.federated_secure_sum_bitwidth()` is not implemented in this executor. For a fake implementation of `federated_secure_sum_bitwidth` suitable for testing, consider using the test executor context by adding the following during initialization: `tff.backends.test.set_test_python_execution_context()`
terminate called without an active exception
```

Is it really not implemented or am I doing something wrong? Is there a working example of TFF with SA anywhere I could run?
Thanks

**Environment (please complete the following information):**
* OS Platform and Distribution: Ubuntu 20.04
* Python package versions : TF ='2.9.1',  TFF='0.27.0'
* Python version: 3.9.13
* Bazel version (if building from source):
* CUDA/cuDNN version: 11.6 
* What TensorFlow Federated execution stack are you using? 

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**
The training run as usual (like with a simple FedAvg)

**Additional context**

**Comment by jkr26** [comment]
TFF at the moment provides only a datacenter-based runtime, and it is not clear that SecAgg is useful in this instance--in particular, e.g., assuming that 'client' devices are running on physical machines owned and operated by the entity which runs the 'server', it's not clear why we would attempt to mask client updates.

This limitation is in no sense baked into the design or implementation of TFF; it is more accurate to state that TFF has not encountered demand for a 'real' SecAgg implementation via a compelling use-case. It is worth noting that there [have been implementations of SecAgg](https://medium.com/dropoutlabs/building-secure-aggregation-into-tensorflow-federated-4514fca40cc0) in a manner composable with TFF, though I'm not sure what the status of the project in that blog post is at the moment.

For the purposes of simply exploring with 'SecAgg-like' aggregation (IE, running logic which should be mathematically identical, but containing no cypto), TFF provides [test execution contexts](https://www.tensorflow.org/federated/api_docs/python/tff/backends/test) which [compile away](https://github.com/tensorflow/federated/blob/f17a45f39f338213feebbe5e0e5b787c692d1ca6/tensorflow_federated/python/core/backends/test/compiler.py#L20) the secure intrinsics, replacing them with mathematically equivalent 'in-the-clear' TensorFlow code. Installing such a test context should allow you to execute the SecAgg intrinsic, though again, without any 'real crypto'.

**Comment by pedropgusmao** [comment]
I see... Thanks for your answer.
