### ISSUE TITLE
Image Classification example without flattening of image array

### ISSUE THREAD

**Issue by anupamme** [tensorflow/federated#303]
Hello,

I tried the mnist image classificaiton tutorial. It works. However, when I try running it without flattening of image array I keep the input shape in model creation as:

model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(
          10, 
          activation=tf.nn.softmax, 
          kernel_initializer='zeros', 
          input_shape=(28,28)
        )])

instead of (784,)

But it does not work in this case. The error I get is:

tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [448,10] and labels shape [16]
	 [[{{node loss/dense_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

Here 16 is the batch size so 448 is 28 * 16. 

Is it not possible to run the example without flattening of images?

Motivation: I already have a model which was built without flattening of images and I am running into some issues while doing federated training on it so I wanted to try image classification tutorial without flattening.

**Comment by ZacharyGarrett** [comment]
Hi @anupamme, in general this should definitely be possible. could you provide a bit more information?

- Are you using the datasets provided by [`tff.simulation.datasets.emnist.load_data()`](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data)?

- Does *"without flattening"* mean skipping the reshape on **both** the `x` and `y` values in the `element_fn()` in [Preparing the input data](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification#preparing_the_input_data) part of the tutorial?

**Comment by anupamme** [comment]
> * Are you using the datasets provided by [`tff.simulation.datasets.emnist.load_data()`](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data)?

Yes.


> * Does _"without flattening"_ mean skipping the reshape on **both** the `x` and `y` values in the `element_fn()` in [Preparing the input data](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification#preparing_the_input_data) part of the tutorial?

So I modify that code to:

collections.OrderedDict([
            ('x', tf.reshape(element['pixels'], element['pixels'].shape)),
            ('y', tf.reshape(element['label'], element['label'].shape)),
        ])
from:
collections.OrderedDict([
            ('x', tf.reshape(element['pixels'], [-1])),
            ('y', tf.reshape(element['label'], [-1])),
        ])


Similarly I change the input_shape in create_compiled_keras_model to (28, 28,) from (784,)

**Comment by ZacharyGarrett** [comment]
I believe the dataset is returning the label as a scalar (e.g. `element['label'].shape == ()`), but I believe Keras is expecting it to be a Tensor with shape `(1,)`.

Perhaps try reverting back to the original code used in the tutorial for just the `y` / `label` feature? e.g.
```
   ('y', tf.reshape(element['label'], [1])),
```

**Comment by anupamme** [comment]
> ('y', tf.reshape(element['label'], [1])),

I think you meant ('y', tf.reshape(element['label'], [-1]))

I tried with this and got the same error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [448,10] and labels shape [16]
         [[{{node loss/dense_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

**Comment by ZacharyGarrett** [comment]
Ah, I think I misread the model initially. I don't think Keras dense layers work in the way this model is trying to use them.

The API docs for [tf.keras.layers.Dense](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) state:

> **Input shape**: nD tensor with shape: (batch_size, ..., input_dim). The most common situation would be a 2D input with shape (batch_size, input_dim).
> **Output shape**: nD tensor with shape: (batch_size, ..., units). For instance, for a 2D input with shape (batch_size, input_dim), the output would have shape (batch_size, units).

If I understand correctly, the model is transforming the input with shape `[16, 28, 28]` to `[16, 28, 10]`; then the first two dimensions are being flattened to compute the crossentropy on the final dimension (and finding the shapes aren't compatible).

Possibly you may want to look into using the convolutions instead, then flattening out before the dense layer for the final prediction layer.

So far it looks like this issue is inside Keras usage and doesn't use any TFF, so I'm closing the issue. I'd recommend asking further Keras API and modelling questions at https://stackoverflow.com/questions/tagged/keras.

**Comment by aynesss** [comment]
@ZacharyGarrett Please can you see this task `https://stackoverflow.com/questions/60060493/tff-invalid-argument-default-maxpoolingop-only-supports-nhwc-on-device-type-cp`
