### ISSUE TITLE
Getting a TypeError ('Adam' object is not callable) with build_weighted_fed_avg_with_optimizer_schedule

### ISSUE THREAD

**Issue by shifdz** [tensorflow/federated#3049]
Can someone please tell me how to set the `client_learning_rate_fn` and `client_optimizer_fn` in `build_weighted_fed_avg_with_optimizer_schedule`?

Part of my code is as follows:

```
iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=tf.keras.optimizers.Adam(learning_rate= client_lr, beta_1 = 0.9, beta_2 = 0.999,epsilon = 1e-07),
    server_optimizer_fn=optimizers.SGD)
```
This throw the error:

```

Traceback (most recent call last):
  File "/home/Desktop/FL/fed.py", line 352, in <module>
    iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
  File "/home/anaconda3/envs/fl/lib/python3.9/site-packages/tensorflow_federated/python/learning/algorithms/fed_avg_with_optimizer_schedule.py", line 276, in build_weighted_fed_avg_with_optimizer_schedule
    client_work = build_scheduled_client_work(model_fn, client_learning_rate_fn,
  File "/home/anaconda3/envs/fl/lib/python3.9/site-packages/tensorflow_federated/python/learning/algorithms/fed_avg_with_optimizer_schedule.py", line 98, in build_scheduled_client_work
    whimsy_optimizer = optimizer_fn(1.0)
TypeError: 'Adam' object is not callable
```

**Comment by shifdz** [comment]
Hi @zcharles8 ,

Bases on your reply, I tried:

```
def client_optimizer_fn(learning_rate):
    return tf.keras.optimizers.Adam(learning_rate=learning_rate, beta_1 = 0.9, beta_2 = 0.999,epsilon = 1e-07)

iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=client_optimizer_fn(client_lr),
    server_optimizer_fn=optimizers.SGD)
```
But I am still getting the same error.

**Comment by zcharles8** [comment]
@shifdz Can you post the stack trace? It looks like the same problem is in your `server_optimizer_fn` which should also be callable (but a no-arg one).

**Comment by zcharles8** [comment]
Ah, I see the issue. In your snippet above you did

```
def client_optimizer_fn(learning_rate):
    return tf.keras.optimizers.Adam(learning_rate=learning_rate, beta_1 = 0.9, beta_2 = 0.999,epsilon = 1e-07)

iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=client_optimizer_fn(client_lr),
    server_optimizer_fn=optimizers.SGD)
```
whereas you should not actually instantiate the `client_optimizer_fn`, ie. you should do something like
```
iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=client_optimizer_fn,
    ...)
```

**Comment by shifdz** [comment]
Did you mean something like this:
```
def client_optimizer(learning_rate):
    return tf.keras.optimizers.Adam(learning_rate=learning_rate, beta_1 = 0.9, beta_2 = 0.999,epsilon = 1e-07)

client_optimizer_fn = client_optimizer(client_lr)

iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=client_optimizer_fn,
    ...)
```

It still doesn't work. Tried this as well, 

```
client_optimizer_fn = tf.keras.optimizers.Adam(learning_rate=0.001)

iterative_process = build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001, 
    client_optimizer_fn=client_optimizer_fn,
    ...)
```
But still getting the same error.

**Comment by zcharles8** [comment]
No, I meant the snippet that I posted. The core of it is that the `client_optimizer_fn` must be of type `Callable[[float], tf.keras.optimizers.Optimizer]`. In both of the examples you post, the `client_optimizer_fn` you pass is actually an optimizer.

So for example, one could do:
```
def client_optimizer_fn(learning_rate):
    return tf.keras.optimizers.SGD(learning_rate)

tff.learning.algorithms.build_weighted_fed_avg_with_optimizer_schedule(
    model_fn,
    client_learning_rate_fn = lambda x: 0.001,
    client_optimizer_fn=client_optimizer_fn)
````

**Comment by zcharles8** [comment]
Maybe at an intuitive level: The fact that the argument is named `client_optimizer_fn` is important: It is a function that constructs optimizers, it is not an optimizer itself.

**Comment by shifdz** [comment]
Thank you so much @zcharles8 for the detailed explanation. It worked. So the `learning_rate` in `client_optimizer_fn` is assigned through `client_learning_rate_fn `, right?

**Comment by zcharles8** [comment]
Exactly! It's worth noting that this complexity is primarily due to having to construct keras optimizers within the graph context in which they're going to be used. There's a simpler pathway for this kind of thing through `tff.learning.optimizers`, but we don't have a dedicated API symbol for FedAvg with client learning rate scheduling just for those optimizers (yet?). We're looking into making this kind of thing easier, but we have no concrete plans yet.

**Comment by shifdz** [comment]
Hi @zcharles8 , however, when trained with the `build_weighted_fed_avg_with_optimizer_schedule` algorithm training accuracy stay constant at around 0.5. I tried with several different learning rates ranging from 0.01 to 0.001. This behavior is not observed with other algorithms like fedprox and fedavg. Could you please tell me what could be the issue?
