### ISSUE TITLE
Can't Convert Federated EMNIST Dataset to tf.keras datasets

### ISSUE THREAD

**Issue by dh928** [tensorflow/federated#3243]
**Describe the bug**
I am trying to do a centralize learning using all the EMNIST from TFF.simulation.dataset to train on a non-federated Keras learning model. I managed to get combine all the data using:

"source, _ = tff.simulation.datasets.emnist.load_data()
(x_train, y_train) = source.create_tf_dataset_from_all_clients()"

But I am not able to split "all" into normal tensorflow x and y ('pixels' and 'labels'). I am not able to find any tutorials on this.

**Environment (please complete the following information):**
* OS Platform and Distribution: Mac OS
* Python version: 3.9

**Expected behavior**
I was expecting to be able to split the dataset, but I kept on getting the following error: 

          [5]source, _ = tff.simulation.datasets.emnist.load_data()
----> [6] (x_train, y_train) = source.create_tf_dataset_from_all_clients()

ValueError: too many values to unpack (expected 2)

**Comment by zcharles8** [comment]
@dh928 The output of `tff.simulation.datasets.ClientData.create_tf_dataset_from_all_clients()` is a `tf.data.Dataset`. These cannot be unpacked in the way that you are trying. If you would like to create two separate datasets of pixels and labels, you could do something like
```
pixel_dataset = source.map(lambda x: x['pixels'])
label_dataset = source.map(lambda x: x['label'])
```
See https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data for details on the structure of the EMNIST datasets (ie. where the keys I used above come from).

**Comment by dh928** [comment]
> @dh928 The output of `tff.simulation.datasets.ClientData.create_tf_dataset_from_all_clients()` is a `tf.data.Dataset`. These cannot be unpacked in the way that you are trying. If you would like to create two separate datasets of pixels and labels, you could do something like
> 
> ```
> pixel_dataset = source.map(lambda x: x['pixels'])
> label_dataset = source.map(lambda x: x['label'])
> ```
> 
> See https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data for details on the structure of the EMNIST datasets (ie. where the keys I used above come from).

thank you! really appreciate your help!
