### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by garytann** [tensorflow/federated#3479]
**Describe the bug**
I am currently testing the federated learning image classifier based on : https://colab.research.google.com/github/tensorflow/federated/blob/v0.44.0/docs/tutorials/federated_learning_for_image_classification.ipynb#scrollTo=ZrGitA_KnRO0 

**Environment (please complete the following information):**
* Linux Ubuntu 22.04
* Python package versions (e.g., TensorFlow Federated, TensorFlow): tff =  0.44.0 , tf = 2.11.0
* Python version: 3.9
* Bazel version (if building from source):
* CUDA/cuDNN version: cuda 11.8 / 8.7.0
* What TensorFlow Federated execution stack are you using? NIL 

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**
I am currently trying to run the tutorial within a linux virtual machine that I have spinned up, I have set the environment to ensure I have got the pre-requisite. I am running in off a python script instead of a notebook. Everything is smooth until I tried to load the EMINST dataset from tff.simulation.datasets.emnist.load_data(only_digits=True)

however, I am getting this error:

```
  File "/datadrive/miniconda/envs/tf/lib/python3.9/site-packages/tensorflow_federated/python/simulation/datasets/sql_client_data.py", line 123, in __init__
    _check_database_format(database_filepath)
  File "/datadrive/miniconda/envs/tf/lib/python3.9/site-packages/tensorflow_federated/python/simulation/datasets/sql_client_data.py", line 48, in _check_database_format
    result = connection.execute("SELECT name FROM sqlite_master;")
sqlite3.DatabaseError: database disk image is malformed
```

I have tried:
1) ensuring there is no issue with my sqlite3 db, by performing sqlite3 command such as .dump and .recover
2) reinstalling miniconda3 and created multiple virtual environments 
3) ensuring all required libraries are properly installed

**Additional context**
I am new to using tensorflow as a machine learning framework

**Comment by zcharles8** [comment]
Thanks for the detailed information! Taking a look now to see if I can repro this.

**Comment by zcharles8** [comment]
@garytann I tried reproing your issue but had no issues. Can you provide 1) the specific code used and 2) the python package versions installed (eg. via running `pip freeze`).

**Comment by garytann** [comment]
hi @zcharles8 thanks for the reply!

Here's more detail as per request:

1) Code
```
#!/usr/bin/env python3

import nest_asyncio
nest_asyncio.apply()

import collections

import numpy as np
import tensorflow as tf
import tensorflow_federated as tff
import pdb

def main():
    np.random.seed(0)
    cur = tff.federated_computation(lambda: 'starting....')()
    print(cur)
    pdb.set_trace()    
    emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data(
    only_digits=True)

    #print(len(emnist_train.client_ids))
    
main()
```
2) Package
```
absl-py==1.0.0
astunparse==1.6.3
attrs==21.4.0
cachetools==3.1.1
charset-normalizer==2.1.1
cloudpickle==2.2.0
contourpy==1.0.6
cycler==0.11.0
decorator==5.1.1
dill==0.3.6
dm-tree==0.1.7
dp-accounting==0.3.0
etils==0.9.0
farmhashpy==0.4.0
flatbuffers==2.0.7
fonttools==4.38.0
gast==0.4.0
google-auth==2.15.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.57.0
grpcio==1.51.1
h5py==3.7.0
idna==3.4
importlab==0.8
importlib-metadata==5.2.0
importlib-resources==5.10.1
jax==0.3.14
jaxlib==0.3.14
Jinja2==3.1.2
joblib==1.2.0
keras==2.11.0
kiwisolver==1.4.4
libclang==14.0.6
libcst==0.4.9
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
mpmath==1.2.1
mypy-extensions==0.4.3
nest-asyncio==1.5.6
networkx==2.8.3
ninja==1.11.1
numpy==1.22.4
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==22.0
pandas==1.5.2
Pillow==9.3.0
portpicker==1.5.2
promise==2.3
protobuf==3.19.6
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydot==1.4.2
pyparsing==3.0.9
python-dateutil==2.8.2
pytype==2022.12.15
pytz==2022.7
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.2.0
scipy==1.7.3
semantic-version==2.10.0
six==1.16.0
tabulate==0.9.0
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-compression==2.11.0
tensorflow-datasets==4.7.0
tensorflow-estimator==2.11.0
tensorflow-federated==0.44.0
tensorflow-gpu==2.11.0
tensorflow-io-gcs-filesystem==0.29.0
tensorflow-metadata==1.12.0
tensorflow-model-optimization==0.7.3
tensorflow-privacy==0.8.6
tensorflow-probability==0.15.0
termcolor==2.1.1
threadpoolctl==3.1.0
toml==0.10.2
tqdm==4.64.1
typing-inspect==0.8.0
typing_extensions==4.4.0
urllib3==1.26.13
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.11.0
```

By specifying a new cache_dir, do you mean to do this when downloading the requirements? or running the script and specifying a specific caching dir?

**Comment by garytann** [comment]
hi @zcharles8 I think I have found a fix for this issue, for the env that I am using which is a virtual machine, because I have partition much of the physical memory into a /datadrive mount. I think when I try to do a 
```
tff.simulation.datasets.emnist.load_data()
```
I assumed it is registering a cache within my root which has insufficient memory since my sqlite3 directory belongs to the root as well. Therefore, after studying the documentation provided by tensorflow federated, the function allows users to specify a cache_dir 

```
TMPDIR = "/$DIR"
emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data(
    only_digits=True, cache_dir=TMPDIR
)
```
This will cache the dataset within the **TMPDIR** I specified and this allows it to be loaded.

I no longer faced an issue, however, please assist with sharing this solution that I provided for users who might have a similar issue as me in the future. 

Cheers

**Comment by zcharles8** [comment]
Glad things are resolved. It sounds like the documentation did its job here, so I am marking this as resolved.
