### ISSUE TITLE
Callable[[arg, ...], result]: each arg must be a type. Got Ellipsis.

### ISSUE THREAD

**Issue by mahimairaja** [tensorflow/federated#3519]
**Tensorflow federated cannot be imported**

I simply tried to run the TensorFlow federated [notebook](https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) for Image Classification using the MNIST dataset.

I ran the notebook on Google Colab only...
But I installed the dependency successfully but I was not able to import the Tensorflow Federated.
The above error is thrown.
A requirement.txt might help me to resolve the issue.

Kindly if anyone knows to solve it. Do comment below.

**Comment by zcharles8** [comment]
This is due to the fact that tensorflow-federated is not compatible with versions of Python earlier than 3.9 and the default colab runtime uses Python 3.7.

Until colab updates their default runtime, I'd suggest running the code locally or else in an environment with Python 3.9 or 3.10.
