### ISSUE TITLE
Calling any federated computation blocks indefinitely in waiter.acquire()

### ISSUE THREAD

**Issue by lndulgence** [tensorflow/federated#3624]
**Describe the bug**
Running any python program containing a call to tff.federated_computation(foo) results in no output indefinitely, when SIGINT is sent, the process always seems to be stuck on waiter.acquire().

For instance, running `python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"` results in:

`2023-02-09 12:02:48.469300: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-09 12:02:48.993706: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-09 12:02:48.993744: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-09 12:02:48.993749: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary)
/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary)
/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary)
/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/backends/native/../../../../data/worker_binary)
`
followed by no output, when sent a SIGINT:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/impl/computation/computation_impl.py", line 144, in __call__
    return self._context_stack.current.invoke(self, arg)
  File "/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/core/impl/execution_contexts/sync_execution_context.py", line 64, in invoke
    return self._async_runner.run_coro_and_return_result(
  File "/home/jmora/venv/lib/python3.9/site-packages/tensorflow_federated/python/common_libs/async_utils.py", line 224, in run_coro_and_return_result
    return future.result()
  File "/home/jmora/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 441, in result
    self._condition.wait(timeout)
  File "/home/jmora/anaconda3/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

`

**Environment (please complete the following information):**
* Ubuntu 20.04
* Package versions:
`tensorflow==2.11.0
tensorflow-compression==2.11.0
tensorflow-datasets==4.8.2
tensorflow-estimator==2.11.0
tensorflow-federated==0.48.0
tensorflow-io-gcs-filesystem==0.30.0
tensorflow-metadata==1.12.0
tensorflow-model-optimization==0.7.3
tensorflow-privacy==0.8.6
tensorflow-probability==0.15.0
`
* Python version: 3.9.16
* CUDA version:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243`

**Expected behavior**
The computation ends and  an output is received, for instance  `python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"`  should print out "Hello World".

**Additional context**
This result is unchanging no matter whether the script is run directly in python or on an iPython environment.

**Comment by stefanfu00** [comment]
I think I have the same problem:

**Describe the bug**: Exactly the same as above, with "version 'GLIBC_2.XX' not found" followed by being stuck in waiter.acquire(). 

**Environment**: Ubuntu 18.04, Python 3.10.9, CUDA toolkit 11.2.2 (CUDNN 8.1.0.77), otherwise identical to above. Also glibc 2.27. 

- I don't get the problem in TFF 0.40.0 (which also downgrades other packages including tensorflow). Any version 0.41.0 and above gets stuck. 
- I did not get the same problem when running on a different computer with Ubuntu 22.04, glibc 2.35 (otherwise identical to the 18.04 environment).

**Comment by lndulgence** [comment]
Can you describe the environment where you're running 0.40.0? I think it would suffice to just stick to that version with CUDA 12. Does the second environment output the GLIB warning all the same?

**Comment by stefanfu00** [comment]
**0.40.0 environment**: Same Ubuntu 18.04, glibc 2.27, Python 3.10.9, CUDA toolkit 11.2.2, CUDNN 8.1.0.77. tensorflow-federated 0.40.0, tensorflow 2.10.1, tensorflow-addons 0.19.0, tensorflow-compression 2.10, tensorflow-estimation 2.10, otherwise same as yours. 

Neither of the working environments (Ubuntu 18.04 + TFF 0.40.0 and Ubuntu 22.04 + TFF 0.48.0) give the GLIBC warning for the hello world print.

**Comment by lndulgence** [comment]
I will try that in the meanwhile, hopefully we get an answer soon. Thanks a lot! Will update if this works/ if I figure out the error.

**Comment by jkr26** [comment]
I believe this is a consequence of the fact that our default C++-backed runtime is not (yet) built in as-cross-platform a manner as possible. There are a few issues that we believe are related (#3608, #3593, #3591), and internally we (I believe primarily @michaelreneer) are working on a fix.

Meanwhile, this problem should also be avoidable by installing the [Python execution context](https://www.tensorflow.org/federated/api_docs/python/tff/backends/native/set_local_python_execution_context):
```
tff.backends.native.set_local_python_execution_context()
```

**Comment by stefanfu00** [comment]
> Meanwhile, this problem should also be avoidable by installing the [Python execution context](https://www.tensorflow.org/federated/api_docs/python/tff/backends/native/set_local_python_execution_context):
> 
> ```
> tff.backends.native.set_local_python_execution_context()
> ```
This worked for me. Thanks!

**Comment by lndulgence** [comment]
This solves the problem. Thank you for your help! Closing the issue.
