### ISSUE TITLE
tff.federated_computation(lambda: 'Hello World!') stuck/hanging at waiter.acquire().

### ISSUE THREAD

**Issue by drakstik** [tensorflow/federated#3700]
I'm running the image classification tff (tutorial )[https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification]  and having issues performing the first tff.federated_computation(lambda: "Hello World!"). It hangs when I run it until I keyboard interrupt it. I've tried it on both Python 3.9.16 and 3.10.6 and I get the same issue on two separate Linux Ubuntu machines (one was a freshly spun up VM with fresh tensorflow-federated and nest-asyncio installs using pip --upgrade as suggested in the tutorial. My version of pip is 22.0.2. I ran the code in a local Jupyter Notebook). It did work with 3.6 but I think 3.9+ is the best for TFF to work properly. I looked around the internet for this issue, but could not figure it out. Please help!

Here is the traceback I get:
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[4], line 14
     10 print("here")
     11 # A Federated Computation (or FC) is a computation where the data stays on clients' machines [2]
     12 # This function simulates a federated computation given any python computation [1]
     13 #tff.federated_computation(lambda: 1+1)()
---> 14 print(tff.federated_computation(lambda: 'Hello, World!')())
     17 # Federated Computations are made of three steps:
     18 #       1. Federated Broadcast: Publicly broadcast Global Model to clients.
     19 #       2. Federated Map: Privately train local parameters using private data and Global Model on the client-side.
     20 #       3. Federated Mean: Aggregate clients' locally trained parameters.

File ~/.local/lib/python3.9/site-packages/tensorflow_federated/python/core/impl/computation/computation_impl.py:144, in ConcreteComputation.__call__(self, *args, **kwargs)
    142 def __call__(self, *args, **kwargs):
    143   arg = function_utils.pack_args(self._type_signature.parameter, args, kwargs)
--> 144   return self._context_stack.current.invoke(self, arg)

File ~/.local/lib/python3.9/site-packages/tensorflow_federated/python/core/impl/execution_contexts/sync_execution_context.py:64, in SyncExecutionContext.invoke(self, comp, arg)
     63 def invoke(self, comp, arg):
---> 64   return self._async_runner.run_coro_and_return_result(
     65       self._async_context.invoke(comp, arg)
     66   )

File ~/.local/lib/python3.9/site-packages/tensorflow_federated/python/common_libs/async_utils.py:224, in AsyncThreadRunner.run_coro_and_return_result(self, coro)
    222 """Runs coroutine in the managed event loop, returning the result."""
    223 future = asyncio.run_coroutine_threadsafe(coro, self._event_loop)
--> 224 return future.result()

File /usr/lib/python3.9/concurrent/futures/_base.py:441, in Future.result(self, timeout)
    438 elif self._state == FINISHED:
    439     return self.__get_result()
--> 441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:
    444     raise CancelledError()

File /usr/lib/python3.9/threading.py:312, in Condition.wait(self, timeout)
    310 try:    # restore state no matter what (e.g., KeyboardInterrupt)
    311     if timeout is None:
--> 312         waiter.acquire()
    313         gotit = True
    314     else:

KeyboardInterrupt: 

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

**Comment by drakstik** [comment]
Solved the issue by running tff.backends.native.set_local_python_execution_context() before doing the federated_computation. It was resolved in a previous issue, sorry I missed it.

**Comment by vivere-dally** [comment]
> Solved the issue by running tff.backends.native.set_local_python_execution_context() before doing the federated_computation. It was resolved in a previous issue, sorry I missed it.

Can you link the other issue? For me setting `tff.backends.native.set_local_python_execution_context()` still hangs.

**Comment by drakstik** [comment]
> Can you link the other issue? For me setting `tff.backends.native.set_local_python_execution_context()` still hangs.

Here: https://github.com/tensorflow/federated/issues/3624

**Comment by Georgeshayek** [comment]
hi guys ! basically I got the same problem but I am working on the code in colab and running in cpu runtime any idea on how to solve it?

**Comment by Georgeshayek** [comment]
> hi guys ! basically I got the same problem but I am working on the code in colab and running in cpu runtime any idea on how to solve it?

and when I use the tff.backends.native.set_local_python_execution_context() I am getting this error on colab

AttributeError: module 'tensorflow_federated.python.core.backends.native' has no attribute 'set_local_python_execution_context'
