### ISSUE TITLE
Why TFF runs slowly even with only one client?

### ISSUE THREAD

**Issue by zhangxinqian** [tensorflow/federated#373]
I found TFF is extremely slow even if I only simulated with one client. In addition, when I insert tf.print() in function "def __call__(self, dataset, initial_weights)" in the class ClientFedAvg in federated_averaging.py, running the script in federated_learning_for_image_classification.ipynb will print several times in each round with only one client. But this function should be executed once in each round with each client. I don't know whether it is a bug

**Comment by krzys-ostrowski** [comment]
Hi. The runtime we initially included is minimal - it was originally intended primarily for testing and small-scale experiments. Support for higher-performance simulations is coming. This is not to say we cannot make the reference runtime faster if we can. We have not invested much in trying to memoize or cache things to avoid repeated calls like those you described. Perhaps you can help by posting here stack traces from these repeated calls, so that we can see exactly when they happen and diagnose this (I do not remember off the top of my head). Thanks!

**Comment by zhangxinqian** [comment]
Thanks for the reply!
For federated_learning_for_image_classification tutorial, set NUM_CLIENTS = 1 and insert tf.print("call ClientFedAvg") at the beginning of function "def call(self, dataset, initial_weights)" in the class ClientFedAvg in federated_averaging.py. Then I run the tutorial and get the following results:
call ClientFedAvg
call ClientFedAvg
call ClientFedAvg
round  0, loss=<loss=3.1112683>
call ClientFedAvg
call ClientFedAvg
call ClientFedAvg
round  1, loss=<loss=2.9389212>
call ClientFedAvg
call ClientFedAvg
call ClientFedAvg
round  2, loss=<loss=2.666009>
call ClientFedAvg
call ClientFedAvg
call ClientFedAvg
round  3, loss=<loss=2.1996822>
I think with NUM_CLIENTS = 1, it should print "call ClientFedAvg" only once. But I got three each round. It means that it trains repeatly from same initial weights in vain for each client in each round. For another case I wrote, with NUM_CLIENTS = 1 it printed more than 10 times. Thanks!

**Comment by llhuii** [comment]
After dividing into this problem, `client_outputs.__getattr__` was called by three times in `run_one_round_tff` in optimizer_utils.py: `client_outputs.weights_delta_weight`, `client_outputs.weights_delta`, and `client_outputs.model_output`, so `ClientFedAvg` was evaluated by three times.

**Comment by jkr26** [comment]
This is to be expected in the interpreted runtime, as it is naively interpreting the syntax trees TFF generates.

Have you tried using `tff.framework.set_default_executor(tff.framework.create_local_executor())`?

**Comment by ines321** [comment]
please what is version of cuda that requires TFF?
I would like to execute this tutorial but I find incompatibility in cuda version

**Comment by jkr26** [comment]
I think we can consider this issue closable.
