### ISSUE TITLE
UnsupportedOperation: fileno when initialize training process

### ISSUE THREAD

**Issue by mrcaelumn** [tensorflow/federated#3747]
**Describe the bug**
I got error UnsupportedOperation: fileno when I was trying Matrix Factorization tutorial

`state = training_process.initialize()`
`print(training_process.model) `
`print('Item variables shape:', training_process.model.trainable[0].shape)`

**Environment:**
IDE: Google Collab
Python **_3.9_**

**Comment by zcharles8** [comment]
Thanks @mrcaelumn. This issue manifests when using the current TFF version (0.51.0) with colab. We believe da6f2a88deae0df8b82a71157f5098a6a6f27c4d should fix the issue. We're hoping to do a release soon, which will pick up this change and should hopefully enable TFF + colab again.

**Comment by ZacharyGarrett** [comment]
The `0.52.0` release (https://github.com/tensorflow/federated/releases/tag/v0.52.0) was just pushed to PyPi (https://pypi.org/project/tensorflow-federated/0.52.0/).

It appears to run the following colab tutorial alright:
https://colab.research.google.com/github/tensorflow/federated/blob/v0.52.0/docs/tutorials/federated_learning_for_image_classification.ipynb

Could you try again?

**Comment by ZacharyGarrett** [comment]
Marking as closed, this was fixed along with #3742 . Feel free to re-open if the same error is still occurring.
