### ISSUE TITLE
Not an issue but I'm wondering how to use Federated learning frameworks with a virtual try on deep learning model 

### ISSUE THREAD

**Issue by Noureldin2303** [tensorflow/federated#3790]
How can I use federated learning frameworks with a virtual try on deep learning model ?

As the size of the model is too large to be trained on users' machines offline and it needs high hardware specifications

**Comment by zcharles8** [comment]
Seconding @huili0140, this seems like an open-ended question that'd be a better fit for a forum like stack-exchange. Marking as resolved.
