### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'from_keras_model'

### ISSUE THREAD

**Issue by zihad18** [tensorflow/federated#3804]
Describe the bug
Trying to run TFF with Federated Learning for Image Classification

from example of   https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification it throws an attribute error.

Environment (please complete the following information):

Python= 3.10.4
Version: 2.12.0
TFF:  0.53.0

My machine is ubuntu

Suggest me how can I resolve this problem

**Comment by zcharles8** [comment]
We deprecated `tff.learning.from_keras_model` in v0.53.0. You can use `tff.learning.models.from_keras_model` to get the same functionality.

The tutorial should've been updated, but seems to have the old symbol. I'll change that ASAP. Thanks for the report.
