### ISSUE TITLE
Support for multiple losses with tf.keras

### ISSUE THREAD

**Issue by aqibsaeed** [tensorflow/federated#386]
If I understand correctly, tf-federated only supports single loss function. Is there any timeline on when the support for multiple losses will be added?

```
File "/home/.local/lib/python3.5/site-packages/tensorflow_federated/python/learning/model_utils.py", line 456, in __init__
    raise NotImplementedError('only a single loss functions is supported')
```

**Comment by ZacharyGarrett** [comment]
@aqibsaeed I'll look into how this fits with efforts and follow-up.

**Comment by Squadrick** [comment]
@ZacharyGarrett I'd love to take a crack at this.

**Comment by ZacharyGarrett** [comment]
@Squadrick thank you, we'd really appreciate any contribution!

A few notes on things we anticipated may need to be changed (there could definitely be more...):

- [`BatchOutput.loss`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/model.py#L27 ) needs to be updated (at least the pydoc) to explain it is the "total loss" 
- [`tff.learning.from_keras_model`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/keras_utils.py#L87) needs to be updated to allow for a single loss, a `collections.Sequence` of losses, or a `collections.Mapping` of output name → loss function, for the `loss` argument.
- [`_TrainableKerasModel.__init__`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/keras_utils.py#L374) needs to be updated to pass all `inner_model.loss_functions` to the base class
- [`_KerasModel.__init__`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/keras_utils.py#L230) needs a bunch of changes
  - `self._loss_fn` should keep a structure of all loss functions
  - `self._loss_metric` should be updated to match
- [`_KerasModel._forward_pass`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/keras_utils.py#L323) needs to be updated to call each loss function on the associated output, and all losses combined to `batch_loss`

We may want to plumb through a `loss_weights` value from the `from_*_model` methods, similar to Keras' similarly named argument in [`tf.keras.Model.compile`](https://www.tensorflow.org/api_docs/python/tf/keras/models/Model#compile), but perhaps just taking a uniform weighting initially is a good start.

If you're going to be taking a look, I'd recommend a test-driven approach by first adding an example model with two outputs and different losses to [learning/model_examples.py](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/model_examples.py#L256), similar to `build_multiple_inputs_keras_model()`, then adding a unittest to [learning/keras_utils_test.py](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/keras_utils_test.py#L278) similar to `test_keras_model_multiple_inputs`.

**Comment by Squadrick** [comment]
@ZacharyGarrett Thanks for the help, I'll get started.

**Comment by aqibsaeed** [comment]
Now I am getting this error:
```
 lambda component_spec: component_spec._to_legacy_output_types(),  # pylint: disable=protected-access
AttributeError: 'list' object has no attribute '_to_legacy_output_types'
```
What might be an issue now?

**Comment by ZacharyGarrett** [comment]
Without more information its hard to tell where this error is coming from. Could you open a new issue with:

- Environment (TFF version, TF version, OS, etc)
- A minimal example code that generates the AttributeError
