### ISSUE TITLE
AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'build_federated_averaging_process'

### ISSUE THREAD

**Issue by Yeojoon** [tensorflow/federated#3882]
**Describe the bug**
I got a bug -> AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'build_federated_averaging_process'. I tried to run codes that use 'build_federated_averaging_process'. But, I realized that there is no 'build_federated_averaging_process' anymore in the module 'tensorflow_federated.python.learning'. Could you let me know which function I can use instead of 'build_federated_averaging_process'? Thank you for your time in advance!

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.6 LTS
* Python package versions (e.g., TensorFlow Federated, TensorFlow): TensorFlow Federated -> 0.56.0
* Python version: Python 3.9.7
* Bazel version (if building from source):
* CUDA/cuDNN version: 12.0
* What TensorFlow Federated execution stack are you using?

**Comment by zcharles8** [comment]
That symbol was previously removed in favor of `tff.learning.algorithms.build_weighted_fed_avg`. You should be able to use that to build FedAvg.

**Comment by Yeojoon** [comment]
Oh, that makes sense. Thank you for your comments!
