### ISSUE TITLE
How adpot other datasets

### ISSUE THREAD

**Issue by Ouimoi** [tensorflow/federated#399]
Hi there, does the current version support other dataset customized by ourselves. The data shown in the tutorials are in HDF5 format and I have a hard time adapting mine to the pipeline.

**Comment by ZacharyGarrett** [comment]
This is probably a good question for StackOverflow, where there is a `tensorflow-federated` tag. A similar question has already been asked in [Create a custom federated data set in TensorFlow Federated](https://stackoverflow.com/questions/55434004/create-a-custom-federated-data-set-in-tensorflow-federated), which might give some of the information you are looking for. 

The `tff.simulation.ClientData` interface supports any file format. The `0.4.0` release contains two implementations: [tff.simulation.HDF5ClientData](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/HDF5ClientData) and [tff.simulation.FilePerUserClientData](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/FilePerUserClientData).

If you have further questions about how to use those APIs, the TFF team would encourage using StackOverflow so the community can benefit from the recorded answers in the future.
