### ISSUE TITLE
Documentation Issue - from_keras_model function

### ISSUE THREAD

**Issue by Barathwaja** [tensorflow/federated#4153]
**Describe the bug**
The latest API documentation states that `from_keras_model` is accessible from `tff.learning.models` but some of the pages still uses old way approach via `tff.learning` (i.e `tff.learning.from_keras_model`) instead of `tff.learning.models.from_keras_model`.

API Documentation - https://www.tensorflow.org/federated/api_docs/python/tff/learning/models/from_keras_model
Bug Pages - https://www.tensorflow.org/federated/tutorials/loading_remote_data

**Expected behavior**
This is where it should be imported as `tff.learning.models.from_keras_model`

**Screenshot**
Attached screenshot below:
<img width="982" alt="image" src="https://github.com/tensorflow/federated/assets/5066436/0d79a34e-e624-447c-bcd2-a2740f00aa3d">

**Comment by zcharles8** [comment]
Thanks @Barathwaja! That tutorial looks stale. I'll try to have it updated today.

**Comment by Barathwaja** [comment]
@zcharles8 I can update and make a PR if that's is the only change needed.

**Comment by zcharles8** [comment]
As it turns out, this tutorial was already deleted, as it is stale. However, we are blocked on releasing a new TFF version until we figure out some compatibility issues, and the TF docs won't update until that happens. Marking this as resolved as a result.
