### ISSUE TITLE
Documentation Issue - GCP Setup

### ISSUE THREAD

**Issue by Barathwaja** [tensorflow/federated#4154]
**Describe the bug**
The GCP Setup Page under [Tensorflow Guide](https://www.tensorflow.org/federated/gcp_setup) is not available. It is showing as 404.

**Comment by zcharles8** [comment]
Thanks @Barathwaja. This should be resolved by edab177d44c526051f4d9975991cb4d5b33c4a80.

It might not propagate to the TF Docs until the next release (which hopefully will be soon).
