### ISSUE TITLE
Multiple inputs with keras model?

### ISSUE THREAD

**Issue by pgoldberg** [tensorflow/federated#416]
I'm trying to apply federated learning to an existing keras model that takes two inputs. When I call `tff.learning.from_compiled_keras_model` and include a dummy batch, I get this error: `ValueError: Layer model_1 expects 2 inputs, but it received 1 input tensors. Inputs received: [<tf.Tensor 'packed:0' shape=(2, 20) dtype=int64>]`.

The model accepts two numpy arrays as inputs, so I defined my dummy_batch as:
```
x = tf.constant(np.random.randint(1,100, size=[20]))
collections.OrderedDict([('x', [x, x]), ('y', x)])
```

I dug around a little bit and saw that eventually, `tf.convert_to_tensor_or_sparse_tensor` gets called on the input list (in the `__init__` for `_KerasModel`), and that returns a single tensor of shape (2,20), instead of two separate arrays or tensors. Is there some other way I can represent the list of inputs to avoid this issue?

**Comment by jkr26** [comment]
@pgoldberg,

This is definitely something we can take a look at. Attaching a colab with a repro and some quick investigation, and assigning myself.

Colab: 

https://colab.research.google.com/drive/1E7VS3AXICnwmcHXwYum5avh_8K_oLuFy

**Comment by jkr26** [comment]
Peter, see [this commit](https://github.com/tensorflow/federated/pull/431/commits/1a87f07eb65962ce300ddfc0f5b96e54468cca24); it should contain the bugfix that you need.

**Comment by pgoldberg** [comment]
Thank you!
