### ISSUE TITLE
What is the refactored name of `federated_output_computation`?

### ISSUE THREAD

**Issue by mahimairaja** [tensorflow/federated#4161]
I could see that `federated_output_computation` is depreciated. So what could I use instead of this?

**Comment by zcharles8** [comment]
@mahimairaja Can you clarify what part of the API you're referring to?

**Comment by mahimairaja** [comment]
I am mentioning the function that has depreciated in the previous version - https://github.com/tensorflow/federated/blob/846d00939ff87d675942a52182b65babdecdf4aa/RELEASE.md?plain=1#L1036

**Comment by mahimairaja** [comment]
@zcharles8  Can you help me with this?

**Comment by zcharles8** [comment]
As the release notes say, you should use `report_local_unfinalized_metrics` and `metric_finalizers` now instead if you're directly subclassing [`tff.learning.models.VariableModel`](https://www.tensorflow.org/federated/api_docs/python/tff/learning/models/VariableModel).

However, if you use [`tff.learning.models.from_keras_model`](https://www.tensorflow.org/federated/api_docs/python/tff/learning/models/from_keras_model) then this is taken care of for you.

**Comment by zcharles8** [comment]
@mahimairaja I believes this answers the question in the original github issue, so I'm marking this as resolved.
