### ISSUE TITLE
Implemented simulation tff code to be distribute from server to clients.

### ISSUE THREAD

**Issue by karantai** [tensorflow/federated#4168]
Hello,

I have implement the simulation code for image classification and text generation using tensorflow_federated and it works fine. Now, I have read the two federated core tutorials so I can learn some extra stuff, but I believe there is no tutorial on how the communication between the server and the clients can be done. Using which protocol, python libraries etc. Any help with that?

**Comment by boxer-code** [comment]
Did you solve this and if, how? I'm a little bit confused about the communication too.

**Comment by karantai** [comment]
As far as I know, `tensorflow_federated` can do only simulations of Federated Learning, so you can only run FL setup in one computer that serves both as server and clients.
I have used [flwr](https://flower.dev/) library in Python and I achieved the federated learning communication between server and clients that reside not in LAN but in WAN.
