### ISSUE TITLE
[Question] Will this support the tensorflow 2.0 Api

### ISSUE THREAD

**Issue by japrogramer** [tensorflow/federated#452]
When the API for 2.0 is finalized .. will this repo also support 2.0?

**Comment by ZacharyGarrett** [comment]
Yes, TF2.0 support is planned for TFF; though the support may not be available immediately when the TF2.0 API is finalized.

TFF already works with eager mode and function semantics. Examples: most of the unittests in the [tensorflow_federated/python/learning](https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/learning) directory are all using eager mode and `tf.function`. Additionally, the tutorial [Federated Learning for Text Generation](https://www.tensorflow.org/federated/tutorials/federated_learning_for_text_generation) is all using TF2.0 behavior (`tf.compat.v1.enable_v2_behavior()`)
