### ISSUE TITLE
Stuck at learning_process.initialize() and tff.federated_computation(lambda: 'Hello, World!')()

### ISSUE THREAD

**Issue by Temitopeadekunle0906** [tensorflow/federated#4586]
when i use tensoflow federated in google colab. When I try to run tff.federated_computation(lambda: 'Hello, World!')(), this command is also hanging. The same happens with .initialize() function when i try to start training my model using tff.learning.algorithms.build_weighted_fed_avg. Has anyone faced this issue recently?

**Comment by zcharles8** [comment]
Marking this as a duplicate of #4585.
