### ISSUE TITLE
how to print local outputs?

### ISSUE THREAD

**Issue by alicelh** [tensorflow/federated#481]
How can I get local outputs in the tutorial federated_learning_for_image_classification?

**Comment by ZacharyGarrett** [comment]
This doesn't sound like a code issue. Rather, would you mind asking this "how to use" question at https://stackoverflow.com/questions/tagged/tensorflow-federated? That way the community and future users with a similar question can benefit.

**Comment by ZacharyGarrett** [comment]
@alicelh, thanks for posting to StackOverflow!
