### ISSUE TITLE
About the server

### ISSUE THREAD

**Issue by mlchuxueing** [tensorflow/federated#483]
Hello, I would like to ask, there is no data training on the server side, but the server will merge the models of each client and update based on FedAvg algorithm, then the model I got is the final server model? Moreover, how do I get the client model?

**Comment by michaelreneer** [comment]
@mlchuxueing Thanks for your interest in Tensorflow Federated! This is a great question, could you please re-direct your question to [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow-federated)?
