### ISSUE TITLE
Tensorflow Federated performance issues

### ISSUE THREAD

**Issue by AbbasiAYE** [tensorflow/federated#553]
Hi,

I know that this might/might not be the right place for posting about performance degradation of the TFF model performance comparing to single keras model. However, I post a detailed question on stackOverflow (below is the link) without any reesponse. Hence, I'd greatly appreciate the help.

https://stackoverflow.com/questions/56514398/why-the-tensorflow-federated-performance-is-worse-than-single-keras-model

**Comment by ZacharyGarrett** [comment]
Hypothesis (hyperparameter tuning) and potential solution are described on StackOverflow.
