### ISSUE TITLE
Federated with KerasRegressor?

### ISSUE THREAD

**Issue by AbbasiAYE** [tensorflow/federated#593]
Hello

I'm trying to get my model of KerasRegressor working with TFF framework. But it seems that "tff.learning.from_compiled_keras_model" does not accept it, right?. My main aim is to differentiate between federated on both regression problem and classification problem.

This is my relevant part of the code:

```
def create_SK_model():
    modelF = create_SGD_model()
    modelF.compile(loss=tf.keras.losses.MSE,optimizer=tf.keras.optimizers.SGD(lr=learn_rate))
    return modelF
    
def create_Reg_model():
    modelF_Reg = tf.keras.wrappers.scikit_learn.KerasRegressor(build_fn = create_SK_model,nb_epoch=SNN_epoch, batch_size=SNN_batch_size)
        
    return modelF_Reg

def create_Class_model():
    modelF_Reg = tf.keras.wrappers.scikit_learn.KerasClassifier(build_fn = create_SK_model,nb_epoch=SNN_epoch, batch_size=SNN_batch_size)
    return modelF_Class

def create_Single_model():
    if Use_RegClas:
        if Use_Regressor:
            return create_Reg_model()
        elif Use_Classification:
            return create_Class_model()
    else:
        return create_SK_model()
def model_fn_Federated():
    if Use_RegClas:
        if Use_Regressor:
            return tff.learning.from_compiled_keras_model(create_Reg_model,sample_batch)
        elif Use_Classification:
            return tff.learning.from_compiled_keras_model(create_Class_model(),sample_batch)
    elif Use_FLAveraging:
        return tff.learning.from_compiled_keras_model(create_SK_model(),sample_batch)
    else:
        return tff.learning.from_keras_model(create_SGD_model(),sample_batch,loss=tf.keras.losses.MSE)


................... some other code ..................

if Use_FLAveraging:
    trainer_Itr_Process = tff.learning.build_federated_averaging_process(model_fn_Federated,server_optimizer_fn=(lambda : tf.keras.optimizers.SGD(learning_rate=learn_rate)),client_weight_fn=None)
else:
    trainer_Itr_Process = tff.learning.build_federated_sgd_process(model_fn_Federated,server_optimizer_fn=(lambda : tf.keras.optimizers.SGD(learning_rate=learn_rate)),client_weight_fn=None)
    

```

My main problem is how to incorporate the Regression/classfiication problem into Federated TF framework. I tried the above implementation, correct? wrong? please advice.

Based on the above implementation I get the following error:

```
.....
    py_typecheck.check_type(keras_model, tf.keras.Model)
  File "/home/..../.local/lib/python3.6/site-packages/tensorflow_federated/python/common_libs/py_typecheck.py", line 48, in check_type
    type_string(type_spec), type_string(type(target))))
TypeError: Expected tensorflow.python.keras.engine.training.Model, found function.

```

**Comment by ZacharyGarrett** [comment]
[`tff.learning.from_keras_model`](https://www.tensorflow.org/federated/api_docs/python/tff/learning/from_keras_model) and [`tff.learning.from_compiled_keras_model`](https://www.tensorflow.org/federated/api_docs/python/tff/learning/from_compiled_keras_model) support (and require) the [`tf.keras.Model`](https://www.tensorflow.org/api_docs/python/tf/keras/Model?hl=en) interface. Both regression and classification models can be implemented using the `tf.keras.Model` interface.

`tf.keras.wrappers.scikit_learn` provides wrapper classes that allow a `tf.keras.Model` to be used in the `scitkit_learn` module. They do not inherit from `tf.keras.Model` nor implement its interface, and hence are not supported in TFF. 

From the code it looks like passing the result of `create_SGD_model()` (assumed to be a `tf.kears.Model`) to `tff.learning.from_keras_model()` may be what is desired. Wrapping the `tf.keras.Model`  with `KerasClassifier` or `KerasRegressor` adds an additional layer of abstraction for using the model with `scikit_learn`, but not necessary for TFF.
