### ISSUE TITLE
front page example does not run

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#677]
hi,

I've installed tensorflow-federated and tried to run the main short example in https://www.tensorflow.org/federated

it fails because from `tensorflow_federated.python.examples` does not seem to be included in the published version

(I think the example should be updated in a way that makes it immediately runnable after tff install)

**Comment by krzys-ostrowski** [comment]
Sorry for that, please try this: https://github.com/tensorflow/federated/releases/tag/v0.7.0

**Comment by amitport** [comment]
works with tff@0.7.0 (and python 3.7) 
thanks!
