### ISSUE TITLE
Can't run the result of "hello world"

### ISSUE THREAD

**Issue by niklausliu** [tensorflow/federated#724]
I have installed all the dependent function packages, and I have not reported an error, but I have been running for no results.

**Comment by hdliuyi** [comment]
/home/liuyi/venv/bin/python3.6 /home/liuyi/PycharmProjects/FL_images/fl_minst.py
WARNING: Logging before flag parsing goes to stderr.
W0723 15:41:17.035517 140592739182400 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-07-23 15:41:17.663317: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-23 15:41:17.690462: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2601000000 Hz
2019-07-23 15:41:17.690809: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fde20149ef0 executing computations on platform Host. Devices:
2019-07-23 15:41:17.690836: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>


This situation has remained unchanged for 15 minutes.

**Comment by jkr26** [comment]
Hi @hdliuyi,

Could you give some more detail? In particular, what command you are running, the output of pip freeze in your environment, and the code you are trying to execute? Also, are you building TFF from source or installign the pip package?

**Comment by lc0** [comment]
Just tested on fresh env in conda and it works fine. Output is a bit noisy but the last line is actually `Hello world`

@hdliuyi are you sure, that you do not get the last line as expected?

**Comment by hdliuyi** [comment]
> Hi @hdliuyi,
> 
> Could you give some more detail? In particular, what command you are running, the output of pip freeze in your environment, and the code you are trying to execute? Also, are you building TFF from source or installing the pip package?

I am building TFF by installing the pip package. Actually, I can not run the code to output "hello world", but I can run other codes, for example, TFF_CNN. Very strange!!!

**Comment by hdliuyi** [comment]
> Just tested on fresh env in conda and it works fine. Output is a bit noisy but the last line is actually `Hello world`
> 
> @hdliuyi are you sure, that you do not get the last line as expected?

Yes, sure. I can not run the code to output 'hello world'.

**Comment by hdliuyi** [comment]
My code as follow:
from __future__ import absolute_import, division, print_function

import collections
import warnings
from six.moves import range
import numpy as np
import six
import tensorflow as tf

warnings.simplefilter('ignore')

tf.compat.v1.enable_v2_behavior()

import tensorflow_federated as tff

np.random.seed(0)

NUM_CLIENTS = 10

# NOTE: If the statement below fails, it means that you are
# using an older version of TFF without the high-performance
# executor stack. Call `tff.framework.set_default_executor()`
# instead to use the default reference runtime.
if six.PY3:
  tff.framework.set_default_executor(
      tff.framework.create_local_executor(NUM_CLIENTS))

tff.federated_computation(lambda: 'Hello, World!')()

**Comment by hdliuyi** [comment]
My code as follow:
`from __future__ import absolute_import, division, print_function

import collections
import warnings
from six.moves import range
import numpy as np
import six
import tensorflow as tf

warnings.simplefilter('ignore')

tf.compat.v1.enable_v2_behavior()

import tensorflow_federated as tff

np.random.seed(0)

NUM_CLIENTS = 10

if six.PY3:
  tff.framework.set_default_executor(
      tff.framework.create_local_executor(NUM_CLIENTS))

tff.federated_computation(lambda: 'Hello, World!')()`

**Comment by lc0** [comment]
@niklausliu can you print your pip freeze or even directly in notebook

```py
try:
    from pip._internal.operations import freeze
except ImportError:  # pip < 10.0
    from pip.operations import freeze

for module in freeze.freeze():
    print(module)
```

**Comment by jkr26** [comment]
From looking at the snippet above, are you running this in a ipython notebook, or as a Python script? If as a Python script, is it possible that the string `'Hello, World!'` is being returned inside the script, but not printed? If so, simply inserting a print statement on the last line should resolve this issue.

**Comment by jkr26** [comment]
Closing, assuming this was lack of a print statement. Feel free to reopen if that wasn't the case.
