### ISSUE TITLE
TF 2.0 migration

### ISSUE THREAD

**Issue by lc0** [tensorflow/federated#741]
Any plans to migrate to support 2.0?

From contrib side, I can see package failing on `tf.contrib.image`, where some functionality like `angles_to_projective_transforms` a well as `translations_to_projective_transforms ` and `compose_transforms` are already supported by [tf/addons](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/image)

So if you are interested, I can migrate this to use addons directly.

Additional visible contrib dependency is `contrib.framework.nest` that looks like is available within `tensorflow.python.data.util` with example would be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/dataset_ops.py#L540

cc @dynamicwebpaige

**Comment by lc0** [comment]
@jkr26 sounds great. Lemme know if you have a beta to test. Happy to test on my side

**Comment by ZacharyGarrett** [comment]
@lc0 the latest version of TFF (`0.9.0`) is fully migrated to TF 2.0. Please take a look!
