### ISSUE TITLE
Unable to run Image classification example

### ISSUE THREAD

**Issue by jqin4749** [tensorflow/federated#743]
I am running the image classification example on my local computer with Python3.5.1, tensorflow 1.4.1 and tensorflow-federated 0.7

I used the exact same codes and the following error occurs at `iterative_process = tff.learning.build_federated_averaging_process(model_fn)`

the following the Error trace:
`TypeError                                 Traceback (most recent call last)
<ipython-input-11-fe6de5c64986> in <module>
      1 #@test {"output": "ignore"}
----> 2 iterative_process = tff.learning.build_federated_averaging_process(model_fn)

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/learning/federated_averaging.py in build_federated_averaging_process(model_fn, server_optimizer_fn, client_weight_fn, stateful_delta_aggregate_fn, stateful_model_broadcast_fn)
    162   return optimizer_utils.build_model_delta_optimizer_process(
    163       model_fn, client_fed_avg, server_optimizer_fn,
--> 164       stateful_delta_aggregate_fn, stateful_model_broadcast_fn)

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/learning/framework/optimizer_utils.py in build_model_delta_optimizer_process(model_fn, model_to_client_delta_fn, server_optimizer_fn, stateful_delta_aggregate_fn, stateful_model_broadcast_fn)
    359   server_state_type = tf_init_fn.type_signature.result
    360 
--> 361   @tff.tf_computation(tf_dataset_type, server_state_type.model)
    362   def tf_client_delta(tf_dataset, initial_model_weights):
    363     """Performs client local model optimization.

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py in <lambda>(fn)
    413         args = (args,)
    414       arg_type = computation_types.to_type(args[0])
--> 415       return lambda fn: _wrap(fn, arg_type, self._wrapper_fn)

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py in _wrap(fn, parameter_type, wrapper_fn)
    101 
    102   # Either we have a concrete parameter type, or this is no-arg function.
--> 103   concrete_fn = wrapper_fn(fn, parameter_type, unpack=None)
    104   py_typecheck.check_type(concrete_fn, function_utils.ConcreteFunction,
    105                           'value returned by the wrapper')

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/computation_wrapper_instances.py in _tf_wrapper_fn(***failed resolving arguments***)
     42   ctx_stack = context_stack_impl.context_stack
     43   comp_pb, extra_type_spec = tensorflow_serialization.serialize_py_fn_as_tf_computation(
---> 44       target_fn, parameter_type, ctx_stack)
     45   return computation_impl.ComputationImpl(comp_pb, ctx_stack, extra_type_spec)
     46 

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/tensorflow_serialization.py in serialize_py_fn_as_tf_computation(target, parameter_type, context_stack)
    266     context = tf_computation_context.TensorFlowComputationContext(graph)
    267     with context_stack.install(context):
--> 268       result = target(*args)
    269 
    270       # TODO(b/122081673): This needs to change for TF 2.0. We may also

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/function_utils.py in <lambda>(arg)
    583       except NameError:
    584         raise AssertionError('Args to be bound must be in scope.')
--> 585       return lambda arg: _unpack_and_call(fn, arg_types, kwarg_types, arg)
    586     else:
    587       # An interceptor function that verifies the actual parameter before it

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/function_utils.py in _unpack_and_call(fn, arg_types, kwarg_types, arg)
    554         for idx, expected_type in enumerate(arg_types):
    555           element_value = arg[idx]
--> 556           actual_type = type_utils.infer_type(element_value)
    557           if not type_utils.is_assignable_from(expected_type, actual_type):
    558             raise TypeError('Expected element at position {} to be '

~/.local/lib/python3.5/site-packages/tensorflow_federated/python/core/impl/type_utils.py in infer_type(arg)
     64     return computation_types.SequenceType(
     65         tf_dtypes_and_shapes_to_type(
---> 66             tf.compat.v1.data.get_output_types(arg),
     67             tf.compat.v1.data.get_output_shapes(arg)))
     68   elif isinstance(arg, anonymous_tuple.AnonymousTuple):

~/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py in get_legacy_output_types(dataset_or_iterator)
   2037     of an element of this dataset.
   2038   """
-> 2039   return get_structure(dataset_or_iterator)._to_legacy_output_types()  # pylint: disable=protected-access
   2040 
   2041 

~/.local/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py in get_structure(dataset_or_iterator)
   2001     pass
   2002   raise TypeError("`dataset_or_iterator` must be a Dataset or Iterator object, "
-> 2003                   "but got %s." % type(dataset_or_iterator))
   2004 
   2005 

TypeError: `dataset_or_iterator` must be a Dataset or Iterator object, but got <class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>.
`

**Comment by ZacharyGarrett** [comment]
`tensorflow-federated v0.7.0` may not be compatible with `tensorflow v1.14.1`. The table of TFF and TF compatibility is here: https://github.com/tensorflow/federated#compatibility

Could you try uninstalling the `tensorflow` pip package and install `tf-nightly` with version `1.15.0.dev20190711` or newer?

**Comment by jqin4749** [comment]
> `tensorflow-federated v0.7.0` may not be compatible with `tensorflow v1.14.1`. The table of TFF and TF compatibility is here: https://github.com/tensorflow/federated#compatibility
> 
> Could you try uninstalling the `tensorflow` pip package and install `tf-nightly` with version `1.15.0.dev20190711` or newer?

Thanks! I solved tihs by using python3.7.
