### ISSUE TITLE
Cannot use with tf-nightly-gpu

### ISSUE THREAD

**Issue by klize** [tensorflow/federated#744]
Here are my installation steps

machine:
cuda 10.0
cuDNN v7.5

1. activate virtualenv with python 3.5.2, 
2. install tensorflow_federated from pip command
    -> successfully finished with learning on cpu
3. remove tf-nightly and install tensorflow-gpu
    -> got an error; dataset_or_iterator must be a Dataset or Iterator object.
4. install tf-nightly-gpu
    -> Things seems to work well, but it tells me i need cuDNN v7.6.

But mine is cuDNN v7.5. Do i need to upgrade the library ? 
Or I got something wrong with the installation steps ?

**Comment by jkr26** [comment]
Hi @klize,

It does seem that upgrading cuDNN is your best bet. TFF develops close to tf-nightly internally, and this can cause issues when using a released version of tensorflow (the `dataset_or_iterator` error is one such issue; TFF uses variant tensors to represent `tf.data.Datasets`, as in `tf.data.experimental.to/from_variant`).

This means that the best bet for a TFF power user is to always ensure they are using the appropriate `tf-nightly` package, and it seems that `tf-nightly-gpu` is dropping support for cuDNN 7.5 and moving to 7.6.
