### ISSUE TITLE
Need help for "federated_learning_for_text_generation"

### ISSUE THREAD

**Issue by JKbasara** [tensorflow/federated#747]
when run the line "state, metrics = fed_avg.next(state, [example_dataset.take(1)])"

I got this error:
TypeError: The tensor type int64[8,100] of the value representation does not match the type spec int32[?,100].

How to solve it?

Thx first~~~

**Comment by jkr26** [comment]
Hi @JKbasara,

I think our best bet here is some version mismatch--so can we get some more detail on a few things?

First, how are you running this code? Is it in a hosted colab runtime (e.g. in a browser on colab.sandbox.google.com), a local jupyter notebook, or as a standalone python script?

Second, can you give the versions of all the python packages in the runtime you are using? E.g. if you're on colab, the output of running `!pip freeze` in a cell, or if you are running as a script in a Conda environment, the output of `conda list -n myenv`? However you're running this, I think we will need the package versions.

Finally, could we get a deeper stacktrace? The error is from TFF, but it's not exactly clear to me where in the stack this is coming from.

Happy to help! Thanks for your interest in TFF!

Keith

**Comment by JKbasara** [comment]
> Hi @JKbasara,
> 
> I think our best bet here is some version mismatch--so can we get some more detail on a few things?
> 
> First, how are you running this code? Is it in a hosted colab runtime (e.g. in a browser on colab.sandbox.google.com), a local jupyter notebook, or as a standalone python script?
> 
> Second, can you give the versions of all the python packages in the runtime you are using? E.g. if you're on colab, the output of running `!pip freeze` in a cell, or if you are running as a script in a Conda environment, the output of `conda list -n myenv`? However you're running this, I think we will need the package versions.
> 
> Finally, could we get a deeper stacktrace? The error is from TFF, but it's not exactly clear to me where in the stack this is coming from.
> 
> Happy to help! Thanks for your interest in TFF!
> 
> Keith

Thank you! Keith
I got your idea~~~

Im a graduate student and our team are trying to use TFF for a project research.
All my codes run above the environment of **Win10 and Visual Studio 2019**.
These are my python packages:
 
![image](https://user-images.githubusercontent.com/4019752/63480094-33e7b200-c4c3-11e9-9b52-4e6d337ec409.png)

all packages list:
![image](https://user-images.githubusercontent.com/4019752/63480143-642f5080-c4c3-11e9-9f70-3e33f95687f3.png)
![image](https://user-images.githubusercontent.com/4019752/63480180-89bc5a00-c4c3-11e9-954c-882e9e950391.png)

By the way, **I can run it well at Google Colab**, so I think that maybe I miss some packages.

The log for error:

**Apply a constraint manually following the optimizer update step.
E0822 10:09:35.617088 20464 federated_learning_for_text_generation.py:173] The tensor type int64[8,100] of the value representation does not match the type spec int32[?,100].
Traceback (most recent call last):
  File "D:\XXX\Python\XXX\TFF_tutorials\federated_learning_for_text_generation.py", line 171, in <module>
    state, metrics = fed_avg.next(state, [example_dataset.take(1)])
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 629, in __call__
    arg = pack_args(self._type_signature.parameter, args, kwargs, context)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 387, in pack_args
    context)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py", line 309, in pack_args_into_anonymous_tuple
    result_elements.append((name, context.ingest(arg_value, elem_type)))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 670, in ingest
    return to_representation_for_type(arg, type_spec, _handle_callable)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 240, in to_representation_for_type
    for v in value
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 240, in <listcomp>
    for v in value
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 199, in to_representation_for_type
    for v in value
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 199, in <listcomp>
    for v in value
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 191, in to_representation_for_type
    callable_handler)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_federated\python\core\impl\reference_executor.py", line 164, in to_representation_for_type
    'the type spec {}.'.format(inferred_type_spec, type_spec))
TypeError: The tensor type int64[8,100] of the value representation does not match the type spec int32[?,100].**

For more details about my code (I am a beginner for python and TFF), I am very glad to offer more info.

**Comment by jkr26** [comment]
Interesting. I suspect that this has something to do with running on Windows, as we generally build and run on Linux. What seems to be *not* happening correctly is the following code snippet from the tutorial:
```
def create_tff_model():
  x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]))
  dummy_batch = collections.OrderedDict([('x', x), ('y', x)]) 
  keras_model_clone = compile(tf.keras.models.clone_model(keras_model))
  return tff.learning.from_compiled_keras_model(
      keras_model_clone, dummy_batch=dummy_batch)
```

TFF is strongly-typed (with its own type system), so functions generally need type declarations, or some way to infer the types they should expect to accept and return. This *should* be taken care of by this code snippet, as part of the under-the-hood integration between TFF and TF, in particular keras.

What seems to be happening here is: TFF performs type inference on the models it constructs by using a dummy batch of data. It looks to me that the data generated by the `tf.constant` call in the above snippet is actually coming out as `tf.int32`, and thus this is the type expected by TFF for its input data. However, the dataset clearly generates int64 entries, and thus TFF raises.

It is possible that there are some subtle differences in the Windows distributions, although one would think `pip` would abstract this away. Perhaps the lack of a standalone Keras package is causing some misdirection (when I `pip freeze` after installing TFF to a colab, I see a Keras 2.2.5 install, which comes pre-installed in Colab runtimes).

I think if you don't want to worry about these issues, however, there *should* be a simple fix. Try simply replacing 
```
x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]))
```
above, with:
```
x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]), dtype=tf.int64)
```
Unfortunately since we have no Windows machines easily available, we can't really repro your issue and make sure this works...

**Comment by JKbasara** [comment]
> Interesting. I suspect that this has something to do with running on Windows, as we generally build and run on Linux. What seems to be _not_ happening correctly is the following code snippet from the tutorial:
> 
> ```
> def create_tff_model():
>   x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]))
>   dummy_batch = collections.OrderedDict([('x', x), ('y', x)]) 
>   keras_model_clone = compile(tf.keras.models.clone_model(keras_model))
>   return tff.learning.from_compiled_keras_model(
>       keras_model_clone, dummy_batch=dummy_batch)
> ```
> 
> TFF is strongly-typed (with its own type system), so functions generally need type declarations, or some way to infer the types they should expect to accept and return. This _should_ be taken care of by this code snippet, as part of the under-the-hood integration between TFF and TF, in particular keras.
> 
> What seems to be happening here is: TFF performs type inference on the models it constructs by using a dummy batch of data. It looks to me that the data generated by the `tf.constant` call in the above snippet is actually coming out as `tf.int32`, and thus this is the type expected by TFF for its input data. However, the dataset clearly generates int64 entries, and thus TFF raises.
> 
> It is possible that there are some subtle differences in the Windows distributions, although one would think `pip` would abstract this away. Perhaps the lack of a standalone Keras package is causing some misdirection (when I `pip freeze` after installing TFF to a colab, I see a Keras 2.2.5 install, which comes pre-installed in Colab runtimes).
> 
> I think if you don't want to worry about these issues, however, there _should_ be a simple fix. Try simply replacing
> 
> ```
> x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]))
> ```
> 
> above, with:
> 
> ```
> x = tf.constant(np.random.randint(1, len(vocab), size=[BATCH_SIZE, SEQ_LENGTH]), dtype=tf.int64)
> ```
> 
> Unfortunately since we have no Windows machines easily available, we can't really repro your issue and make sure this works...

@jkr26 Thank you! It worked.
