### ISSUE TITLE
The official document should be updated

### ISSUE THREAD

**Issue by zzhu2019** [tensorflow/federated#748]
Hi there,

I got a bug that the `tff.utlis.get_variables()` function cannot be found under [python/core/utils/tf_computation_utils.py](http://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/core/utils/tf_computation_utils.py) which confused me a lot. After I accessed the directory to check the tf_computation_utlis.py file, I found that `tff.utlis.get_variables()` has been changed into `tff.utlis.create_variables()`. I suppose both the API document and tutorials should be updated correspondingly to prevent further confusions.

**Comment by JKbasara** [comment]
And the version of TFF should be updated too. The document said the version is 0.7.0, but the current version for demo is 0.8.0 these days.

**Comment by ZacharyGarrett** [comment]
Apologies for the delay, the documentation should now be updated. The text generation and image classification tutorials still need some work, but the API docs and the custom federated algorithms tutorials (part1 and part2) should be good to go.
