### ISSUE TITLE
Fail to test the tff in macos

### ISSUE THREAD

**Issue by zzhu2019** [tensorflow/federated#752]
Hi there,

I have been playing with tff in colab for a while, but whenever I tried to install tff in  my local Pycharm and run the test code `tff.federated_computation(lambda: 'Hello, World!')()`. There is just nothing to print, and the process finished normally. I have double-checked that I have the same pre-requisite as in the doc.
![image](https://user-images.githubusercontent.com/38281790/63576904-8a8ee200-c5d0-11e9-9764-f393b7a4a0bf.png)

**Comment by ZacharyGarrett** [comment]
Could you try wrapping with a `print()` call, similar to the change made in #738

```python
print(tff.federated_computation(lambda: 'Hello, World!')())
```

**Comment by zzhu2019** [comment]
> Could you try wrapping with a `print()` call, similar to the change made in #738
> 
> ```python
> print(tff.federated_computation(lambda: 'Hello, World!')())
> ```

Oh, I should have found that. Thx for your help.
