### ISSUE TITLE
TypeError: `dataset_or_iterator` must be a Dataset or Iterator object

### ISSUE THREAD

**Issue by phalangee** [tensorflow/federated#755]
```
@tff.tf_computation(tff.SequenceType(tf.float32))
def get_local_temperature_average(local_temperatures):
  sum_and_count = (
      local_temperatures.reduce((0.0, 0), lambda x, y: (x[0] + y, x[1] + 1)))
  return sum_and_count[0] / tf.cast(sum_and_count[1], tf.float32)
```

**This code from custom_federated_algorithms_1.ipynb** 
    **python: 3.7.2** 
   **tensorflow: 1.14.0**
   **tensorflow-federated : 0.8.0**
   **tf-nightly: 1.15.0.dev20190805**  
**and I got this error:** 

`TypeError: "dataset_or_iterator" must be a Dataset or Iterator object, but got <class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>.`
**more information about error:**
```
TypeError                                 Traceback (most recent call last)
<ipython-input-35-3c145a7e5ece> in <module>
----> 1 @tff.tf_computation(tff.SequenceType(tf.float32))
      2 
      3 def get_local_temperature_average(local_temperatures):
      4   sum_and_count = (
      5       local_temperatures.reduce((0.0, 0), lambda x, y: (x[0] + y, x[1] + 1)))

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py in <lambda>(fn)
    413         args = (args,)
    414       arg_type = computation_types.to_type(args[0])
--> 415       return lambda fn: _wrap(fn, arg_type, self._wrapper_fn)

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/computation_wrapper.py in _wrap(fn, parameter_type, wrapper_fn)
    101 
    102   # Either we have a concrete parameter type, or this is no-arg function.
--> 103   concrete_fn = wrapper_fn(fn, parameter_type, unpack=None)
    104   py_typecheck.check_type(concrete_fn, function_utils.ConcreteFunction,
    105                           'value returned by the wrapper')

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/computation_wrapper_instances.py in _tf_wrapper_fn(***failed resolving arguments***)
     42   ctx_stack = context_stack_impl.context_stack
     43   comp_pb, extra_type_spec = tensorflow_serialization.serialize_py_fn_as_tf_computation(
---> 44       target_fn, parameter_type, ctx_stack)
     45   return computation_impl.ComputationImpl(comp_pb, ctx_stack, extra_type_spec)
     46 

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/tensorflow_serialization.py in serialize_py_fn_as_tf_computation(target, parameter_type, context_stack)
    266     context = tf_computation_context.TensorFlowComputationContext(graph)
    267     with context_stack.install(context):
--> 268       result = target(*args)
    269 
    270       # TODO(b/122081673): This needs to change for TF 2.0. We may also

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py in <lambda>(arg)
    600       except NameError:
    601         raise AssertionError('Args to be bound must be in scope.')
--> 602       return lambda arg: _call(fn, parameter_type, arg)
    603 
    604 

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py in _call(fn, parameter_type, arg)
    587       # forwards the call as a last-minute check.
    588       def _call(fn, parameter_type, arg):
--> 589         arg_type = type_utils.infer_type(arg)
    590         if not type_utils.is_assignable_from(parameter_type, arg_type):
    591           raise TypeError('Expected an argument of type {}, found {}.'.format(

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/type_utils.py in infer_type(arg)
     63     return computation_types.SequenceType(
     64         tf_dtypes_and_shapes_to_type(
---> 65             tf.compat.v1.data.get_output_types(arg),
     66             tf.compat.v1.data.get_output_shapes(arg)))
     67   elif isinstance(arg, anonymous_tuple.AnonymousTuple):

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in get_legacy_output_types(dataset_or_iterator)
   2037     of an element of this dataset.
   2038   """
-> 2039   return get_structure(dataset_or_iterator)._to_legacy_output_types()  # pylint: disable=protected-access
   2040 
   2041 

~/Python-3.7.2/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in get_structure(dataset_or_iterator)
   2001     pass
   2002   raise TypeError("`dataset_or_iterator` must be a Dataset or Iterator object, "
-> 2003                   "but got %s." % type(dataset_or_iterator))
   2004 
   2005 

TypeError: `dataset_or_iterator` must be a Dataset or Iterator object, but got <class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>.
```
 **if you need any information please tell me,i'd like to add it.  Thanks a lot !**

**Comment by ZacharyGarrett** [comment]
@phalangee could you try adding `tf.compat.v1.enable_v2_behavior()` just after the code imports tensorflow?

**Comment by happy2019-k** [comment]
> @phalangee could you try adding `tf.compat.v1.enable_v2_behavior()` just after the code imports tensorflow?
I met the same problem. I tried this method you suggested, but the same problem arose. Is there any other solution? Look forward to your reply, Thanks.

**Comment by nakibmehdi** [comment]
> @ZacharyGarrett > @phalangee could you try adding `tf.compat.v1.enable_v2_behavior()` just after the code imports tensorflow?
> I met the same problem. I tried this method you suggested, but the same problem arose. Is there any other solution? Look forward to your reply, Thanks.

Me too I tried this suggestion but didn't work for me as well. Is there any suggestion please. Thank You

**Comment by ZacharyGarrett** [comment]
Sorry I didn't notice earlier: it looks like both `tensorflow==1.14.0` and  `tf-nightly==1.15.0.dev20190805` pip packages are installed, which might be causing problems. @nakibmehdi is this true for your system also?

TFF requires the newer nightly package, and the system maybe pulling the libraries from the `tensorflow=1.14.0` package. Could you please try uninstalling the `tensorflow` pip package and only installing the `tf-nightly` package?  I'd strongly recommend doing this inside of a virtual environment (see more at https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)

**Comment by phalangee** [comment]
> Sorry I didn't notice earlier: it looks like both `tensorflow==1.14.0` and `tf-nightly==1.15.0.dev20190805` pip packages are installed, which might be causing problems. @nakibmehdi is this true for your system also?
> 
> TFF requires the newer nightly package, and the system maybe pulling the libraries from the `tensorflow=1.14.0` package. Could you please try uninstalling the `tensorflow` pip package and only installing the `tf-nightly` package? I'd strongly recommend doing this inside of a virtual environment (see more at https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)

thank you,I tried the two methods that you mentioned but it didn't work.
`tensorflow=1.14.0`,`tf-nightly` ,`tensorflow-federated` are all installed in my virtual enviroment ,I noticed that  most code in tutorials need` import tensorflow` ,if  `pip uninstall tensorflow` , it will report an error: `"No module named 'tensorflow'"` . Is there any suggestion please or you need any information about error please tell me

**Comment by HandsomeHans** [comment]
I met the same error today:

os: Ubuntu 18.04
python: 3.6.8
IDE: Pycharm Runtime version: 11.0.3+12-b304.39 amd64
tensorflow: 1.14.0
tensorflow-federated : 0.8.0
tf-nightly: 1.15.0.dev20190805

Thank you @ZacharyGarrett for the two methotds, but neither of them worked.

**Comment by HandsomeHans** [comment]
@ZacharyGarrett @phalangee 

I solved this problem by uninstall tensorflow and tf-nightly and then reinstall tf-nightly.

**Comment by ZacharyGarrett** [comment]
Thanks @HandsomeHans!

@phalangee If `tensorflow` was not uninstalled before installing `tensorflow-federated`, likely `tf-nightly` needs to be installed again the steps form @HandsomeHans should achieve this. Alternatively, when creating a new virtual environment avoid pip installing `tensorflow` and only install `tensorflow-federated` which will also install the necessary dependency `tf-nightly` automatically.

**Comment by phalangee** [comment]
Thanks @ZacharyGarrett  @HandsomeHans  I have solved this problem as you suggested. Thank you very much !

**Comment by savi-hub** [comment]
I am still getting same error.. I have tried to uninstall tensorflow , and installing tensorflow- federated
