### ISSUE TITLE
Problem with 'tf-nightly version'

### ISSUE THREAD

**Issue by HaiQW** [tensorflow/federated#759]
File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 2106, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1997, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/framework/func_graph.py", line 884, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 325, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 2614, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages/tensorflow_core/python/framework/func_graph.py", line 874, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in converted code:
    relative to /Users/haiqw/anaconda3/envs/py3/lib/python3.5/site-packages:

    tensorflow_federated/python/tensorflow_libs/tensor_utils.py:115 zero_all_if_any_non_finite
        if all_finite:
    tensorflow_core/python/framework/ops.py:762 __bool__
        self._disallow_bool_casting()
    tensorflow_core/python/framework/ops.py:531 _disallow_bool_casting
        "using a `tf.Tensor` as a Python `bool`")
    tensorflow_core/python/framework/ops.py:518 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

**Comment by ZacharyGarrett** [comment]
Thanks for the report!

Could you share a few more pieces of information? 

- output of `pip freeze`
- output of `python --version`
- operating system
- the code snippet being run that leads to the stack trace

Thanks!

**Comment by HaiQW** [comment]
> Thanks for the report!
> 
> Could you share a few more pieces of information?
> 
> * output of `pip freeze`
> * output of `python --version`
> * operating system
> * the code snippet being run that leads to the stack trace
> 
> Thanks!
pip freeze:
absl-py==0.8.0
astor==0.8.0
attrs==18.2.0
cachetools==3.1.1
certifi==2019.6.16
enum34==1.1.6
gast==0.3.1
google-pasta==0.1.7
grpcio==1.22.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.2
opt-einsum==3.0.1
portpicker==1.3.1
protobuf==3.9.1
six==1.12.0
tb-nightly==1.15.0a20190908
tensorflow-federated==0.8.0
tensorflow-model-optimization==0.1.3
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019090801
tf-nightly==1.15.0.dev20190805
Werkzeug==0.15.6
wrapt==1.11.2

python --version:
Python 3.6.9 :: Anaconda, Inc.

OS: macOS mojave 10.14.2

**Comment by williamcityu** [comment]
@ZacharyGarrett I also encountered a similar problem as HaiQW. So I directly post it here for your reference. Thanks. 

- OS
System: macOS 10.14.6, Kernel: Darwin 18.7.0

- python --version
Python 3.7.4

- pip freeze 
absl-py==0.8.0
astor==0.8.0
attrs==18.2.0
cachetools==3.1.1
enum34==1.1.6
gast==0.3.1
google-pasta==0.1.7
grpcio==1.22.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.2
opt-einsum==3.0.1
portpicker==1.3.1
protobuf==3.9.1
six==1.12.0
tb-nightly==1.15.0a20190908
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-federated==0.8.0
tensorflow-model-optimization==0.1.3
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019090801
tf-nightly==1.15.0.dev20190805
Werkzeug==0.15.6
wrapt==1.11.2

- code snippet
A very simple example from the tutorial 

```
 from six.moves import range
 import tensorflow as tf
 import tensorflow_federated as tff
 from tensorflow_federated.python.examples import mnist
 tf.compat.v1.enable_v2_behavior()

 # Load simulation data.
 source, _ = tff.simulation.datasets.emnist.load_data()
 def client_data(n):
   dataset = source.create_tf_dataset_for_client(source.client_ids[n])
   return mnist.keras_dataset_from_emnist(dataset).repeat(10).batch(20)

 # Pick a subset of client devices to participate in training.
 train_data = [client_data(n) for n in range(3)]

 # Grab a single batch of data so that TFF knows what data looks like.
 sample_batch = tf.nest.map_structure(
     lambda x: x.numpy(), iter(train_data[0]).next())

 # Wrap a Keras model for use with TFF.
 def model_fn():
   return tff.learning.from_compiled_keras_model(
       mnist.create_simple_keras_model(), sample_batch)

 # Simulate a few rounds of training with the selected client devices.
 trainer = tff.learning.build_federated_averaging_process(model_fn)
 state = trainer.initialize()
 for _ in range(5):
   state, metrics = trainer.next(state, train_data)
   print (metrics.loss)
```

**Comment by williamcityu** [comment]
@HaiQW 
A walkaround solution here. Before you start, you should create a pure environment with "virtualenv". 
First, run "pip install -r requirements.txt" in federated folder you pulled from github
Then, pip install --upgrade tensorflow_federated
It works for me.

**Comment by HaiQW** [comment]
> @ZacharyGarrett I also encountered a similar problem as HaiQW. So I directly post it here for your reference. Thanks.
> 
> * OS
>   System: macOS 10.14.6, Kernel: Darwin 18.7.0
> * python --version
>   Python 3.7.4
> * pip freeze
>   absl-py==0.8.0
>   astor==0.8.0
>   attrs==18.2.0
>   cachetools==3.1.1
>   enum34==1.1.6
>   gast==0.3.1
>   google-pasta==0.1.7
>   grpcio==1.22.1
>   h5py==2.10.0
>   Keras-Applications==1.0.8
>   Keras-Preprocessing==1.1.0
>   Markdown==3.1.1
>   numpy==1.17.2
>   opt-einsum==3.0.1
>   portpicker==1.3.1
>   protobuf==3.9.1
>   six==1.12.0
>   tb-nightly==1.15.0a20190908
>   tensorboard==1.14.0
>   tensorflow==1.14.0
>   tensorflow-estimator==1.14.0
>   tensorflow-federated==0.8.0
>   tensorflow-model-optimization==0.1.3
>   termcolor==1.1.0
>   tf-estimator-nightly==1.14.0.dev2019090801
>   tf-nightly==1.15.0.dev20190805
>   Werkzeug==0.15.6
>   wrapt==1.11.2
> * code snippet
>   A very simple example from the tutorial
> 
> ```
>  from six.moves import range
>  import tensorflow as tf
>  import tensorflow_federated as tff
>  from tensorflow_federated.python.examples import mnist
>  tf.compat.v1.enable_v2_behavior()
> 
>  # Load simulation data.
>  source, _ = tff.simulation.datasets.emnist.load_data()
>  def client_data(n):
>    dataset = source.create_tf_dataset_for_client(source.client_ids[n])
>    return mnist.keras_dataset_from_emnist(dataset).repeat(10).batch(20)
> 
>  # Pick a subset of client devices to participate in training.
>  train_data = [client_data(n) for n in range(3)]
> 
>  # Grab a single batch of data so that TFF knows what data looks like.
>  sample_batch = tf.nest.map_structure(
>      lambda x: x.numpy(), iter(train_data[0]).next())
> 
>  # Wrap a Keras model for use with TFF.
>  def model_fn():
>    return tff.learning.from_compiled_keras_model(
>        mnist.create_simple_keras_model(), sample_batch)
> 
>  # Simulate a few rounds of training with the selected client devices.
>  trainer = tff.learning.build_federated_averaging_process(model_fn)
>  state = trainer.initialize()
>  for _ in range(5):
>    state, metrics = trainer.next(state, train_data)
>    print (metrics.loss)
> ```

Thanks.  The problem is now solved after upgrading TFF to the master version.

**Comment by pthai** [comment]
@HaiQW I'm having similar issues -- would you kindly post the working output from `pip freeze`?

**Comment by HaiQW** [comment]
> @HaiQW I'm having similar issues -- would you kindly post the working output from `pip freeze`?

The output of pip freeze is attached below.

```
absl-py==0.8.0
appnope==0.1.0
asn1crypto==0.24.0
astor==0.8.0
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
cachetools==3.1.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
dill==0.3.0
entrypoints==0.3
enum34==1.1.6
fuel==0.2.0
future==0.17.1
gast==0.2.2
google-pasta==0.1.7
googleapis-common-protos==1.6.0
grpcio==1.22.1
h5py==2.10.0
idna==2.8
importlib-metadata==0.19
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-core==4.5.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.0.2
mkl-service==2.3.0
mock==3.0.5
more-itertools==7.2.0
mpmath==1.1.0
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numexpr==2.7.0
numpy==1.17.2
olefile==0.46
opt-einsum==3.0.1
packaging==19.2
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
picklable-itertools==0.1.1
pickleshare==0.7.5
Pillow==6.1.0
pluggy==0.13.0
portpicker==1.3.1
progressbar2==3.46.1
prometheus-client==0.7.1
promise==2.2.1
prompt-toolkit==2.0.9
protobuf==3.9.1
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pycparser==2.19
Pygments==2.4.2
pyOpenSSL==19.0.0
pyparsing==2.4.2
pyrsistent==0.14.11
PySocks==1.7.1
pytest==5.1.2
pytest-runner==5.1
python-dateutil==2.8.0
python-utils==2.3.0
pytz==2019.2
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
requests==2.22.0
scikit-learn==0.21.3
scipy==1.3.1
Send2Trash==1.5.0
six==1.12.0
tables==3.5.2
tb-nightly==1.15.0a20190911
tensorflow-datasets==1.2.0
tensorflow-federated==0.8.0
tensorflow-metadata==0.14.0
tensorflow-model-optimization==0.1.3
tensorflow-privacy==0.0.1
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019091601
tf-nightly==1.15.0.dev20190805
tornado==6.0.3
tqdm==4.36.1
traitlets==4.3.2
typing==3.7.4.1
urllib3==1.25.5
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.6
widgetsnbextension==3.5.1
wrapt==1.11.2
yapf==0.28.0
zipp==0.5.2
```

A walkaround solution here. 
First, download the newest  version of tensorflow federated. 
Then,  run "pip install -r requirements.txt" in federated folder you pulled from github.
Last, pip install --upgrade tensorflow_federated 

It works for me.
