### ISSUE TITLE
Manipulating weight delta element-wisely

### ISSUE THREAD

**Issue by cpwan** [tensorflow/federated#763]
Say, for each entry in the weight delta, i would like to find its median among the clients. How can i do that? 
I am trying to build a custom `stateful_delta_aggregate_fn`  and feed that to `tff.learning.build_federated_averaging_process`, as a result, having elemental-wise median updates instead of FedAvg.

**Comment by ZacharyGarrett** [comment]
Could you please ask this question at https://stackoverflow.com/questions/tagged/tensorflow-federated? Questions about how to use TFF, or how to accomplish a task are best asked there.

We use the GitHub issues page for handling bugs in TFF.
