### ISSUE TITLE
TypeError: Expected a TensorFlow computation, found intrinsic.

### ISSUE THREAD

**Issue by dsudzeng** [tensorflow/federated#764]
This is from Federated_learning_for_image_classification.ipynb
tensorflow_federated 0.8.0
tensorflow nightly 1.15.0-dev20190805

run as a local notebook. It works on colab!

state = iterative_process.initialize()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-0c0dcd96a774> in <module>
----> 1 state = iterative_process.initialize()

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py in __call__(self, *args, **kwargs)
    628     context = self._context_stack.current
    629     arg = pack_args(self._type_signature.parameter, args, kwargs, context)
--> 630     return context.invoke(self, arg)
    631 
    632 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\execution_context.py in invoke(self, comp, arg)
    118   def invoke(self, comp, arg):
    119     return asyncio.get_event_loop().run_until_complete(
--> 120         _invoke(self._executor, comp, arg))

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\base_events.py in run_until_complete(self, future)
    482             raise RuntimeError('Event loop stopped before Future completed.')
    483 
--> 484         return future.result()
    485 
    486     def stop(self):

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\tasks.py in _step(***failed resolving arguments***)
    180                 result = coro.send(None)
    181             else:
--> 182                 result = coro.throw(exc)
    183         except StopIteration as exc:
    184             if self._must_cancel:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\execution_context.py in _invoke(executor, comp, arg)
     89     py_typecheck.check_type(arg, executor_value_base.ExecutorValue)
     90   comp = await executor.create_value(comp)
---> 91   result = await executor.create_call(comp, arg)
     92   py_typecheck.check_type(result, executor_value_base.ExecutorValue)
     93   result_val = _unwrap(await result.compute())

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\lambda_executor.py in create_call(self, comp, arg)
    273       # so this is the only case left to handle.
    274       py_typecheck.check_type(comp_repr, pb.Computation)
--> 275       eval_result = await self._evaluate(comp_repr, comp.scope)
    276       py_typecheck.check_type(eval_result, LambdaExecutorValue)
    277       if arg is not None:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\lambda_executor.py in _evaluate(self, comp, scope)
    376         arg = None
    377       return await self.create_call(
--> 378           LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
    379     elif which_computation == 'selection':
    380       which_selection = comp.selection.WhichOneof('selection')

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\lambda_executor.py in create_call(self, comp, arg)
    259         arg_type = type_utils.get_argument_type(arg.type_signature)
    260         type_utils.check_assignable_from(param_type, arg_type)
--> 261         return await self.create_call(comp, await self.create_call(arg))
    262     else:
    263       py_typecheck.check_none(arg)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\lambda_executor.py in create_call(self, comp, arg)
    273       # so this is the only case left to handle.
    274       py_typecheck.check_type(comp_repr, pb.Computation)
--> 275       eval_result = await self._evaluate(comp_repr, comp.scope)
    276       py_typecheck.check_type(eval_result, LambdaExecutorValue)
    277       if arg is not None:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\lambda_executor.py in _evaluate(self, comp, scope)
    352           comp,
    353           type_utils.get_function_type(
--> 354               type_serialization.deserialize_type(comp.type))))
    355     elif which_computation == 'lambda':
    356 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\caching_executor.py in create_value(self, value, type_spec)
    240                                  target_future)
    241       self._cache[identifier] = cached_value
--> 242     target_value = await cached_value.target_future
    243     type_utils.check_assignable_from(type_spec, target_value.type_signature)
    244     return cached_value

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\tasks.py in _wakeup(self, future)
    248     def _wakeup(self, future):
    249         try:
--> 250             future.result()
    251         except Exception as exc:
    252             # This may also be a cancellation.

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\tasks.py in _step(***failed resolving arguments***)
    180                 result = coro.send(None)
    181             else:
--> 182                 result = coro.throw(exc)
    183         except StopIteration as exc:
    184             if self._must_cancel:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\concurrent_executor.py in create_value(self, value, type_spec)
     66   async def create_value(self, value, type_spec=None):
     67     return await self._delegate(
---> 68         self._target_executor.create_value(value, type_spec))
     69 
     70   async def create_call(self, comp, arg=None):

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\futures.py in __iter__(self)
    325         if not self.done():
    326             self._asyncio_future_blocking = True
--> 327             yield self  # This tells Task to wait for completion.
    328         assert self.done(), "yield from wasn't used with future"
    329         return self.result()  # May raise too.

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\tasks.py in _wakeup(self, future)
    248     def _wakeup(self, future):
    249         try:
--> 250             future.result()
    251         except Exception as exc:
    252             # This may also be a cancellation.

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\futures.py in result(self)
    241         self._log_traceback = False
    242         if self._exception is not None:
--> 243             raise self._exception
    244         return self._result
    245 

c:\users\XXX\appdata\local\continuum\anaconda3\envs\wz\lib\asyncio\tasks.py in _step(***failed resolving arguments***)
    178                 # We use the `send` method directly, because coroutines
    179                 # don't have `__iter__` and `__next__` methods.
--> 180                 result = coro.send(None)
    181             else:
    182                 result = coro.throw(exc)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\eager_executor.py in create_value(self, value, type_spec)
    369     if not tf.executing_eagerly():
    370       raise RuntimeError('The eager executor may only be used in eager mode.')
--> 371     return EagerValue(value, type_spec, self._device)
    372 
    373   async def create_call(self, comp, arg=None):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\eager_executor.py in __init__(self, value, type_spec, device)
    274       py_typecheck.check_type(type_spec, computation_types.Type)
    275     self._type_signature = type_spec
--> 276     self._value = to_representation_for_type(value, type_spec, device)
    277 
    278   @property

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\eager_executor.py in to_representation_for_type(value, type_spec, device)
    207         computation_impl.ComputationImpl.get_proto(value), type_spec, device)
    208   if isinstance(value, pb.Computation):
--> 209     return embed_tensorflow_computation(value, type_spec, device)
    210   if isinstance(type_spec, computation_types.TensorType):
    211     if not isinstance(value, tf.Tensor):

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_federated\python\core\impl\eager_executor.py in embed_tensorflow_computation(comp, type_spec, device)
     66   if which_computation != 'tensorflow':
     67     raise TypeError('Expected a TensorFlow computation, found {}.'.format(
---> 68         which_computation))
     69 
     70   if isinstance(type_spec, computation_types.FunctionType):

TypeError: Expected a TensorFlow computation, found intrinsic.

**Comment by jkr26** [comment]
Hi @dsudzeng 

Thanks for pinging us on this!

We pushed the capability for the local executor to infer cardinalities from its arguments in August 29 in [this change](https://github.com/tensorflow/federated/commit/7107a4a8d474524341250b15da389614b478b1e8#diff-9a0820f4f746826fab7fd2b2f3612342), and released our last version of TFF (0.8.0) on August 20. This means that any ipython notebook currently at master which does not explicitly set its number of clients will behave as a non-federated executor (and e.g. won't know how to handle intrinsics); basically master is out of sync with the pip package.

If you are running these notebooks against the pip package, you will need to explicitly specify the number of clients in the executor stack. Here, `num_clients` should be 10 if I recall correctly; so if you call `tff.framework.set_default_executor(tff.framework.create_local_executor(10))` instead of `tff.framework.set_default_executor(tff.framework.create_local_executor())` at the top level of this notebook, this discrepancy should be resolved.

Hopefully this should solve this issue!

**Comment by aynesss** [comment]
you must add this lignes in notebook tff.framework.set_default_executor(tff.framework.create_local_executor(10)) tff.framework.set_default_executor(tff.framework.create_local_executor())

But 10 means the total number of clients ? or the fraction of clients C that we have to choose, because as you know, in Federated learning, not all the clients are going to participate in training.
