### ISSUE TITLE
The best version of frameworks that support federated

### ISSUE THREAD

**Issue by Pangeensi** [tensorflow/federated#765]
I want to know that if I use tensorflow federated, which version of python, tensorflow and keras should I use to minimize the weird bugs.

**Comment by ZacharyGarrett** [comment]
Hi @Pangeensi,

There is a [compatibility chart](https://github.com/tensorflow/federated#compatibility) on the https://github.com/tensorflow/federated with versions of Tensorflow (which should include Keras in the `tf.keras` package) and Tensorflow Federated. As for Python versions, we run continuous tests on Python 2.7 (Linux) and Python 3.6 (Linux and MacOS).

I would check out the steps are [Install TensorFlow Federated](https://github.com/tensorflow/federated/blob/master/docs/install.md), which provide a couple different alternatives for installing.

In the future, this type of question maybe better asked at https://stackoverflow.com/questions/tagged/tensorflow-federated. Please continue to create github issues for the weird bugs you encounter, we'd like to fix those.
