### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by phalangee** [tensorflow/federated#766]
Hi! Can `Tensorflow_federated` be installed in` CentOS`?
  I'm trying to install this in remote server and can  only install the software by compiling it,because I can't get the "root" permission.I'm very embarrassed to ask if you have relevant  installation documentation?
  My server system information is :`CentOS Linux release 7.4.1708 (Core)`
Thank you very much

**Comment by jkr26** [comment]
Hi @phalangee,

Can you create a virtualenv and install the TFF pip package there? In general, as long as you have python already installed, you should be able to start [here](https://www.tensorflow.org/federated/install#2_create_a_virtual_environment), install TFF to your interpreter, and run any programs requiring TFF through this interpreter.

Does this work for your setup?

**Comment by phalangee** [comment]
@jkr26  Thank you very much !I just came back from vacation. You are right, I googled how to install conda with non-root permissions. and `conda create -n envname` Then follow the tutorial to install successfully.
Thank you very much

**Comment by jkr26** [comment]
Awesome, happy to help!
