### ISSUE TITLE
Installing TFF in a Disributed Environment

### ISSUE THREAD

**Issue by Tabrizian** [tensorflow/federated#768]
Can `tensorflow/federated` be used in a real distributed environment?

**Comment by ZacharyGarrett** [comment]
At this time TFF supports simulating federated learning environments; components for a central aggregation service and executing computations on a fleet of client devices are not available.

Work is underway to enable multi-machine simulations using GCP/GKE, when this is ready https://github.com/tensorflow/federated/blob/master/docs/tutorials/simulations.ipynb will be updated to demonstrate how to do this.
