### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#779]
currently it is impossible to install through pip or build this package in windows

the core issue is
https://github.com/tensorflow/custom-op/issues/24
which blocks
https://github.com/tensorflow/addons/issues/173
which blocks
various tensorflow-addons windows issues 
which blocks
tensorflow-addons use by the emnist simulation here

the bottom line is that I just want to use tensorflow-federated on windows and I think its windows support should be traced here and perhaps an alternative solution could be provided since I'm not sure anyone is working on the core issue.
(is it possible to avoid or extract tensorflow-addons usage?)

**Comment by jkr26** [comment]
Hi @amitport,

I think we unfortunately are simply unlikely to attempt to add windows support in the near future. There is some nontrivial setup that would have to happen on our side, and it's not currently considered a high priority.

That said, a solution like [virtualbox](https://www.virtualbox.org/) or [docker](https://www.docker.com/) (maybe even [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?) should allow you to run TFF on a Windows machine, though there may be some slightly gnarly edges.

**Comment by amitport** [comment]
Of course I bypassed this issue

but, as I see it, treating windows as a low priority seems like a symptom of low maturity, capacity, and commitment. That's part of the reason why I'm currently just using regular tf and building what I need around it.

**Comment by aWeinzierl** [comment]
> That said, a solution like virtualbox or docker (maybe even Windows Subsystem for Linux?) should allow you to run TFF on a Windows machine, though there may be some slightly gnarly edges.

Is there a way which includes GPU use?

**Comment by amitport** [comment]
resolved for me

**Comment by AshiakerWang** [comment]
> resolved for me

How did you resolve the problem? I have encountered the same issue here. Could you please give me some suggestions?

**Comment by amitport** [comment]
It just worked for on clean penv install today with tensorflow2.1. I didn't do anything on my part.
