### ISSUE TITLE
FileCheckpointManager causes exception on windows

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#780]
Hi,

running FileCheckpointManager using a windows machine will cause an exception at line https://github.com/tensorflow/federated/blob/48d5e4860f3349086d018b9553f730c87def2429/tensorflow_federated/python/research/utils/checkpoint_manager.py#L88 :

`re.error: bad escape \c at position`

this happened because `os.path.join` creates a string that contains `\\ckpt_`

(I bypassed https://github.com/tensorflow/federated/issues/779 by commenting out emnist import, and am using the checkpoint_manager by copy-pasting the code. So I just hardcoded a solution for my project, but it is an issue with that code in this repo)

**Comment by michaelreneer** [comment]
@amitport Can you provide a few pieces of information...
* Python version
* Is `path` == '\\ckpt_'? If not can you provide the full value of `path`?

**Comment by amitport** [comment]
* python 3.6
* path has a prefix but the error happen because how `os.path.join` is adding the default `ckpt`

just run the following on windows to get an exception
```
path = os.path.join(anyPath, 'ckpt')
re.compile(r'{}([0-9]+)$'.format(path)) 
```

**Comment by michaelreneer** [comment]
@amitport Can you provide the value you are using for `anyPath` and what is `path` after you call join?

```python
path = os.path.join(anyPath, 'ckpt')
print(path)
```

Thanks

**Comment by amitport** [comment]
it really does not matter the exception happen on the `\\c`: `re.error: bad escape \c at position`

in any case mine is something like: 'C:\\my_folder'

**Comment by michaelreneer** [comment]
This issue is more subtle than you are making it out to be (or I am confused) and this is why I am asking you for specifics.

This is what we want:
```shell
>>> re.compile(r'c:\\my_folder')
re.compile('c:\\\\my_folder')
```

All the following generate the error you are experiencing:
```shell
>>> re.compile(r'c:\my_path')
...
re.error: bad escape \m at position 2
>>> re.compile('c:\\my_path')
...
re.error: bad escape \m at position 2
>>> re.compile('c:\my_path')
...
re.error: bad escape \m at position 2
```

Therefore I believe that `os.path.join` returning a string that has an escaped slash is correct. Instead I believe the issue is in combining Python raw strings with Python strings.

```shell
>>> re.compile(r'{}'.format(r'c:\\my_path'))
re.compile('c:\\\\my_path')
>>> re.compile(r'{}'.format('c:\\my_path'))
...
re.error: bad escape \m at position 2
```

I believe the solution is something like...
```shell
>>> re.compile(r'{}'.format('c:\\my_path'.encode('unicode-escape').decode()))
re.compile('c:\\\\my_path')
```

Note this is a Python 3 only fix. I'll follow up with a CL after a little more testing.

**Comment by amitport** [comment]
The two lines I quoted in always cause the issue on windows and it's easy to reproduce. I didn't mean that it is easy to solve or that `path.join` directly causes the issue, but having `\\c` in the next line does.

anyway thanks for the effort
