### ISSUE TITLE
Making federated data!

### ISSUE THREAD

**Issue by Krypton3** [tensorflow/federated#786]
Hi,

I have selected a dataset from kaggle which is the "FIFA 19 complete player dataset". I wanted to use this dataset as a federated dataset. However, when I was trying to convert the dataset into a federated one, it seems not working for me. I have imported the dataset as Dataframe. 

Does anyone have any suggestions? How do I make this dataset into federated one as they showed in the tutorial section?

Thanks

**Comment by ZacharyGarrett** [comment]
@Krypton3 questions about _how to use_ TFF are often better addressed at StackOverflow with the [TensorFlow Federated tag](https://stackoverflow.com/questions/tagged/tensorflow-federated).

Perhaps the following questions are similar to yours and the answers might apply?

- [Create a custom federated data set in TensorFlow Federated](https://stackoverflow.com/questions/55434004/create-a-custom-federated-data-set-in-tensorflow-federated)
- [Is there a reasonable way to create tff clients datat sets?](https://stackoverflow.com/questions/58004272/is-there-a-reasonable-way-to-create-tff-clients-datat-sets)

@jpgard is currently working on a tutorial for structured data in #782, it might be good to follow that issue as well.

**Comment by jpgard** [comment]
+1 to @ZacharyGarrett 's comment. @Krypton3 if you do post this on StackOverflow, perhaps you can share a link and I will see if I can answer the question on StackOverflow.

**Comment by Krypton3** [comment]
Thank you. I will post this on StackOverflow and use the proper tag. I am working on federated for a few days and hopefully will do my ms thesis on it. However, I need to solve this issue in which I am stuck right now. 

Thanks

**Comment by jpgard** [comment]
FYI I think this question has been posted on SO here: https://stackoverflow.com/questions/58965488/how-to-create-federated-dataset-from-a-csv-file

**Comment by jkr26** [comment]
Seems like given the activity on SO, this issue can be closed.
