### ISSUE TITLE
Can't find tff research in released version

### ISSUE THREAD

**Issue by str4w** [tensorflow/federated#790]
TFF research does not seem to be present in the released pip build of tff, despite being present in the code at that tag.   Is that intentional?

A file such as the following is present at tag 0.11.0 https://github.com/tensorflow/federated/blob/v0.11.0/tensorflow_federated/python/research/baselines/emnist/run_federated.py

However, if I try to import research (or run the code in the above file line by line) I get the error below.  (I tried this in a colab).

```
import tensorflow_federated as tff
print(tff.__version__)
from tensorflow_federated.python.research import *

0.11.0
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-20193a02f825> in <module>()
      1 import tensorflow_federated as tff
      2 print(tff.__version__)
----> 3 from tensorflow_federated.python.research import *

ModuleNotFoundError: No module named 'tensorflow_federated.python.research'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by ZacharyGarrett** [comment]
Correct, the `research/` directory is not part of the pip package. Code in the `research/` directory is intended for local development and tinkering, and hence is intentionally not part of the pip package.

The official, supported APIs available in the pip package are documented at https://www.tensorflow.org/federated/api_docs/python/tff. All other packages/module imports come without guarantee, they may break in future versions (this includes importing via `tff.python`).
