### ISSUE TITLE
How to implement my own federated algorithm Usinsg tensorflow federated

### ISSUE THREAD

**Issue by MMorafah** [tensorflow/federated#791]
I have read all the documents on the tensorflow federated available at tensorflow.org, but I am not sure how to implement my own federated algorithm. For example, I have a compiled keras model, I know how to convert this to tff.computation. It seems that in order to build a federated algorithm one should build an iterative_process. Can anyone help me in this regard?

Thank you so much,

**Comment by sandeepwww** [comment]
https://colab.research.google.com/github/tensorflow/federated/blob/v0.11.0/docs/tutorials/federated_learning_for_image_classification.ipynb 

I think this should help you.

**Comment by ines321** [comment]
please I have my own dataset and would like to know how this line become :

>`emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data()`

**Comment by ines321** [comment]
I have image dataset of skin cancer, and i must convert my dataset into federated data
can anyone give me an example 
I use 
tff.simulation.clientData
or 
tff.simulation.clientData.create_tf_dataset_for_client()
or
tff.simulation.HDF5ClientData.create_tf_dataset_for_client(client_id)
or
tf.data.Dataset.from_tensor_slices()

**Comment by jkr26** [comment]
Hi @ines321!

Unsure if you reposted this on StackOverflow, but it seems like [perhaps this](https://stackoverflow.com/questions/59741397/federated-learning-convert-my-own-image-dataset-into-tff-simulation-clientdata) is a good pointer here.

**Comment by michaelreneer** [comment]
Please feel free to reopen this issue if the link provided by @jkr26 does not help.
