### ISSUE TITLE
Text generation colab notebook throws error on keras evaluation

### ISSUE THREAD

**Issue by r-o-s-h-a-n** [tensorflow/federated#795]
Hello! I am running the Text generation colab notebook in Python 3 runtime with no hardware acceleration. Without making any modification to the notebook and simply running all cells, the notebook throws an error in the "Fine-tune the model with Federated Learning" section on line 21 where it calls the keras_evaluate function. 

https://colab.research.google.com/github/tensorflow/federated/blob/v0.11.0/docs/tutorials/federated_learning_for_text_generation.ipynb#scrollTo=vm_-PU8OFXpY

I have encountered a similar issue with my own work. I think tf keras, unlike TFF, does not accept preprocessed datasets where elements are OrderedDicts. The situation is fixed by switching the preprocess function to take a tuple as instead of an OrderedDict.

Full error is given below: 

Evaluating before training round 0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-6e9921caacc8> in <module>()
     19 
     20 for round_num in range(NUM_ROUNDS):
---> 21   keras_evaluate(state, round_num)
     22   # N.B. The TFF runtime is currently fairly slow,
     23   # expect this to get significantly faster in future releases.

2 frames
<ipython-input-21-6e9921caacc8> in keras_evaluate(state, round_num)
     15   tff.learning.assign_weights_to_keras_model(keras_model, state.model)
     16   print('Evaluating before training round', round_num)
---> 17   keras_model.evaluate(example_dataset, steps=2)
     18 
     19 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v1.py in evaluate(self, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing)
    883     self._check_call_args('evaluate')
    884 
--> 885     func = self._select_training_loop(x)
    886     return func.evaluate(
    887         self,

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v1.py in _select_training_loop(self, inputs)
    563 
    564     # Experiment training loop with default DS path.
--> 565     if context.executing_eagerly() and self._experimental_run_tf_function:
    566       if self._in_multi_worker_mode():
    567         return training_distributed.DistributionMultiWorkerTrainingLoop(

AttributeError: 'Sequential' object has no attribute '_experimental_run_tf_function'

**Comment by ZacharyGarrett** [comment]
Hi @r-o-s-h-a-n we just released version `v0.12.0`. The new version of the colab tutorial is [here](https://colab.research.google.com/github/tensorflow/federated/blob/v0.12.0/docs/tutorials/federated_learning_for_text_generation.ipynb). Our tests indicate this notebook does not raise errors, could you retry there and see if this issue still occurs?

**Comment by r-o-s-h-a-n** [comment]
Hi @ZacharyGarrett , the notebook works now. Thanks!
