### ISSUE TITLE
 RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by cianohagan** [tensorflow/federated#805]
I have been receiving an issue while working through the TFF image classification tutorial (https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification) when invoking the initialize computation to construct the server state. 

RuntimeError                              Traceback (most recent call last)
<ipython-input-18-0c0dcd96a774> in <module>
----> 1 state = iterative_process.initialize()

/anaconda3/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py in __call__(self, *args, **kwargs)
    590     context = self._context_stack.current
    591     arg = pack_args(self._type_signature.parameter, args, kwargs, context)
--> 592     return context.invoke(self, arg)
    593 
    594 

/anaconda3/lib/python3.6/site-packages/retrying.py in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

/anaconda3/lib/python3.6/site-packages/retrying.py in call(self, fn, *args, **kwargs)
    204 
    205             if not self.should_reject(attempt):
--> 206                 return attempt.get(self._wrap_exception)
    207 
    208             delay_since_first_attempt_ms = int(round(time.time() * 1000)) - start_time

/anaconda3/lib/python3.6/site-packages/retrying.py in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

/anaconda3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/anaconda3/lib/python3.6/site-packages/retrying.py in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

/anaconda3/lib/python3.6/site-packages/tensorflow_federated/python/core/impl/execution_context.py in invoke(self, comp, arg)
    186             _ingest(executor, unwrapped_arg, arg.type_signature))
    187       return asyncio.get_event_loop().run_until_complete(
--> 188           _invoke(executor, comp, arg))

/anaconda3/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    469         future.add_done_callback(_run_until_complete_cb)
    470         try:
--> 471             self.run_forever()
    472         except:
    473             if new_task and future.done() and not future.cancelled():

/anaconda3/lib/python3.6/asyncio/base_events.py in run_forever(self)
    423         self._check_closed()
    424         if self.is_running():
--> 425             raise RuntimeError('This event loop is already running')
    426         if events._get_running_loop() is not None:
    427             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by ZacharyGarrett** [comment]
@cianohagan could you provide details on where this is running?

- colab.research.google.com or Jupyter?
- Version of TFF being run?
- Version of Python?

**Comment by skeydan** [comment]
Hi, I just got the same error, for that same code and as well, for this snippet from the algorithms 1 notebook:

```
@tff.federated_computation(tff.FederatedType(tf.float32, tff.CLIENTS))
def get_average_temperature(sensor_readings):
  return tff.federated_mean(sensor_readings)

get_average_temperature([68.5, 70.3, 69.8])
```

I'm running on my local machine, with versions:

Python: 3.7.6
TF: 2.1
TFF: 0.12

Please let me know if there's anything else that could help. Many thanks!

Oops - forgot about the Jupyter question and now I tested, it **does in fact occur in Jupyter only, but not interactively in the Python interpreter!**

:-)

**Comment by ZacharyGarrett** [comment]
If this is happening in Jupyter, could you see the instructions in the tutorial README? The section [Running the TFF Tutorials in Jupyter Notebooks](https://github.com/tensorflow/federated/blob/master/docs/tutorials/README.md#running-the-tff-tutorials-in-jupyter-notebooks) discusses how to install `nest_asyncio` (which is required only when running within Jupyter).

**Comment by skeydan** [comment]
Wonderful, - works! 

Many thanks for the quick resolution!

**Comment by cianohagan** [comment]
@ZacharyGarrett Thanks for that. I didn't see the instructions in the README about Jupyter. The code now works without any errors.
