### ISSUE TITLE
Links to tutorials must be updated on website

### ISSUE THREAD

**Issue by tzapzoor** [tensorflow/federated#806]
Hi,

It seems the links to the tutorials that appear on the website must be updated. [This](https://www.tensorflow.org/federated/tutorials/custom_federated_algorithms_2) tutorial for example, doesn't point to the right colab or github link.

Thanks.

**Comment by michaelreneer** [comment]
@tzapzoor thanks for pointing this out.  We published out documentation before we tagged the release. Sorry about that. You can use that [notebook](https://colab.sandbox.google.com/github/tensorflow/federated/blob/master/docs/tutorials/custom_federated_algorithms_2.ipynb) at `master`. I'll close this issue after I push the release and those links work again.

**Comment by michaelreneer** [comment]
@tzapzoor the tutorial that you linked should now work. Sorry for the inconvenience.
