### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by AshiakerWang** [tensorflow/federated#808]
The following error occurred while  running (https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/gans/experiments/emnist/classifier/measure_misclassification_of_users.py):

**AttributeError: module 'tensorflow' has no attribute 'contrib'**

There exists a similar issue #224 , but it's actually different from mine
since I have installed  TensorFlow 1.14.0 which is a version under  2.0.
![image](https://user-images.githubusercontent.com/14258909/77029801-aed06700-69d7-11ea-9dd8-47c1903118f1.png)

Could you please give me some suggestions?

**Comment by michaelreneer** [comment]
Hi @AshiakerWang, it looks like you are using an old version of the TensorFlow Federated package and if you have TensorFlow 1.14.0 then you are also using an old version of the TensorFlow package. Can you update to the latest version of those packages and see if that fixes your issue.

```
pip install --upgrade tensorflow-federated
```

**Comment by AshiakerWang** [comment]
thank you so much! I will try it.
