### ISSUE TITLE
How to aggregate only part of client model weights?

### ISSUE THREAD

**Issue by huangmingkai** [tensorflow/federated#809]
Not sure if I should ask here again. I encounted similar issue as https://stackoverflow.com/questions/60501245/can-i-broadcast-different-models-for-each-of-the-clients-in-federated-tensorflow, but seems no one answered it. Wondering if tff supports aggregating only part of client model weights? I mean the client model contains two parts, and one part needs to aggregate, the other part needs to keep locally. Thanks!

**Comment by cramertj** [comment]
There isn't anything available yet for this that is plug-and-play-- it's possible to do by creating your own `IterativeProcess` and calling `tff.federated_aggregate`/`tff.federated_collect` manually. There are, however, some internal research examples that do this that we're looking to open-source soon. Stay tuned for those, otherwise feel free to ask questions if you decide to use `IterativeProcess` and hit any issues!

**Comment by huangmingkai** [comment]
Thanks!
I have implemented this by transfering weights deltas to python environment by tff.federated_collect, the patch is
[optimizer_utils.txt](https://github.com/tensorflow/federated/files/4455248/optimizer_utils.txt)
Do you think this implementation is suitable?
The following issue is that performance is lowered by about 10X after using tff.federated_collect. Do you have any advice?
The version of tensorflow_federated I used is 0.12.0 and 10 clients are used.
Thanks again!

**Comment by cramertj** [comment]
You're in luck! `federate_collect` had a severe performance issue on the simulation stack, and I have a patch locally that fixes it. I'll try to have it in some time this week-- thanks for your patience!

If you're curious, it boils down to the `EagerTFExecutor::create_value` call with values of `SequenceType` calling into [`make_dataset_from_elements`](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/core/impl/utils/tensorflow_utils.py#L928) and then [this numpy call](https://github.com/tensorflow/federated/blob/eb57cca1666670cf167a5468c761cd3724fe4a8f/tensorflow_federated/python/core/impl/utils/tensorflow_utils.py#L902) which can take a *long* time. I believe we can replace that call in this case with a more efficient type conversion, but I'll update back here once I have a finished patch.

**Comment by cramertj** [comment]
I've just landed https://github.com/tensorflow/federated/commit/c7f90f11ca17224cdf130206dbd0736f9a8a7318 which gives me massive speedup on some cases of `federated_collect`. It'll be available in the next release. Let me know when you have a chance to try it and if it helps you!

**Comment by huangmingkai** [comment]
It works and I also get massive speedup! Thanks for your great help!

**Comment by cramertj** [comment]
Woooo!!! :)
