### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_federated.python.research'

### ISSUE THREAD

**Issue by AshiakerWang** [tensorflow/federated#814]
The following error occurred while running "https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/gans/experiments/emnist/run_experiments.py" (I am attempting to regenerate the results of the [paper](https://arxiv.org/abs/1911.06679)):

`ModuleNotFoundError: No module named 'tensorflow_federated.python.research'`

1. Here is the full list of my anaconda environment information:
![Screenshot from 2020-03-23 21-05-17](https://user-images.githubusercontent.com/14258909/77319901-97340e00-6d4a-11ea-96d2-af819ebfb1ef.png)

2. and I am using Pycharm in Ubuntu 16.04:
![Screenshot from 2020-03-23 21-04-13](https://user-images.githubusercontent.com/14258909/77320002-bf237180-6d4a-11ea-914e-17ae59594c36.png)

3. Last but not least, I have tried to execute the code in the terminal but the error continued to exist, so I'm afraid that the problem is  not concerned with the Pycharm IDE.
![Screenshot from 2020-03-23 21-11-35](https://user-images.githubusercontent.com/14258909/77320343-5a1c4b80-6d4b-11ea-90be-ccd68fe51245.png)

It will be appreciated if you could give me some suggestions.

**Comment by ZacharyGarrett** [comment]
I believe the research under `tensorflow_federated/python/research/gans/` requires using [bazel](https://bazel.build/) to build and run, similar to the rest of TensorFlow Federated. It likely won't work to run the python script directly.

@saugenst can you confirm? If this is the case, could we update the directory's [README.md](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/gans/README.md) to explicitly state this requirement, and provide some example commandlines?

**Comment by AshiakerWang** [comment]
@ZacharyGarrett Thank you for your response very much, and I have installed bazel now. However, while running
 `bazel run \ tensorflow_federated/python/research/gans/experiments/emnist:run_experiments` 
I have encountered some other troubles.
![Screenshot from 2020-03-24 11-54-25](https://user-images.githubusercontent.com/14258909/77386693-5ed21580-6dc6-11ea-87d7-3450c014c3ed.png)
As can be seen, I have tried to create a WORKSPACE using `touch WORKSPACE`, but I don't konw what to do in the next step since I am not familiar with bazel.
Could you please give me some more advices?

**Comment by ZacharyGarrett** [comment]
Could you try re-running the command _inside_ the folder where the cloned TensorFlow Federated repo is? TensorFlow Federated comes with a [`WORKSPACE`](https://github.com/tensorflow/federated/blob/master/WORKSPACE) file that should do everything needed.

```shell
git clone https://github.com/tensorflow/federated.git ${DESTINATION}
cd ${DESTINATION}
bazel run ...
```


Possibly the instructions for [Build the TensorFlow Federated pip package](https://github.com/tensorflow/federated/blob/master/docs/install.md#build-the-tensorflow-federated-pip-package), but skipping the last steps (stop after step 5), will help get the environment working.

**Comment by AshiakerWang** [comment]
The problem was solved based on your suggestions. Thanks a lot!
