### ISSUE TITLE
Two issues when I tried to reimplement the result training emnist using adam

### ISSUE THREAD

**Issue by slowbull** [tensorflow/federated#817]
The command line is as follows, where I follow the value in Table 10 of paper "https://arxiv.org/pdf/2003.00295.pdf": 
bazel run emnist:run_federated -- --total_rounds=1500 --client_optimizer=sgd --client_learning_rate=0.001 --server_optimizer=adam --server_learning_rate=1.0 --clients_per_round=10 --client_epochs_per_round=1 --experiment_name=emnist_fedadam_experiment --root_output_dir=/export/tmp/fed_opt/

Two issues:
1) the program breaks down after 70 iterations.  Error: "/home/.cache/bazel/_bazel_hzy/0133413982e33a0797f543bd111e9efb/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/emnist/run_federated.run
files/org_tensorflow_federated/tensorflow_federated/python/simulation/hdf5_client_data.py", line 71, in create_tf_dataset_for_client                                                                        
    tf_dataset = self._create_dataset(client_id) "/home/cache/bazel/_bazel_hzy/0133413982e33a0797f543bd111e9efb/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/emnist/run_federated.run
files/org_tensorflow_federated/tensorflow_federated/python/simulation/hdf5_client_data.py", line 64, in _create_dataset                                                                                     
    self._h5_file[HDF5ClientData._EXAMPLES_GROUP][client_id].items())))                                                                                                                                     
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                                                                                                     
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                                                                                                     
  File "/home/anaconda3/envs/PY3/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__                                                                                               
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)                                                                                                                                                 
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                                                                                                     
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                                                                                                     
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open                                                                                                                                                           
KeyError: 'Unable to open object (bad symbol table node signature)'                                                                                                                                         
"
**Does it mean that there are problems with the data?**

2) **The loss does not converge. The acc is still 0.04137931 after 70 rounds. Are there any other params I need to change?**  (It converges when I change client_learning_rate=0.01, server_learning_rate=0.01. ) But how can I reimplement the result in the paper?

**Comment by ZacharyGarrett** [comment]
1. Could you please post the contents of `pip freeze`? What version fo `tensorflow_federated` and `h5py` are installed?

2. @zcharles8 to confirm: I believe the Adam experiments may need higher `epsilon` values, though they might already be the default?

**Comment by zcharles8** [comment]
The Adam optimizer argument uses the Keras defaults unless otherwise specified. @slowbull I would recommend using the flag "--server_adam_epsilon=0.1" to re-obtain the results from our paper.

**Comment by zcharles8** [comment]
Using the same parameters but with the epsilon value set to 0.1, I am observing a consistently decreasing loss function. I would also caution against using FedAdam for EMNIST. On the character recognition task, it was the slowest to reach its peak accuracy, and for the autoencoder task, it consistently got stuck or diverged. FedYogi and FedAvgM were generally the best optimizers for EMNIST.

**Comment by slowbull** [comment]
> 1. Could you please post the contents of `pip freeze`? What version fo `tensorflow_federated` and `h5py` are installed?
tensorflow-federated==0.13.1, 
h5py==2.8.0                     
This problem is not observed every run. But it may occur sometimes.                                                                                                                                                                  
> 2. @zcharles8 to confirm: I believe the Adam experiments may need higher `epsilon` values, though they might already be the default?
@zcharles8  Thanks, epsilon=0.1 should do the trick. I will try yogi also.

**Comment by ZacharyGarrett** [comment]
@slowbull Thanks for the information!

Could you possibly try adding a try/except context to see if there is a specific client id that is failing?

Maybe something like this:
```python
try:
  datasets = []
  for client_id in sample(client_data.client_ids):
    datasets.append(client_data.create_tf_dataset_for_client(client_id))
except KeyError as e:
  logging.exception('Failed to create dataset for client_id %s', client_id)
  raise e
```

**Comment by slowbull** [comment]
> Using the same parameters but with the epsilon value set to 0.1, I am observing a consistently decreasing loss function. I would also caution against using FedAdam for EMNIST. On the character recognition task, it was the slowest to reach its peak accuracy, and for the autoencoder task, it consistently got stuck or diverged. FedYogi and FedAvgM were generally the best optimizers for EMNIST.

@zcharles8 I tried to use Yogi: 
bazel run emnist:run_federated -- --total_rounds=500 --client_optimizer=sgd --client_learning_rate=0.001 --server_optimizer=yogi --server_learning_rate=3.
162 --clients_per_round=10 --client_epochs_per_round=1 --experiment_name=emnist_fedyogi_experiment_n3_p1f2 --root_output_dir=/export/UserData/tmp/fed_opt/ --server_yogi_initial_accumulator_value=8.178
732e-6
The learning rates are from Table 10 in the paper, client_learning_rate=10^-3,  server_learning_rate=10^0.5 \approx 3.162, and server_yogi_initial_accumulator_value=8.178
732e-6 is computed from emnist/compute_yogi_init.py. The loss does not converge either in this setting. Any hint?


> @slowbull Thanks for the information!
> 
> Could you possibly try adding a try/except context to see if there is a specific client id that is failing?
> 
> Maybe something like this:
> 
> ```python
> try:
>   datasets = []
>   for client_id in sample(client_data.client_ids):
>     datasets.append(client_data.create_tf_dataset_for_client(client_id))
> except KeyError as e:
>   logging.exception('Failed to create dataset for client_id %s', client_id)
>   raise e
> ```

@ZacharyGarrett  It looks like this issue disappears if there is only one process/experiment running on one machine. I will keep you informed when the error pops up.

**Comment by ZacharyGarrett** [comment]
@slowbull Ah, thanks for the additional information. It looks like h5py may not support concurrent access to the same file based on the code comment [here](https://github.com/h5py/h5py/blob/4589052eaa6aa8fec612bb2b73c11006e7ead20f/examples/multiprocessing_example.py#L17).

We may want to look into alternative file formats for the datatasets...

**Comment by zcharles8** [comment]
@slowbull For all of our adaptive optimizers, we used an epsilon value of 0.1. I believe this was noted in the paper. We should probably emphasize it in the repository too, as it seems to be critical to reaching a good minima.

For FedYogi, we actually took the extra step of optimizing the initial accumulator value based on the average norm of the gradients (across a small number of samples). While this is the recommended way to set it, a simpler option is to set it to 0. This will also help.

**Comment by zcharles8** [comment]
We may want to make this information more explicit in our documentation. Thanks for trying it out! It's good to be reminded of what information should be exposed more formally.

**Comment by slowbull** [comment]
@zcharles8   Are you referring to this sentence "For the adaptive optimizers, we fix the numerical stability constant \varepsilon to be 0.01" ? Thank you very much.

**Comment by zcharles8** [comment]
Yes, sorry, it was set to 0.01 in all experiments. I went back through the experiment output data to be certain.
