### ISSUE TITLE
Issue when running stackoverflow_lr

### ISSUE THREAD

**Issue by slowbull** [tensorflow/federated#820]
When I tried to run the experiment of stackoverflow_lr:

> bazel run stackoverflow_lr:run_federated -- --total_rounds=1500 --client_optimizer=sgd --client_learning_rate=0.5 --server_optimizer=adagrad --server_learning_rate=10 --clients_per_round=10 --client_batch_size=100 --client_epochs_per_round=10 --experiment_name=stackoverflow_fedadagrad_experiment_05_10 --root_output_dir=/export/UserData/hzy/tmp/fed_opt/ --server_adagrad_initial_accumulator_value=0.1 --server_adagrad_epsilon=0.01

I have the following issue: 

> Traceback (most recent call last):                                                                                                                                                                          
>   File "/home/hzy/.cache/bazel/_bazel_hzy/86f4822ac0d3e01f42858069fe654bbe/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_fed
> erated.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_federated.py", line 125, in <module>                                                        
>     app.run(main)                                                                                                                                                                                           
>   File "/home/hzy/anaconda3/envs/PY3/lib/python3.6/site-packages/absl/app.py", line 299, in run                                                                                                             
>     _run_main(main, args)                                                                                                                                                                                   
>   File "/home/hzy/anaconda3/envs/PY3/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main                                                                                                       
>     sys.exit(main(argv))                                                                                                                                                                                    
>   File "/home/hzy/.cache/bazel/_bazel_hzy/86f4822ac0d3e01f42858069fe654bbe/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_fed
> erated.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_federated.py", line 75, in main                                                             
>     num_validation_examples=FLAGS.num_validation_examples)                                                                                                                                                  
>   File "/home/hzy/.cache/bazel/_bazel_hzy/86f4822ac0d3e01f42858069fe654bbe/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_fed
> erated.runfiles/org_tensorflow_federated/tensorflow_federated/python/research/optimization/stackoverflow_lr/dataset.py", line 117, in get_stackoverflow_datasets                                            
>     stackoverflow_train, _, stackoverflow_test = tff.simulation.datasets.stackoverflow.load_data(                                                                                                           
>   File "/home/hzy/.cache/bazel/_bazel_hzy/86f4822ac0d3e01f42858069fe654bbe/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_fed
> erated.runfiles/org_tensorflow_federated/tensorflow_federated/python/simulation/datasets/stackoverflow.py", line 109, in load_data                                                                          
>     os.path.join(dir_path, 'stackoverflow_train.h5'))                                                                                                                                                       
>   File "/home/hzy/.cache/bazel/_bazel_hzy/86f4822ac0d3e01f42858069fe654bbe/execroot/org_tensorflow_federated/bazel-out/k8-opt/bin/tensorflow_federated/python/research/optimization/stackoverflow_lr/run_fed
> erated.runfiles/org_tensorflow_federated/tensorflow_federated/python/simulation/hdf5_client_data.py", line 50, in __init__                                                                                  
>     self._h5_file = h5py.File(self._filepath, "r")                                                                                                                                                          
>   File "/home/hzy/anaconda3/envs/PY3/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__                                                                                                  
>     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)                                                                                                                                             
>   File "/home/hzy/anaconda3/envs/PY3/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid                                                                                                  
>     fid = h5f.open(name, flags, fapl=fapl)                                                                                                                                                                  
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                                                                                                     
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                                                                                                     
>   File "h5py/h5f.pyx", line 78, in h5py.h5f.open                                                                                                                                                            
> OSError: Unable to open file (unable to open file: name = '/home/hzy/.keras/stackoverflow_train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)                        
> 

tf version: 2.1.0 
tff version: 0.13.1 

Is this a bug caused by tf and tff mismatch @ZacharyGarrett ?
I solved this issue by changing this line: https://github.com/tensorflow/federated/blob/d145e66ebb113423a3c921621e1b11957642ad24/tensorflow_federated/python/research/optimization/stackoverflow_lr/dataset.py#L53 to: words = tf.strings.split(tf.strings.substr(sentence, 0, MAX_SEQ_LEN), sep=' ')
and https://github.com/tensorflow/federated/blob/d145e66ebb113423a3c921621e1b11957642ad24/tensorflow_federated/python/research/optimization/stackoverflow_lr/dataset.py#L59 to: tags = tf.strings.split(tags, sep='|')

**Comment by ZacharyGarrett** [comment]
Those versions of TFF and TF should be compatible.

@zcharles8 @jkr26 have written a lot of the code in this directory, they might have ideas?

**Comment by jkr26** [comment]
@zcharles8 just pushed [this change](https://github.com/tensorflow/federated/commit/22c89fac4aa9e92e591a7de43e705773215986b2), which should have fixed this problem. @slowbull, could you ocnfirm?

**Comment by zcharles8** [comment]
Hi @slowbull, just wanted to ping this thread again. I've since attempted to make sure that using the code internally and externally produced the same results, and things look good as far as I can tell. Have your issues been resolved?

**Comment by slowbull** [comment]
Sorry for the late reply. It works.  @jkr26 @zcharles8
