### ISSUE TITLE
bulid tensorflow federated failed

### ISSUE THREAD

**Issue by whyseu** [tensorflow/federated#822]
I follow the instrctons in the "https://tensorflow.google.cn/federated/install".
(1)Install TensorFlow Federated using pip: When I run the command "python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"" , there is a SyntaxError: invalid syntax os
(2)Using Docker: When I run the command "docker build . --tag tensorflow_federated", it always fails.
These two errors are shown in the shapshot.
<img width="771" alt="78322895-a0bb4280-75a2-11ea-9886-20e256eae28c" src="https://user-images.githubusercontent.com/35478590/78515225-9ccc3200-77e7-11ea-9b0e-f27345033443.png">

**Comment by ZacharyGarrett** [comment]
@whyseu could you. please include which version of `tensorflow` and `tesnorflow_federated` pip packages are installed (found via `pip freeze`) and the version of python (found via `python --version`).

**Comment by whyseu** [comment]
tensorflow 2.1.0; tesnorflow_federated 0.13.1; python 3.5.2

**Comment by ZacharyGarrett** [comment]
The error is occurring on a literal string interpolation ([PEP 498](https://www.python.org/dev/peps/pep-0498/)) which was introduced in Python 3.6.

It seems like the TFF pip package maybe too lenient in declaring acceptable python versions.

Are you able to use a newer version of Python?

**Comment by michaelreneer** [comment]
This should not be an issue with Python 3.6 and greater. The latest tensorflow_federated package on PyPI is not annotated correctly to express the fact that it is dependent on Python 3.6 and greater. This will be fixe in the next release.
