### ISSUE TITLE
Gradient quantization/sparsification

### ISSUE THREAD

**Issue by jczestochowska** [tensorflow/federated#824]
Hi! I would like to perform federated learning with gradient quantization/sparsification, I am looking for a way to implement that using tensorflow federated, I know we can utilize `tff.learning.build_federated_sgd_process` but is there a way to modify each client's gradients before sending them to the central node? Thanks for any guidance and help in that matter.

**Comment by jkr26** [comment]
@PraChetit I think has the most knowledge about this, assigning.

**Comment by jczestochowska** [comment]
Many thanks!

**Comment by PraChetit** [comment]
_[apologies for my late response...]_

Yes, there is! Have a look at [Model and update compression](https://github.com/tensorflow/federated/blob/master/docs/tff_for_research.md#model-and-update-compression) section in the tff_for_research doc. The simple example there should get you started.

You can implement the `EncodingStageInterface` using standard TF, and pass them into the [`tff.learning.build_federated_averaging_process`](https://www.tensorflow.org/federated/api_docs/python/tff/learning/build_federated_averaging_process)

More broadly, this depends on the [`tensor_encoding API`](https://github.com/tensorflow/model-optimization/tree/master/tensorflow_model_optimization/python/core/internal/tensor_encoding), which is "quietly" open-sourced, and we are now working on getting it fully documented and "graduating" it to a fully supported status.

If you have trouble getting something compression related done, please tag me with more details, I should be able to help.

**Comment by jczestochowska** [comment]
Thank you for pointing me to the right place in the project! My current trouble is that if we wanted to change the code and run our experiments it would be most convenient to build research and utilise it as an external dependency, I don't know however how to proceed with that? Could you also give me some advice on how to proceed with that? Thank you in advance for any help in that matter

**Comment by jczestochowska** [comment]
sorry I wasn't aware that this is not a correct place to ask questions, I will close the issue and move my question to stackoverflow.
