### ISSUE TITLE
Documentaiton: optimization bazel

### ISSUE THREAD

**Issue by matech96** [tensorflow/federated#831]
On this markdown file [https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/optimization/README.md](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/optimization/README.md)
there is the following command: `pip install bazel`.

I haven't found a bazel pip package.

**Comment by zcharles8** [comment]
Thanks for the careful reading! Your assessment is correct. We have updated the documentation regarding Bazel installation. Hope that helps!
