### ISSUE TITLE
User-level DP with emnist and stackoverflow not running!

### ISSUE THREAD

**Issue by PhungLai728** [tensorflow/federated#837]
I'd like to reproduce the results of User-level DP in the Learning Differentially Private Recurrent Language Models paper [H. Brendan McMahan et al. ICLR 2018]. But the Reddit dataset is not publicly available. So I try with emnist and stackoverflow that are provided in the implementation.

But I am not able to run the model with these datasets. (I am using the latest version tff 0.13.1 &	tensorflow 2.1.0).
1. With stackoverflow, I try to run with `bazel run //tensorflow_federated/..../stackoverflow:run_federated`. But after downloading the data, it stucks there for a while, then it shows an error `RuntimeError: generator raised StopIteration`. 
+ I am not sure how to make it run. Could you please help?
+ How can I adapt the code with other datasets and models (not dataset provided in the code) ? Is there a function to preprocess the data so that we obtain the same format with dataset in `simulation` ?

2. With emnist, I try to run directly with Python, and it 'seems to work'. But when it runs to `training_loop`, when it called `py_typecheck`, it raises an error `TypeError: Expected anonymous_tuple.AnonymousTuple, found tensorflow_federated.python.common_libs.anonymous_tuple.AnonymousTuple.`
+ How can I pass this error? 

3. I searched around and found this github `https://github.com/TalwalkarLab/leaf`. Is the Reddit data here as same as Reddit data used in the [H. Brendan McMahan et al. ICLR 2018] ? 

Thanks!

**Comment by nightldj** [comment]
Could you try the following for EMNIST/Stackoverflow for sanity check?

bazel run run_federated -- --clients_per_round 2 --uniform_weighting --noise_multiplier 0.1  --total_rounds 2 --client_optimizer sgd --client_learning_rate 0.1 --server_optimizer sgd --server_learning_rate 1.0 --root_output_dir /tmp/dp-opt/emnist --experiment_name debug

**Comment by PhungLai728** [comment]
I am able to make it run. Thanks.
