### ISSUE TITLE
Make research/ a normal Python package

### ISSUE THREAD

**Issue by jvmncs** [tensorflow/federated#841]
**Is your feature request related to a problem? Please describe.**
If I'm starting a new project, say `tff_project`, and I want this library to depend on code in `tensorflow_federated/python/research/`, my options are limited.

**Describe the solution you'd like**
Make `tensorflow_federated/python/research` into it's own Python package, installable with setuptools/pip. This can be driven by Bazel (like TFF itself), but the end result should be that I can use `from tensorfloe_federated.python.research import utils` (or similar) in `tff_project` without resorting to any of the workarounds described below.

**Describe alternatives you've considered**
1. Keep `tff_project` in the `research/` directory and set it up to work with bazel via a BUILD file. This seems like the intended workflow, but requires that I do all my work in a fork of TFF, which is unfortunate.
3. Clone TFF and add my own Python installation boilerplate. This solves the problem most directly, but should not need to be done by every new (external) project depending on `research/` code.
4. Clone TFF and add whichever `research/` submodules I want to use to `sys.path` in `tff_project` scripts. Scripts in `research/` that reference other `research/` code as a module will have broken imports. Although these can be changed manually, this is not ideal if I want others to eventually be able to reproduce my code without going through the same process.
2. Use Bazel for `tff_project`, either including TFF as a git submodule or configuring Bazel's WORKSPACE to include the `research/` repo. Also unfortunate -- as a researcher, I probably don't have experience with Bazel, and the overhead of learning it for managing research code seems excessive.
5. Copy code over from the `research/` directory into `tff_project`. For projects lasting months or more, the code quickly becomes out of sync, and I'm effectively barred from pulling in upstream changes.
6. It's also possible I've missed an existing alternative. If that's the case, it should be documented somewhere obvious, e.g. in the [TFF for Research](https://github.com/tensorflow/federated/blob/master/docs/tff_for_research.md) doc.

**Comment by michaelreneer** [comment]
@jvmncs **Can you be more specific about what API you want to use in `research/utils` package?** In the past we have "upstreamed" API from research into the TFF package. Where depends on the API in question. I think we don't want a solution that adds everything from research to TFF, but it is very likely that individual API should be upstreamed.

**Comment by jvmncs** [comment]
Yep, sorry about that. This request comes from trying to experiment with the utilities in the `optimization/shared` subdirectory. Many of those APIs would be useful imo, in particular `fed_avg_schedule`.

I was originally thinking this could be a separate package from main TFF; something like a `tff-addons-nightly` package with no stability guarantees. Perhaps this is best left as a community project though.

**Comment by michaelreneer** [comment]
I could see a couple of paths forward.

1. Open a feature request to upstream a smaller set of the research API that you want to use. We can use that feature request to discuss and coordinate. If this is something we want to support, we would appreciate contributions!

1. As you suggest, you or the community could own this.

1. You could open up a feature request describing what a `tff-addons-nightly` might look like. I've made the argument in the past that our research utilities should be published in a separate package. There is some overlap between `research/utils` and `optimization/shared`.

I think any of these are equally possible. The last is the hardest. The first option could be a win-win I think. WDYT?

**Comment by jkr26** [comment]
+@zcharles8 who wrote `fed_avg_schedule`, for visibility.

**Comment by jvmncs** [comment]
>I think any of these are equally possible. The last is the hardest. The first option could be a win-win I think. WDYT?

Option 3 would be what I had in mind originally, although I understand it could be a low priority for the moment.

FWIW I've just ended up copying code over to a different repo, which worked okay for my purposes. Right now, it's not a high enough priority for me to open a PR for upstreaming or to maintain a package like this on my own, but I can circle back to it in the future.  Maybe someone else who's interested will stumble on this issue and volunteer.

**Comment by michaelreneer** [comment]
I see. I'll assign this issue to myself, I read it differently at first. I think this issue is a good place to track how we handled shared research code.

**Comment by amitport** [comment]
@michaelreneer 
Any updates on this? the 'research' folder is just getting more and more useful.

Besides the 'utils' folder, the other folders also serve as good starting points for which I would like to be able to track changes and possibly contribute back to

A very easy solution that would work is just to move those to another root level folder outside of `tensorflow_federated` folder. (for example, move it to root 'tensorflow_fedrated_research' and update the imports accordingly)

This would allow me to just clone the repo (possibly as a git submodule, or with a local link) and work locally only on this research folder without having to build anything that I don't want or need. This also does not require any publishing so it is fairly clear that maintenance is not guaranteed.

**Comment by amitport** [comment]
If anyone is interested, I'm using the following script (hack) to just copy the research folder locally from time to time. (and replace the local imports):

https://gist.github.com/amitport/1bc57bb0c039f2e3f98f1c2095d28352

**Comment by amitport** [comment]
(note that the examples folder has the same issue: internal reference use imports like `from tensorflow_federated.python.examples.stateful_clients import stateful_fedavg_tf`)

**Comment by michaelreneer** [comment]
@amitport I think this is intentional the examples folder is written as if it were built on top of TFF as opposed to part of TFF. Can you explain what you would expect here?

**Comment by amitport** [comment]
well, it less critical than the research folder that has many utils. In any case, it would be to just copy the folder and have everything work locally without having to rewrite imports or build tff locally.

**Comment by michaelreneer** [comment]
Ah, in this case the intention is to depend on the latest released Python package not the source. This might not be clear. You shouldn't need to rewrite the imports or depend on anything in examples?

In my eyes we should have instructions for creating a venv, installing TFF and run example? I think we are missing documentation maybe?

**Comment by amitport** [comment]
For me at least, the documention was Ok. It's just that there are imports that are a little annoying (but workable):

https://github.com/tensorflow/federated/blob/56783d7f22a67937d44bb4aadf1a45dc57222502/tensorflow_federated/python/examples/stateful_clients/emnist_fedavg_main.py#L27

**Comment by michaelreneer** [comment]
The research directory has been moved to https://github.com/google-research/federated. It should be easy enough to pull in as a submodule now.

**Comment by amitport** [comment]
@michaelreneer there's nothing there though, I guess there is an intention to move the folder there soon?

**Comment by hongliny** [comment]
The directory https://github.com/google-research/federated is effectively empty. I guess it is happening shortly?

**Comment by michaelreneer** [comment]
@hongliny sorry about that there was a delay in the tooling that was migrating the source. It should be there now https://github.com/google-research/federated
