### ISSUE TITLE
Which components add to a federated model to achieve DP protection ?

### ISSUE THREAD

**Issue by PhungLai728** [tensorflow/federated#843]
I know that  to achieve DP, we need to clip gradients, aggregate gradients, and add noise. But, I am not sure how to add DP components (i.e., user-level DP as in `https://arxiv.org/abs/1710.06963`) from `tff/different_privacy` or `tf-privacy` into a a normal federated model (for example the text generation in the tutorial) in order to achieve privacy protection. 
Any suggestion? Thanks!

**Comment by ZacharyGarrett** [comment]
@kairouzp @galenmandrew, who work at the intersection of TFF and TFPrivacy, perhaps could provide some pointers?

**Comment by galenmandrew** [comment]
Hi Phung, I believe we were in correspondence via email, right? And I pointed you to the following code for enabling DP for federated training: https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/research/differential_privacy/stackoverflow/run_federated.py
Specifically the lines that add DP are 148-159. Does that answer your question?

**Comment by PhungLai728** [comment]
Hi Galen, 
Yes, I am. Thanks for your response.
To make DP, I added line 148-159, and 173-176 to the normal federated code.
I wonder whether DP components need different data format or sth like that in order to make it run. I was following the data format of stackoverflow/sharespeare to create train and test data. It works with a normal federated code, but it does not work with DP. I got the following error: `TypeError: Unsupported mapping type dict. Use collections.OrderedDict for mappings.`
Do you have any suggestion ? Thanks.

**Comment by PhungLai728** [comment]
I am able to make the DP model work with customized models and data. Thanks!

**Comment by dshahrokhian** [comment]
Would you kindly update the reference code? The link is broken for the present master branch.
