### ISSUE TITLE
protobuf issues: computation_pb2 and protobuf version issues

### ISSUE THREAD

**Issue by anupamme** [tensorflow/federated#844]
**Describe the bug**

1. I installed protobuf (protoc) on ubuntu and compiled computation.proto file which created computation_pb2.py. The location of computation_pb2.py file is same as computation.proto file which is tensorflow_federated/proto/v0

2. when I run this command:

from tensorflow_federated.python.core.api.computations import federated_computation

I get this error and trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/federated/tensorflow_federated/__init__.py", line 21, in <module>
    from tensorflow_federated.python.core.api.computation_base import Computation
  File "/home/ubuntu/federated/tensorflow_federated/python/core/__init__.py", line 17, in <module>
    from tensorflow_federated.python.core.api.computation_base import Computation
  File "/home/ubuntu/federated/tensorflow_federated/python/core/api/__init__.py", line 25, in <module>
    from tensorflow_federated.python.core.api.computations import federated_computation
  File "/home/ubuntu/federated/tensorflow_federated/python/core/api/computations.py", line 17, in <module>
    from tensorflow_federated.python.core.impl.wrappers import computation_wrapper_instances
  File "/home/ubuntu/federated/tensorflow_federated/python/core/impl/wrappers/computation_wrapper_instances.py", line 18, in <module>
    from tensorflow_federated.python.core.impl import computation_impl
  File "/home/ubuntu/federated/tensorflow_federated/python/core/impl/computation_impl.py", line 17, in <module>
    from tensorflow_federated.proto.v0 import computation_pb2 as pb
  File "/home/ubuntu/federated/tensorflow_federated/proto/v0/computation_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

Just to note, I followed the install instructions and tff is installed correctly as I can run this command successfully:

python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
* Python package versions (e.g., TensorFlow Federated, TensorFlow): tensorflow==2.1.0, tensorflow-federated==0.13.1
* Python version: 3.6.9
* Bazel version (if building from source): 3.1.0
* CUDA/cuDNN version: Not using (CPU machine only)
* What TensorFlow Federated execution stack are you using? I am running code under research repository so I am not sure how to answer this.

**Expected behavior**
Since proto file was compiled into .py file Import should just work

**Additional context**
protoc version: libprotoc 3.11.4
computation_pb2.py is present in the dir tensorflow_federated/proto/v0/
I manually compiled .proto file using protoc but it was not mentioned in the install readme. 
Perhaps there is some version mismatch with protobuf.

**Comment by ZacharyGarrett** [comment]
Thanks for the report. Sounds like there maybe some holes in the documentation.

It will help debugging if we can break up Steps 1 and 2 into the full set of commands that others can copy to reproduce locally. A few questions:

In **Step 1**: Does "compiled computation.proto" means directly invoking the `protoc` compiler on `tensorflow_federated/proto/v0/computation.proto`, or does it mean building the proto using `bazel build tensorflow_federated/proto/v0/:executor_py_pb2`?

In **Step 2**: Where is the command run (python interpreter shell, python script, jupyter notebook)? If the later two, are they creating using bazel build rules? What is the current working directory?

**Side question**: could you help us understand the intent for directly interacting with the protocol buffer message definition? In general TFF treats that as an internal implementation detail. Understanding the use case can better inform the API design.

**Comment by anupamme** [comment]
Hello,

In Step 1: Does "compiled computation.proto" means directly invoking the protoc compiler on tensorflow_federated/proto/v0/computation.proto, or does it mean building the proto using bazel build tensorflow_federated/proto/v0/:executor_py_pb2?

Ans: I used protoc compiler directly.

In Step 2: Where is the command run (python interpreter shell, python script, jupyter notebook)? If the later two, are they creating using bazel build rules? What is the current working directory?

Ans: I am using python interpreter shell. Current working directory is federated root directory.

Side question: could you help us understand the intent for directly interacting with the protocol buffer message definition? In general TFF treats that as an internal implementation detail. Understanding the use case can better inform the API design.

Ans: I was trying to run the code under python/research/target_attack/attacked_fedavg.py and there is this import command which fails:

from tensorflow_federated.python.research.targeted_attack.aggregate_fn import build_stateless_mean

I digged further on why it fails and that lead me to interact with protocol buffer. So API design is okay, I dont have a need to interact with protocol buffer.

**Comment by ZacharyGarrett** [comment]
Hmm, and think there maybe a few pieces being conflated here.

Running from an interpreter in the root directory of the repo can cause issues. This will cause Python to searching for `tensorflow_federated` in the directory with the same name in the repo. If the code is expecting to import the pip package (which I believe the targeted_attack code is) this will fail. This is likely why its complaining that the proto message import is missing, normally this file is created during the bazel build.

TFF generally requires using bazel to build/run the Python scripts, rather than calling the Python interpreter on the scripts directly (this may work some times, but is unsupported). Bazel creates an environment where all the necessary imports are available.

What commandline was used to run the code under `python/research/target_attack/attacked_fedavg.py`?

**Comment by anupamme** [comment]
I was trying to bypass bazel build - was not clear to me that it is required.

I tried running attacked_fedavg_test.py (again not clear to me how to run the files in the research repository)

root directory: federated/

python3 tensorflow_federated/python/research/target_attack/attacked_fedavg_test.py

I ran into import issue: 
 computation_pb2 file is not found for the proto file.

That led me to search how to compile protobuf files and I ended up using protoc to do that. However, doing this lead to some probably protobuf version issue.

I am following the installation guide more methodically (using bazel). Will update the issue shortly.

**Comment by anupamme** [comment]
I used bazel to build (all 10 steps ran okay).

However not clear to me how can I run the code in research repo:

tensorflow_federated/python/research/target_attack/attacked_fedavg_test.py

**Comment by ZacharyGarrett** [comment]
Thanks for the follow-up. Sounds like the TFF documentation could be better to more explicitly call out that bazel is required, perhaps both in the getting started and perhaps in the README.md inside the `research/` directory.

To run the test, could you try:

```shell
bazel test tensorflow_federated/python/research/target_attack:attacked_fedavg_test
```

If may simply only print whether it "passed" or "failed". To get more info, add the flag [`--test_output=all`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_output)

**Comment by anupamme** [comment]
when I run the command

bazel test tensorflow_federated/python/research/target_attack:attacked_fedavg_test

I get following error:

ERROR: Skipping 'tensorflow_federated/python/research/target_attack:attacked_fedavg_test': no such package 'tensorflow_federated/python/research/target_attack': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/ubuntu/federated/tensorflow_federated/python/research/target_attack
ERROR: no such package 'tensorflow_federated/python/research/target_attack': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

Questions:

1. Do I need to add build files in order to run the code under research folder?

2. If yes, is this similar to the BUILD file in the home directory?

**Comment by anupamme** [comment]
I am able to run the test case. There was a typo in the name.

Closing the issue.
