### ISSUE TITLE
publish pypi pack with tensorflow 2.2 and numpy 1.18 deps

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#845]
please? are there known issues installing those lib versions?

thank you!

**Comment by michaelreneer** [comment]
OK so we are using version now that satisfy this issue. We still need to do a release however.

**Comment by jkr26** [comment]
Current plan is to begin a release on Monday--assuming everything goes smoothly, we will have on out soon. Our builds are pretty green right now, so I'm assuming few hiccups here.

**Comment by jkr26** [comment]
We just released [TFF 0.14.0](https://github.com/tensorflow/federated/releases/tag/0.14.0), which is compatible with TF 2.2 and NP 1.18. Thanks!
