### ISSUE TITLE
Possible bug in cifar100 data loading module

### ISSUE THREAD

**Issue by Saipraneet** [tensorflow/federated#846]
https://github.com/tensorflow/federated/blob/269e70d9a0ecc5b73f38cab7403aae9676dbc9e2/tensorflow_federated/python/research/optimization/cifar100/dataset.py#L37

Given that 'crop_shape' is set as
`crop_shape = CIFAR_SHAPE = (32, 32, 3)`

The references line seems to crop the image to shape [32, 3] instead of [32, 32]. Perhaps the code should instead be

`image, target_height=crop_shape[0], target_width=crop_shape[1]) `

**Comment by zcharles8** [comment]
Hi Praneeth! Thanks for the close investigation. Further down, you can see that the batch size is put at the beginning of the train image shape: 

https://github.com/tensorflow/federated/blob/269e70d9a0ecc5b73f38cab7403aae9676dbc9e2/tensorflow_federated/python/research/optimization/cifar100/dataset.py#L77-L82

We also have some tests that make sure we have the right crop size: https://github.com/tensorflow/federated/blob/269e70d9a0ecc5b73f38cab7403aae9676dbc9e2/tensorflow_federated/python/research/optimization/cifar100/dataset_test.py#L38-L46

We appreciate extra eyes on this code, so please let us know if you do think there's any other issues.
