### ISSUE TITLE
Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by meijuanwang** [tensorflow/federated#850]
Hi,
  A problem appeared when I use TFF run this code:
  tff.federated_computation(lambda: 'Hello, World!')()
 The error  "Cannot run the event loop while another loop is running"
I used Jupyter notebook, the version of tensorflow_federated is 0.13.1

**Comment by jvmncs** [comment]
Have a look at this one: #842

**Comment by michaelreneer** [comment]
Also you can take a look at https://github.com/tensorflow/federated/blob/master/docs/tutorials/README.md

**Comment by morningD** [comment]
You can downgrade tornado to 4.5.3 to solve this problem. 
`pip install tornado==4.5.3`
more information: https://github.com/jupyter/notebook/issues/3397

**Comment by harshp77** [comment]
> Worked For Me
