### ISSUE TITLE
How to get accumulated privacy budget ?

### ISSUE THREAD

**Issue by PhungLai728** [tensorflow/federated#852]
Hi there, 
I follow the code (`https://github.com/tensorflow/federated/blob/978bc860a7e686ffd652d3e775cd702fc485d1a0/tensorflow_federated/python/research/differential_privacy/stackoverflow/run_federated.py`) to perform DP in language models. 

I am not sure how to get value of accumulated privacy budget after training (last line 
`print M.get privacy spent()` in Algorithm 1 in `https://arxiv.org/pdf/1710.06963.pdf`). Could you please guide me with this ?

Thanks

**Comment by ZacharyGarrett** [comment]
@galenmandrew may be able to provide the best guidance.

**Comment by galenmandrew** [comment]
You can use the tools here to compute RDP or GDP privacy spent:

https://github.com/tensorflow/privacy/tree/master/tensorflow_privacy/privacy/analysis
