### ISSUE TITLE
A problem of evaluation

### ISSUE THREAD

**Issue by meijuanwang** [tensorflow/federated#854]
I'd like to use my own model and dataset to try TFF, when evaluating ,it taks a long time and I can't see the result. Is there any log file or something I can track the problem?
My dataset is the smart information of hard-drive.

![image](https://user-images.githubusercontent.com/65224044/82646930-f8dc0000-9c47-11ea-8dfa-842c71bfeeee.png)

**Comment by jkr26** [comment]
It seems to me that this question might be best suited on StackOverflow, as it seems more like a usage question than a bug report or feature request. Would you mind posting there and tagging with tensorflow-federated?

**Comment by meijuanwang** [comment]
I have solved this problem.  When I run my code  by using " python   ***.py" ,it's ok
