### ISSUE TITLE
tf_computation returns garbage when used with `**` operator

### ISSUE THREAD

**Issue by amitport** [tensorflow/federated#860]
**Describe the bug**
```python
@tff.tf_computation(tf.int32) # or tf.float32
def pow10(n):
    return n ** 10

pow10(10) # returns garbage (different wrong values)
```
The code above does not throw any error, but quietly returns garbage
(even if `**` is not supported, it should throw an error)

**Environment (please complete the following information):**
* OS Platform and Distribution: windows 10
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
tensorflow@2.2 tff@0.14
* Python version: 3.7

**Comment by PraChetit** [comment]
This seems to be integer overflow unrelated to TFF -- using `tf.int64` works as I would expect in this case.

**Comment by amitport** [comment]
🤦 sorry
