### ISSUE TITLE
Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by imrankhan441** [tensorflow/federated#861]
python 3.7.7
all are the latest upgrade

when I try to run

```
import collections
import numpy as np
import tensorflow as tf
import tensorflow_federated as tff

tf.compat.v1.enable_v2_behavior()

np.random.seed(0)

tff.federated_computation(lambda: 'Hello, World!')()
```

RuntimeError: Cannot run the event loop while another loop is running

And I try this. then second-line not running

```
import nest_asyncio
nest_asyncio.apply()
tff.federated_computation(lambda: 'Hello, World!')()
Out[4]: b'Hello, World!'
```

then this line not working or not printing
`print("hello")`
no output it's just stack

![problem1](https://user-images.githubusercontent.com/26671669/83523238-b2b65480-a503-11ea-9641-3c8f279cc0a3.png)

**Comment by gokulanv** [comment]
Were you able to fix this?

**Comment by gokulanv** [comment]
My error logs:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-9c097e9baec9> in <module>
----> 1 tff.federated_computation(lambda: 'hi')()

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\tensorflow_federated\python\core\impl\utils\function_utils.py in __call__(self, *args, **kwargs)
    562     context = self._context_stack.current
    563     arg = pack_args(self._type_signature.parameter, args, kwargs, context)
--> 564     return context.invoke(self, arg)
    565 
    566 

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\retrying.py in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    204 
    205             if not self.should_reject(attempt):
--> 206                 return attempt.get(self._wrap_exception)
    207 
    208             delay_since_first_attempt_ms = int(round(time.time() * 1000)) - start_time

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\retrying.py in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\retrying.py in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\site-packages\tensorflow_federated\python\core\impl\executors\execution_context.py in invoke(self, comp, arg)
    202         return event_loop.run_until_complete(
    203             tracing.wrap_coroutine_in_current_trace_context(
--> 204                 _invoke(executor, comp, arg)))

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\asyncio\base_events.py in run_until_complete(self, future)
    469         future.add_done_callback(_run_until_complete_cb)
    470         try:
--> 471             self.run_forever()
    472         except:
    473             if new_task and future.done() and not future.cancelled():

~\AppData\Local\Continuum\anaconda3\envs\tflocal\lib\asyncio\base_events.py in run_forever(self)
    426         if events._get_running_loop() is not None:
    427             raise RuntimeError(
--> 428                 'Cannot run the event loop while another loop is running')
    429         self._set_coroutine_wrapper(self._debug)
    430         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running`

**Comment by gokulanv** [comment]
This can be fixed by using nest_asyncio.
If you face kernel freezing error, try downgrading the jupyter notebook and tornado version.

Default versions of notebook >= 6.x and tornado >= 6.0

By running the command,

`pip install jupyter notebook==5.7.8 tornado==4.5.0`

This issue is fixed

**Comment by imrankhan441** [comment]
Install old version of notebook and tornado is not a proper solution developer need fix this issue as well as.

**Comment by michaelreneer** [comment]
@imrankhan441 More detailed information on the issue can be found in our documentation [here](https://github.com/tensorflow/federated/blob/master/docs/tutorials/README.md#running-the-tff-tutorials-in-jupyter-notebooks). In short this is not an issue with TFF, but rather a feature of Jupyter.  Alternatively you could run your notebooks using https://colab.research.google.com/.
