### ISSUE TITLE
How to install and deploy tensorflow federated on multiple devices?

### ISSUE THREAD

**Issue by chinatzsj** [tensorflow/federated#864]
I'm trying to install and deploy tensorflow federated on multiple machines and treat them as different parties, who interact with each other without expose their data.

But the current document seems to merely support installing on a local machine.

So I am wondering whether the goal can be achieved?

**Comment by krzys-ostrowski** [comment]
Assuming that I understand the specifics of your scenario, we don't have a ready-to-use setup for it that I could point you to, but if you want to experiment with creating your own, the easiest way to go would be to base what you want on the GCP/GKE setup outlined in this tutorial:

https://github.com/tensorflow/federated/blob/master/docs/tutorials/high_performance_simulation_with_kubernetes.ipynb

The workers would be running on the "different parties". The main difference is that you wouldn't be pushing the datasets from the server to those workers, as the GKE tutorial does, but rather, you'd incorporate the tf.data.Dataset logic into the client-side computations (perhaps via custom TF op that accesses client-side data, by accessing it at a standardized location on workers, etc.).

Unfortunately, we don't have a tutorial for it, but it shouldn't be too hard.
