### ISSUE TITLE
Script aborts due to ModuleNotFoundError

### ISSUE THREAD

**Issue by jaintj95** [tensorflow/federated#867]
**Describe the bug**
I am trying to execute the `run_federated.py` script but it throws the following error  
  
    
    Traceback (most recent call last):
        File "run_federated.py", line 24, in <module>
            from tensorflow_federated.python.research.differential_privacy import dp_utils
    ModuleNotFoundError: No module named 'tensorflow_federated.python.research'

This is strange because I have a conda environment with all modules installed. Then why I am getting import errors? 

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
* Python package versions (e.g., TensorFlow Federated, TensorFlow): TF federated 0.14.0
* Python version: 3.7.7

**Comment by jkr26** [comment]
Hi @jaintj95 

Research is not included in the pip package--to run those scripts, you will need to build TFF from source--instructions are included [here](https://github.com/tensorflow/federated/blob/master/docs/install.md#build-the-tensorflow-federated-pip-package).

**Comment by michaelreneer** [comment]
I am going to go ahead and close this @jaintj95 please feel free to reopen if @jkr26 explanation did not solve your issue.
