### ISSUE TITLE
ERROR: No matching distribution found for tensorflow-addons~=0.9.1 (from tensorflow_federated)

### ISSUE THREAD

**Issue by munhyunsu** [tensorflow/federated#872]
**Describe the bug**
- pip install tensorflow_federated occur error 'ERROR: No matching distribution found for tensorflow-addons~=0.9.1 (from tensorflow_federated)'

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 19.3
* Python package versions (e.g., TensorFlow Federated, TensorFlow): Tensorflow Federated 0.14.0, Tensorflow 2.2.0
* Python version: Python 3.8.3
* Bazel version (if building from source): NA
* CUDA/cuDNN version: NA
* What TensorFlow Federated execution stack are you using?
absl-py==0.9.0
astunparse==1.6.3
cachetools==4.1.0
certifi==2020.6.20
chardet==3.0.4
gast==0.3.3
google-auth==1.18.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.9
Keras-Preprocessing==1.1.2
Markdown==3.2.2
numpy==1.19.0
oauthlib==3.1.0
opt-einsum==3.2.1
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1

**Expected behavior**
1. Create new virtual environment using Python 3.8
```bash
python3 -m venv venv
source venv/bin/activate
```
2. pip install tensorflow_federated
```bash
pip3 install --upgrade pip
pip3 install tensorflow_federated
```
3. Error!
```bash
ERROR: Could not find a version that satisfies the requirement tensorflow-addons~=0.9.1 (from tensorflow_federated->-r tff-app/requirements.txt (line 4)) (from versions: 0.10.0)
ERROR: No matching distribution found for tensorflow-addons~=0.9.1 (from tensorflow_federated->-r tff-app/requirements.txt (line 4))
```

**Additional context**

**Comment by michaelreneer** [comment]
Hi @munhyunsu 

Can you run this command in your virtual environment and share the output.

`pip install tensorflow-addons~=0.9.1`

Note that this should [succeed](https://pypi.org/project/tensorflow-addons/#history), but I expect it to fail in your environment for some reason. My guess is that you have `tensorflow-addons` installed in your system or user level site-packages. If that is the case you can use the `--ignore-installed` flag on the `pip` command to install the older version in your virtual environment.

**Comment by munhyunsu** [comment]
Hi @michaelreneer 

I run this command,
`pip3 install tensorflow-addons~=0.9.1` or `pip install --ignore-installed tensorflow-addons~=0.9.1`.
It produce same error that 
```bash
ERROR: Could not find a version that satisfies the requirement tensorflow-addons~=0.9.1 (from versions: 0.10.0)
ERROR: No matching distribution found for tensorflow-addons~=0.9.1
```

I guess it's a problem with Python 3.8.
The [tensorflow-addons Github](https://github.com/tensorflow/addons) states that the 0.9.1 version supports only Python 3.7 and the 0.10.0 version supports Python 3.8.
If I install only tensorflow-addons without tensorflow_federated in Python 3.8, `pip3 install tensorflow-addons` succeeds.
However, `pip3 install tensorflow-addons~=0.9.1` fails.

**Comment by michaelreneer** [comment]
Hi @munhyunsu

That makes sense. It seems like the set of TFF requirements as it currently stands is not compatible with Python 3.8. It also appears that if we update to the latest version of `tensorflow-addons` then TFF would not be compatible with versions of Python less than 3.8.

You could work around this issue by constructing your virtual environment with Python 3.7?

**Comment by munhyunsu** [comment]
Hi @michaelreneer 

Of course it is possible with 3.7. :D

I just tried it because I wanted to try out the latest features of Python 3.8 in my code.
I'll later change to Python 3.8 if the dependency changes to a version that supports `tensorflow-addons` used by `tensorflow_federated`.
Thanks for the help.
I didn't open `setup.py` and immediately installed it with `pip3`, so I didn't know that Python 3.8 is not supported yet.

PS. But, if this happens, shouldn't it be marked somewhere that Python 3.8 doesn't support TFF yet? I think someone has the same problem as me.
For example, write down the Python version in the TFF-TF version mapping table in the README.
Like a tensorflow-addons README!

Thanks again!
