### ISSUE TITLE
Does TFF support windows10 system?

### ISSUE THREAD

**Issue by XiaotianJia** [tensorflow/federated#874]
Hi,
I installed tensorflow-federated on windows10, and run [this](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/examples/remote_executor_example.py) tutorial. But I got the error of `module 'tensorflow_federated' has no attribute 'framework'`.

Python package versions are:
`python=3.6
tensorflow=1.3.1
tensorflow-federated=0.3.0
`
Is it because the OS is wrong? Whether TFF supports win10? Thanks.

**Comment by roselander** [comment]
The current release of TFF is 0.14.0. Please update `tensorflow-federated` and try again.

**Comment by michaelreneer** [comment]
Closing this issue, I believe that @roselander suggestion should fix.
