### ISSUE TITLE
Failing test related to encoding_utils

### ISSUE THREAD

**Issue by jvmncs** [tensorflow/federated#876]
**Describe the bug**
Test related to `tff.learning.framework.encoding_utils` fails on master.  The exact test is `test_broadcast_from_model`, which is specifically testing the factory function `tff.learning.framework.encoding_utils.build_encoded_broadcast_from_model`. I've pasted the error message & traceback below.

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X 10.15
* Python package versions (e.g., TensorFlow Federated, TensorFlow): TFF master @ 259af6a3307ad01af27417cd1b910216e7c2b84c; `tf-nightly==2.3.0.dev20200625`
* Python version: 3.7
* Bazel version (if building from source): 0.26.1

Full list of TF dependencies:
```
tb-nightly==2.3.0a20200702
tensorboard-plugin-wit==1.7.0
tensorflow-model-optimization==0.3.0
tensorflow-privacy==0.3.0
tf-estimator-nightly==2.4.0.dev2020070201
tf-nightly==2.3.0.dev20200625
tfa-nightly==0.11.0.dev20200630231055
```

**Expected behavior**
Tests should pass.

**Additional context**
```
======================================================================
FAIL: test_broadcast_from_model (__main__.EncodingUtilsTest)
test_broadcast_from_model (__main__.EncodingUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jasonmancuso/d42bb2c3e756badbc3917bcb81e95d65/sandbox/darwin-sandbox/543/execroot/org_tensorflow_federated/bazel-out/darwin-opt/bin/tensorflow_federated/python/learning/framework/encoding_utils_test.runfiles/org_tensorflow_federated/tensorflow_federated/python/learning/framework/encoding_utils_test.py", line 74, in test_broadcast_from_model
    self.assertLen(w, 2)
  File "/Users/jasonmancuso/tff-aggregations/venv/lib/python3.7/site-packages/absl/testing/absltest.py", line 866, in assertLen
    container_repr, len(container), expected_len), msg)
  File "/Users/jasonmancuso/tff-aggregations/venv/lib/python3.7/site-packages/absl/testing/absltest.py", line 1704, in fail
    return super(TestCase, self).fail(self._formatMessage(prefix, msg))
AssertionError: [<warnings.WarningMessage object at 0x13baba650>, <warnings.WarningMessage object at 0x13bd687d0>, <warnings.WarningMessage object at 0x13bc912d0>, <warnings.WarningMessage object at 0x13be524d0>] has length of 4, expected 2.

----------------------------------------------------------------------
```

**Comment by jvmncs** [comment]
I just noticed this message from tf-addons:

```
UserWarning: You are currently using a nightly version of TensorFlow (2.3.0-dev20200625).
TensorFlow Addons offers no support for the nightly versions of TensorFlow. Some things might work, some other might not.
If you encounter a bug, do not file an issue on GitHub.
```

If this is not an issue that should be reported here, please feel free to close without response.

**Comment by PraChetit** [comment]
This is surely a good issue to post here, don't worry, and this functionality should work.

I was not able to reproduce it now, but I noticed this target was briefly broken around the time matching your tf-nightly build date. I'll assume this is a transient bug due to an unlucky cut, please update the tf-nightly package and reopen if it is not fixed.
