### ISSUE TITLE
Failed to build the TensorFlow Federated pip package 

### ISSUE THREAD

**Issue by hongliny** [tensorflow/federated#878]
**Describe the bug**
Failed to install TFF from build by following the tutorials of `https://github.com/tensorflow/federated/blob/master/docs/install.md`.

The step 5 `pip install --requirement "requirements.txt"` will install `tf-nightly`, whereas step 9 `pip install --upgrade "/tmp/tensorflow_federated/tensorflow_federated-"*".whl"` will install `tensorflow-2.2.0`. This leads to a version conflict error while executing step 10 :
```
python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"
```
while leads to (Note that the error itself is not relevant but is due to version conflict) 
```
module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```

I tried to uninstall `tensorflow` package afterwards but the dependency is still broken
```
AttributeError: module 'tensorflow' has no attribute 'function'
```

**Environment (please complete the following information):**
* OS Platform and Distribution: Linux Debian 9 from GCP `common-cpu` package
* Python package versions: N/A
* Python version: 3.7.6
* Bazel version: 3.3.1
* CUDA/cuDNN version: N/A
* What TensorFlow Federated execution stack are you using? N/A

**Expected behavior**
Can `import tensorflow_federated` after installation

**Comment by michaelreneer** [comment]
@hongliny Can you try skipping steps 4-6 in that doc. I think the issue is that after step 6 you would need to deactivate the current virtualenv, but honestly these steps are not really helpful so I'd simply skip them.
