### ISSUE TITLE
Docs of traced functions link to wrong source code location

### ISSUE THREAD

**Issue by jvmncs** [tensorflow/federated#881]
**Describe the bug**
Traced methods/functions have broken links to source code on tensorflow.org/federated/api_docs. For example, in [this method](https://www.tensorflow.org/federated/api_docs/python/tff/framework/EagerTFExecutor#create_call), clicking the `View Source` button redirects me to a [wrapper function](url) `async_trace` local to the `tracing.trace` decorator. The same is true of all other traced functions I tried this with.

**Expected behavior**
I would expect the above to direct me to [this place](https://github.com/tensorflow/federated/blob/v0.15.0/tensorflow_federated/python/core/impl/executors/eager_tf_executor.py#L467-L497) in the GH source code

**Comment by michaelreneer** [comment]
I am working on a fix for this.
