### ISSUE TITLE
Empty TFF runtime docker image when running dockerized TFF on GCP

### ISSUE THREAD

**Issue by jingtaow** [tensorflow/federated#882]
**Describe the bug**

I tried to set up a TFF Docker runtime on GCP by following instructions on the official TFF website ( https://www.tensorflow.org/federated/gcp_setup ) . I encountered an error when running the TFF runtime container via the following command:

$ docker run \
    --detach \
    --name=runtime \
    --publish=8000:8000 \
    gcr.io/tensorflow-federated/runtime

The error message is: 

Unable to find image 'gcr.io/tensorflow-federated/runtime:latest' locally docker: Error response from daemon: manifest for gcr.io/tensorflow-federated/runtime:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/tensorflow-federated/runtime/manifests/latest".

Additional diagnose:

  It seems that the docker daemon reported this error because the URL appeared in the official document, i.e. gcr.io/tensorflow-federated/runtime is redirecting to pantheon.corp.google.com/gcr/images/tensorflow-federated/GLOBAL/runtime?gcrImageListsize=30  and it is an empty GCP storage bucket at this moment. 

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): "Container-Optimized" boot image provided by GCP
* Python package versions (e.g., TensorFlow Federated, TensorFlow): N/A
* Python version: N/A
* Bazel version (if building from source): N/A
* CUDA/cuDNN version: N/A
* What TensorFlow Federated execution stack are you using?
TensorFlow Federated runtime container suggested on the official TFF website ( https://www.tensorflow.org/federated/gcp_setup )

**Expected behavior**

docker run command should end without error, with TFF runtime container up and rumming.

**Additional context**
N/A

**Comment by jlewi** [comment]
Doesn't look like the image: gcr.io/tensorflow-federated/runtime:latest' exists.

@jingtaow For public GCR registries you can enter the URL in a browser to browse the contents of the registry.
