### ISSUE TITLE
How does IterativeProcess.next work?

### ISSUE THREAD

**Issue by sharare90** [tensorflow/federated#883]
I went through the Federated Learning tutorial. I was wondering how .next function work when we call it on an iterative process.
Assuming that we have a train data which is a list of lists. The outer list is a list of clients and the inner lists are batches of data for each client. Then, we create an iterative process, for example, a federated averaging process and we initialize the state. 
What exactly happens when we call IterativeProcess.next on this training data. Does it take from these data randomly in each round? Or just take data from each client one batch at a time?

Assume that I have a list of tf.data.Datasets each representing a client data. How can I add some randomness to sampling from this list for the next iteration of federated learning?

My datasets are not necessarily the same length. When one of them is completely iterated over, does this dataset waits for all other datasets to completely iterate over their data or not?

**Comment by ZacharyGarrett** [comment]
Generally we use GitHub Issues for bugs and feature requests, this is more of a question about how to use or description of the system. Would you mind moving this question to StackOverflow https://stackoverflow.com/questions/tagged/tensorflow-federated?

This will preserve the question and answer for the community to find in the future (whereas closed GitHub issues can be less discoverable).
