### ISSUE TITLE
asyncio loop error in Google Colab

### ISSUE THREAD

**Issue by timdhondt1** [tensorflow/federated#884]
So as of today I've been getting the following asyncio error when running in Google Colab:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-a23308ec3f7c> in <module>()
      7 np.random.seed(0)
      8 
----> 9 tff.federated_computation(lambda: 'Hello, World!')()

8 frames
/usr/lib/python3.6/asyncio/base_events.py in run_forever(self)
    426         if events._get_running_loop() is not None:
    427             raise RuntimeError(
--> 428                 'Cannot run the event loop while another loop is running')
    429         self._set_coroutine_wrapper(self._debug)
    430         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running
```

It suddenly showed up in a project which has been working fine before. 
When running the tutorial `Federated_Learning_for_Image_Classification.ipynb` notebook, it also shows up in the first 'Hello world' federated test computation. I tried several types of runtimes and factory reset of the runtime. 

Since it can easily be replicated; anyone have an idea why this suddenly shows up?

**Comment by ZacharyGarrett** [comment]
Colab has recently updated their runtime to use a new version of various dependencies, including tornado. This has hopefully been fixed in `master` as of #1f9daf6

Does this still occur when visiting https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb

**Comment by timdhondt1** [comment]
This new notebook w/ the asyncio patch seems to work! 
Might want to change the 'run in colab' link at https://www.tensorflow.org/federated/tutorials/federated_learning_for_image_classification cause it still directs to the v0.15.0 notebook without the patch.

Thanks anyway!

**Comment by ZacharyGarrett** [comment]
Thanks for confirming. Yup, we'll look at updating the tensorflow.org links.

**Comment by michaelreneer** [comment]
Please check out v0.16.0, or master in GitHub. Also the published tutorials should be pointing at master now.

**Comment by dennymarcels** [comment]
I compared the execution time with both nest_asyncio and by downgrading tornado. The first solution impacts performance - it seems asyncio is not being used at all. The second doesn't.
