### ISSUE TITLE
Mandatory installation of tensorflow-cpu 1.15.3 when installing tensorflow_federated 0.2.0

### ISSUE THREAD

**Issue by wang19950602** [tensorflow/federated#886]
I'm trying to install tensorflow_federated 0.2.0 on my PC using the command pip install tensorflow_federated==0.2.0. But after the installation, my python starts using a newly added tensorflow-cpu 1.15.3 instead of the tensorflow-gpu 1.13.1 I installed before, it seems that the tensorflow-cpu 1.15.3 is installed during the installation of tensorflow_federated 0.2.0. Is there any method that can avoid the installation of tensorflow-cpu during the installation of tensorflow_federated? I'm using ubuntu 18.04.
![1](https://user-images.githubusercontent.com/32090473/89012524-f29f8980-d344-11ea-8622-0a12801f3170.png)

**Comment by michaelreneer** [comment]
Is there a reason you are trying to use an old version of TFF?

Here is the [pip reference](https://pip.pypa.io/en/stable/reference/), you can ignore dependencies with the `--no-dependencies` flag.
