### ISSUE TITLE
research/targeted_attack: emnist targeted attack doesnt run

### ISSUE THREAD

**Issue by DanielNolte** [tensorflow/federated#890]
**Describe the bug**
A clear and concise description of what the bug is. It is often helpful to
provide a link to a [colab](https://colab.research.google.com/) notebook that
reproduces the bug.

After cloning TensorFlow/federated and attempting to run emnist_with_targeted_attack, I get the following error:

TypeError: Expected tensorflow_federated.python.common_libs.structure.Struct or tensorflow_federated.python.learning.model_utils.ModelWeights, found tensorflow.python.autograph.impl.api.ModelWeights.

The issue is caused by the following line in the evaluate method:
tff.learning.assign_weights_to_keras_model(keras_model, state.model)

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
tf: 2.2.0
tff: 0.16.1
* Python version:
Python: 3.7.6
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**

I expected the example code to run without errors, and return the test metrics when the evaluate method is called.

**Additional context**

Let me know if you need any additional information, or if I am doing something wrong.
Thank you in advance.

**Comment by jkr26** [comment]
I'll take a look internally--thanks for the report!

**Comment by DanielNolte** [comment]
Thank you

Yesterday I was not using Bazel to run the code, so that might be where the problem was coming from. I saw in other posts that Bazel is normally required for building and running the research code.

But I attempted to build emnist_with_targeted_attack with Bazel 3.3.1 using the following command:

bazel build //tensorflow_federated/python/research/targeted_attack:emnist_with_targeted_attack

I get the following error: 
ERROR: An error occurred during the fetch of repository 'local_config_python':
Python Configuration Error: Invalid python library path:

I have given the correct path to the folder containing the python.exe. I am confused as to what is wrong. Please let me know if I am doing something wrong or if you need additional information. It could just be a Bazel configuration issue that I need to work out. I am just trying to build and run the examples in the research folder. Are there any instructions for using Windows to build and run the research examples? I greatly appreciate your help. If I need to switch to a Linux OS I can try to do that as well.

**Comment by jkr26** [comment]
You are for sure correct that there is a bug here--there have been some internal changes that *should* make TFF user experience generally easier, but you are hitting a thorny edge case. Working on a fix now.

Thanks again for the report!

**Comment by DanielNolte** [comment]
Okay, thank you for your help. Let me know what else I need to do.

**Comment by DanielNolte** [comment]
That fixed the error. Thank you again.
