### ISSUE TITLE
How can a client maintain its state

### ISSUE THREAD

**Issue by anupamme** [tensorflow/federated#894]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I am trying to write an adaptive client who can be an adversary as well. This client wants to be stateful so it will keep some variables from the last round.

**Describe the solution you'd like**

 I would like each client to be able to maintain a local cache so if there is a client identifier e.g. id_XX, then global_cache[id_XX] to be accessible to client id_XX.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

I could maintain a cache in attacked_fedavg.ClientProjectBoost however, the client id is not available.

**Additional context**
Add any other context about the feature request here.

There should be Client Class and Server Class and each of them should have an id associated.

**Comment by PraChetit** [comment]
This seems more suitable for StackOverflow. Please see [this question](https://stackoverflow.com/questions/63498907/is-there-a-way-for-tff-clients-to-have-internal-states) to see if it addresses your need.
