### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by AshiakerWang** [tensorflow/federated#895]
**While trying to build from source according to the [instructions](https://github.com/tensorflow/federated/blob/master/docs/install.md), I encountered the following error:**

`ERROR: /home/wzy/TF_privacy/Federated_Learning/federated/tensorflow_federated/tools/development/BUILD:9:10: failed to create symbolic link 'tensorflow_federated/tools/development/build_pip_package': file 'tensorflow_federated/tools/development/build_pip_package.sh' is not executable Target //tensorflow_federated/tools/development:build_pip_package failed to build Use --verbose_failures to see the command lines of failed build steps.
`

**Here is the full screenshot of the output:** 
![image](https://user-images.githubusercontent.com/14258909/91701163-78fbf500-eba9-11ea-8a63-27aca0a654e4.png)

**My configuration  are as follows:**

- tensorflow==2.0.0
- Ubuntu 18.04.3
- python = 3.7.5

**Comment by michaelreneer** [comment]
Can you share the output of running the following command from the repository directory.

```bash
ls -la "tensorflow_federated/tools/development"
```

**Comment by AshiakerWang** [comment]
Sure. Here is the corresponding output of the script:
![image](https://user-images.githubusercontent.com/14258909/91780285-ac7e6400-ec29-11ea-81e8-b0b56523e022.png)

**Comment by michaelreneer** [comment]
So the problem is that those scripts are not executable. You can find about more about `chmod` here https://linux.die.net/man/1/chmod.

I think the simplest option is to just run...

```
chmod +x tensorflow_federated/tools/development/build_pip_package.sh
```

**Comment by AshiakerWang** [comment]
> So the problem is that those scripts are not executable. You can find about more about `chmod` here https://linux.die.net/man/1/chmod.
> 
> I think the simplest option is to just run...
> 
> ```
> chmod +x tensorflow_federated/tools/development/build_pip_package.sh
> ```
> 
> Please let me know if this resolves your issue.

It worked for me. Thank you very much !
