### ISSUE TITLE
`tff.simulation.datasets.emnist.load_data()` extract(unzip) the dataset every time it runs

### ISSUE THREAD

**Issue by hongliny** [tensorflow/federated#896]
**Describe the bug**
`tff.simulation.datasets.emnist.load_data()` will extract(unzip) the `h5` dataset **every time** it runs. The cache mode will only cache the `.tar.bz2` file (see [here](https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/simulation/datasets/stackoverflow.py#L96)). For large dataset (say stackoverflow) it will take quite long time to extract. 

Also there is thread conflict issue if multiple parallel runs attempt to extract the same file.

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
* Python package versions (e.g., TensorFlow Federated, TensorFlow): TF 2.3, TFF 0.16.1
* Python version: 3.7
* Bazel version (if building from source): 3.4.1
* CUDA/cuDNN version: N/A
* What TensorFlow Federated execution stack are you using? N/A

**Expected behavior**
`h5` dataset to be properly cached.

**Additional context**
N/A

**Comment by ymodak** [comment]
cc @zcharles8 (as per git blame) Can you please help/route to code owner?

**Comment by ZacharyGarrett** [comment]
This should be fixed by https://github.com/tensorflow/federated/commit/7bb20162f96e3d5bc28ce50b206de0138d9894eb

The datasets should be uncompressed once, during download. After that the uncompressed files are cached and re-used.
