### ISSUE TITLE
`tff.learning.from_keras_model` does not accept subclassed Keras model

### ISSUE THREAD

**Issue by hongliny** [tensorflow/federated#897]
**Describe the bug**
`tff.learning.from_keras_model()` does not accept subclassed keras model. See this [colab](https://colab.research.google.com/drive/1dPJlo3e6vVHXS9O4Pm3_Qq2c_h0VtRaP?usp=sharing).

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
* Python package versions (e.g., TensorFlow Federated, TensorFlow): Colab TF-nightly TFF-nightly
* Python version: python 3.6
* Bazel version (if building from source): N/A
* CUDA/cuDNN version: N/A
* What TensorFlow Federated execution stack are you using? N/A

**Expected behavior**
`tff.learning.from_keras_model()` properly accepts subclassed keras model, or provide info on the doc if this is not possible?

**Additional context**
The issue seems to be due to `from_keras_model()` consuming `tf.keras.model.output` (see [pointer](https://github.com/tensorflow/federated/blob/v0.16.1/tensorflow_federated/python/learning/keras_utils.py#L260)) which is not written when the model is subclassed.

**Comment by nightldj** [comment]
Thanks Honglin! One option is to write your own keras model wrapper, or tff.learning.Model. It should not be very difficult, but you may loose some flexibility on things like keras metricss. Examples can be found at https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/examples/simple_fedavg/simple_fedavg_tf.py#L38
and https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/examples/simple_fedavg/simple_fedavg_test.py#L137

**Comment by jkr26** [comment]
This behavior is definitely TFF working as intended. TFF is strongly typed and neds to be able to reason about the output shapes and types of the functions it invokes.

But definitely we should update our documentation. Writing such a change now.
