### ISSUE TITLE
Memory explosion

### ISSUE THREAD

**Issue by matech96** [tensorflow/federated#903]
While running the following command:
`bazel run main:federated_trainer -- --task=cifar100 --total_rounds=1500 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 --server_optimizer=sgd --server_learning_rate=1 --clients_per_round=10 --client_epochs_per_round=1 --experiment_name=cifar100_fedavg`
the VRAM usage explodes.
It quickly reaches 8.9 GB in the first round. It remains stable, until around the 125. round, when it doubles to 16.9 GB. This phenomenon repeats itself until the training crashes.

**Comment by zcharles8** [comment]
Hi @matech96. Can you verify that you are using the latest version of TFF? If so, can you see what happens when you set `clients_per_round=1`?

**Comment by matech96** [comment]
I'm using version 0.16.1, which is the latest as I can tell. It is reproducible with `clients_per_round=1` as well. It starts off with 4.9 GB, then around the 70. round, jumps to 8.9 GB.

**Comment by hongliny** [comment]
I also got into this memory explosion issue when running TFF 0.16.1 on GPU (a single GPU). I would be happy to provide more details if needed

**Comment by zcharles8** [comment]
I am marking this as resolved (see google-research/federated#29 for context).
