### ISSUE TITLE
Add an assertion maybe cause other problems?

### ISSUE THREAD

**Issue by catdogpandas** [tensorflow/federated#911]
https://github.com/tensorflow/federated/blob/b47440fa531b738d84a710f22f5f0fd5627254c4/tensorflow_federated/python/core/utils/differential_privacy.py#L210
The " # TODO(b/140236959): Add an assertion that weight is None here" above cannot fit the scenario below. 
"Stateful_delta_aggregate_fn" may be tff.utils.StatefulAggregateFn or tff.utils.build_dp_aggregate.
https://github.com/tensorflow/federated/blob/b47440fa531b738d84a710f22f5f0fd5627254c4/tensorflow_federated/python/research/targeted_attack/attacked_fedavg.py#L392

**Comment by michaelreneer** [comment]
This assertion no longer exists.
