### ISSUE TITLE
federated/tensorflow_federated/python/examples/simple_fedavg/emnist_fedavg_main.py does not run from fresh install

### ISSUE THREAD

**Issue by JustoA** [tensorflow/federated#912]
**Describe the bug**
Running federated/tensorflow_federated/python/examples/simple_fedavg/emnist_fedavg_main.py errors out with a sizeable traceback that I've included [here](https://gist.github.com/JustoA/d9b5ab836496369d7a210297eed30869) when running from fresh install. 
The error that I think is the cause is: `TypeError: ReferenceResolvingExecutor asked to create call with incompatible type specifications. Function takes an argument of type <model_weights=<trainable=<float32[5,5,1,32],float32[32],float32[5,5,32,64],float32[64],float32[3136,512],float32[512],float32[512,10],float32[10]>,non_trainable=<>>,optimizer_state=<int64>,round_num=int32>, but was supplied an argument of type <model_weights=<non_trainable=<>,trainable=<>>,optimizer_state=<int64>,round_num=int32>`.

**Environment:**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.1 LTS
* Python package versions (e.g., TensorFlow Federated, TensorFlow): 
Tensorflow 2.2.1
tensorflow-federated-nightly 0.16.1.dev20200928
tf-estimator-nightly==2.4.0.dev2020092701
tf-nightly==2.4.0.dev20200927
tfa-nightly==0.12.0.dev20200927184204

* Python version: 3.8.2
* Bazel version (if building from source):  Bazelisk version: v1.6.1
* CUDA/cuDNN version: N/A
* What TensorFlow Federated execution stack are you using?
The default one, I'm not entirely sure what this means.

**Expected behavior**
I expected the example file to run without error.

**Additional context**
I'm running this within a pycharm venv. I also had to change some imports in the example directory from
`from tensorflow_federated.python.examples.simple_fedavg import simple_fedavg_tf
from tensorflow_federated.python.examples.simple_fedavg import simple_fedavg_tff`

to

`from federated.tensorflow_federated.python.examples.simple_fedavg import simple_fedavg_tf
from federated.tensorflow_federated.python.examples.simple_fedavg import simple_fedavg_tff`.

I've also tried installing just from pip, but the same error occurs.

**Comment by JustoA** [comment]
FYI This may be a Python 3.8 Issue. Running with 3.6 works just fine.

**Comment by nightldj** [comment]
@michaelreneer , could you comment on the python version issue? Thanks!

**Comment by michaelreneer** [comment]
@JustoA I think this is correct. I have not been able to dig into this yet, but I have seen failures with Python 3.8 before in some of our downstream dependencies and possibly in TFF as well. We do need to track this issue, but right now you have a work around correct?

**Comment by JustoA** [comment]
@michaelreneer Yes, the workaround is running Python 3.6 instead of 3.8.

**Comment by nightldj** [comment]
@JustoA Hi, we have a new release and now tested under python 3.8. Could you try it our again, or close this issue if it is no longer an interest? Thanks!

**Comment by JustoA** [comment]
I'll get on this ASAP

**Comment by JustoA** [comment]
Yep, can confirm it's working as intended! Thanks y'all
