### ISSUE TITLE
Expected TFF type {float32*}@CLIENTS, which is not assignable from <<float32,float32>,<float32>,<float32,float32,float32>>.

### ISSUE THREAD

**Issue by wxthu** [tensorflow/federated#917]
**Describe the bug**
A clear and concise description of what the bug is. It is often helpful to
provide a link to a [colab](https://colab.research.google.com/) notebook that
reproduces the bug.

**Environment (please complete the following information):**
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* Python package versions (e.g., TensorFlow Federated, TensorFlow):
* Python version:
* Bazel version (if building from source):
* CUDA/cuDNN version:
* What TensorFlow Federated execution stack are you using?

Note: You can collect the Python package information by running `pip3 freeze`
from the command line and most of the other information can be collected using
TensorFlows environment capture
[script](https://github.com/tensorflow/tensorflow/blob/master/tools/tf_env_collect.sh).

**Expected behavior**

**Additional context**

**Comment by jkr26** [comment]
From the title here, this sounds like TFF's static typesystem working as intended. Perhaps posting the code raising this error on StackOverflow with the tensorflow-federated tag would be the best next step here.

**Comment by wxthu** [comment]
I encountered this error when I learned the tutorial [https://github.com/tensorflow/federated/blob/master/docs/tutorials/custom_federated_algorithms_1.ipynb](url)
![Uploading Screenshot from 2020-10-29 13-49-51.png…]()

**Comment by wxthu** [comment]
[Uploading Screenshot from 2020-10-29 13-49-51.png…]()

**Comment by wxthu** [comment]
x-special/nautilus-clipboard
copy
file:///home/wangxiang/Pictures/Screenshot%20from%202020-10-29%2013-49-51.png

**Comment by wxthu** [comment]
**get_global_temperature_average([[68.0, 70.0], [71.0], [68.0, 72.0, 70.0]])**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-95c690a2d13f> in <module>
----> 1 get_global_temperature_average([[68.0, 70.0], [71.0], [68.0, 72.0, 70.0]])

~/.local/lib/python3.8/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py in __call__(self, *args, **kwargs)
    518   def __call__(self, *args, **kwargs):
    519     context = self._context_stack.current
--> 520     arg = pack_args(self._type_signature.parameter, args, kwargs, context)
    521     return context.invoke(self, arg)
    522 

~/.local/lib/python3.8/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py in pack_args(parameter_type, args, kwargs, context)
    315       else:
    316         arg = pack_args_into_struct(args, kwargs, parameter_type, context)
--> 317       return context.ingest(arg, parameter_type)
    318 
    319 

~/.local/lib/python3.8/site-packages/tensorflow_federated/python/core/impl/tensorflow_context/tensorflow_computation_context.py in ingest(self, val, type_spec)
     39 
     40   def ingest(self, val, type_spec):
---> 41     type_analysis.check_type(val, type_spec)
     42     return val
     43 

~/.local/lib/python3.8/site-packages/tensorflow_federated/python/core/impl/types/type_analysis.py in check_type(value, type_spec)
     89   value_type = type_conversions.infer_type(value)
     90   if not type_spec.is_assignable_from(value_type):
---> 91     raise TypeError(
     92         'Expected TFF type {}, which is not assignable from {}.'.format(
     93             type_spec, value_type))

TypeError: Expected TFF type {float32*}@CLIENTS, which is not assignable from <<float32,float32>,<float32>,<float32,float32,float32>>.
