### ISSUE TITLE
Allow TFF datasets to be accessed concurrently

### ISSUE THREAD

**Issue by scaldas** [tensorflow/federated#919]
**Is your feature request related to a problem? Please describe.**
TFF datasets can't be accessed concurrently from different processes (e.g., different experiments running on the same machine).

**Describe the solution you'd like**
My understanding is that this is due to TFF saving their datasets in HDF5 format, which doesn't allow for concurrent accesses to the data. Although this is desirable in some scenarios, it becomes an obstacle when the goal is to run several repetitions of an experiment (and you're constrained to one machine).  

**Describe alternatives you've considered**
The simplest alternative I've considered (and the one I'm currently using) is caching a copy of the dataset per experiment run (using the cache_dir parameter in TFF's load_data functions). However, this won't scale for larger datasets than EMNIST and Shakespeare (e.g., StackOverflow). I also looked into using [Parallel HDF5](https://docs.h5py.org/en/stable/mpi.html), but it's unclear to me how it would interact with TFF, TF, and blaze. 

**Additional context**
N/A

**Comment by jkr26** [comment]
Hi @scaldas !

There are currently some interesting talks underway with the `tf.data` team to support the (currently experimental) [`tf.data.experimental.SQLDataset`](https://www.tensorflow.org/api_docs/python/tf/data/experimental/SqlDataset?hl=en&version=nightly), primarily to support the implementation of a `dataset_computation` on our default external implementations of `ClientData` objects. But if I understand correctly, this might also be able to allow for concurrent access to the data.

I think this will be fairly slow-moving if it is left to @ZacharyGarrett and myself to push in our downtime. If we could get `tf.data` to promote the `SQLDataset` symbol, would you be interested in contributing a `SQLClientData` implementation?
