### ISSUE TITLE
Non-IID data distribution for a custom dataset

### ISSUE THREAD

**Issue by avinashsai** [tensorflow/federated#922]
Current built in API's support only few datasets in a Non-IID setting. How can we create a Non-IID data distribution for a custom text dataset?

**Comment by CSJDeveloper** [comment]
@avinashsai I have the same problem.

**Comment by jkr26** [comment]
@CSJDeveloper, @avinashsai 

There are a few different ways that this can be done, generally depending on the data you have now. [This StackOverflow post](https://stackoverflow.com/questions/58965488/how-to-create-federated-dataset-from-a-csv-file) may be useful.

One thing to note--if your existing dataset does not contain a natural user-keyed structure, you will have to first determine a strategy for creating synthetic non-iid-ness. TFF distributes a [synthetic partitioning of CIFAR100](https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/cifar100/load_data) which may be helpful as inspiration.

Generally, we prefer using StackOverflow for usage questions and federated computing questions in general, and reserving GitHub issues for bugs. This is an excellent question! Closing, however, for this reason.
