### ISSUE TITLE
How to load Fashion MNIST dataset in Tensorflow Fedarated?

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [tensorflow/federated#923]
Hello TensorFlow team, recently i asked this question on StackOverflow i provide more details in the link. Please consider if y have  appropriate time to take a quick look around and give any solution.thnx in advance

https://stackoverflow.com/questions/64760396/how-to-load-fashion-mnist-dataset-in-tensorflow-fedarated

**Comment by jkr26** [comment]
I see @ZacharyGarrett answered this question on the 10th and the answer has since been accepted; closing, seems like weve got a good resolution!
