### ISSUE TITLE
import error in google colab

### ISSUE THREAD

**Issue by chzhyang** [tensorflow/federated#930]
import error
[https://colab.research.google.com/drive/1LnDOu076TBeaJT6yjnnNkSyim_GdpCxD?usp=sharing](url)
at the same time, I can not open the tutorial:[https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb](url)

My code:
`import collections  
import numpy as np   
import tensorflow as tf   
import tensorflow_federated as tff   
np.random.seed(0)   
tff.federated_computation(lambda: 'Hello, World!')()  
`

ImportError                              Traceback (most recent call last)
<ipython-input-7-a23308ec3f7c> in <module>()
      3 import numpy as np
      4 import tensorflow as tf
----> 5 import tensorflow_federated as tff
      6 
      7 np.random.seed(0)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/compat/v1/types/experimental/__init__.py in <module>()
      8 import sys as _sys
      9 
---> 10 from tensorflow.python.types.core import TensorLike
     11 
     12 del _print_function

ImportError: cannot import name 'TensorLike'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by hbmcmahan** [comment]
I just verifed that [the tutorial](https://colab.research.google.com/github/tensorflow/federated/blob/master/docs/tutorials/federated_learning_for_image_classification.ipynb) is working for me. When you say you can't open it, what error are you getting?

Perhaps you need something like this in your colab to get the latest version of TFF and TF?
```
!pip uninstall --yes tensorboard tb-nightly

!pip install --quiet --upgrade tensorflow_federated_nightly
!pip install --quiet --upgrade nest_asyncio
!pip install --quiet tb-nightly  # or tensorboard, but not both

import nest_asyncio
nest_asyncio.apply()
```

**Comment by ZacharyGarrett** [comment]
Closing after no response for 2 months. Please feel free to re-open if the behavior can be reproduced.
