### ISSUE TITLE
TFF with web browser clients

### ISSUE THREAD

**Issue by thankrandomness** [tensorflow/federated#950]
I am hoping to use TFF to do federated learning with web-based clients from the browser environments using javascript. There was an [issue](https://github.com/tensorflow/federated/issues/229) related to this before. Not sure if there's been any interest or activity to support this request.

As described by @krzys-ostrowski in the [issue#229](https://github.com/tensorflow/federated/issues/229), I would like to see an in-browser JS runtime for executing TFF computations.

I am also looking at openmined Syft framework that has support for web-based clients through their syft.js worker library which is based on tensorflow.js. It would be great if TFF also has support for web-based clients.

Thanks,
Vijay

**Comment by amirdib** [comment]
Any news on this feature ?

**Comment by UPstartDeveloper** [comment]
Could I maybe help on this @ZacharyGarrett?

**Comment by bhack** [comment]
Please check:

https://github.com/epfml/disco

**Comment by krzys-ostrowski** [comment]
We do not take feature requests from the community at this point, but contributions to the ecosystem are always welcome. Anything that speaks the TFF protocol defined in executor.proto and the Executor interfaces can be used as a part of a TFF runtime. This would be a relatively simple addition. If you'd like to contribute a component to the TFF repo, we'd just need to ensure that it's consitent with the rest of the ecosystem and that it would be properly maintained long-term. Please take a look at [the ](https://discuss.tensorflow.org/c/special-interest-groups/sig-federated/)(SIG Federated) or the Discord channel referenced there. Thanks!
