### ISSUE TITLE
a problem of parameter

### ISSUE THREAD

**Issue by Chun78HunZi** [tensorflow/federated#972]
In TFF, which parameter defines how many clients are selected for training in each round? TFF version is 0.15

**Comment by ZacharyGarrett** [comment]
GitHub Issues is more of a forum for discussing bugs, feature requests, and other issues with the code/software. The [`tensorflow-federated`](https://stackoverflow.com/questions/tagged/tensorflow-federated) tag on StackOverflow is a better places for questions about how to _use_ TFF, would you mind re-asking your question there?
