### ISSUE TITLE
a problem of  CPU resources

### ISSUE THREAD

**Issue by Chun78HunZi** [tensorflow/federated#973]
On the same machine, if more clients are defined, will running TFF consume more CPU resources? Neural network runs on GPU

**Comment by ZacharyGarrett** [comment]
In general yes, more clients typically starts more threads which run in parallel and will try to consume more CPU resources. In some sense it is performing a type of _data parallelism_. Note that TensorFlow will use both CPU (e.g. data pipelines) and GPU (math operations, e.g. matmul) for executing neural networks.
